dataCityJson = {
	"list": [{
		"groupname": "A",
		"citylist": [{
			"dataSpac": "am",
			"dataTags": "macau",
			"dataSzm": "MFM",
			"dataValue": "澳门"
		}, {
			"dataSpac": "as",
			"dataTags": "anshan",
			"dataSzm": "AOG",
			"dataValue": "鞍山"
		}]
	}, {
		"groupname": "B",
		"citylist": [{
			"dataSpac": "bj",
			"dataTags": "beijing",
			"dataSzm": "PEK",
			"dataValue": "北京"
		}, {
			"dataSpac": "bj",
			"dataTags": "beijing",
			"dataSzm": "NAY",
			"dataValue": "北京"
		}, {
			"dataSpac": "bn",
			"dataTags": "xishuangbanna",
			"dataSzm": "JHG",
			"dataValue": "西双版纳"
		}, {
			"dataSpac": "bt",
			"dataTags": "baotou",
			"dataSzm": "BAV",
			"dataValue": "包头"
		}, {
			"dataSpac": "baishan",
			"dataTags": "baishan",
			"dataSzm": "NBS",
			"dataValue": "白山"
		}]
	}, {
		"groupname": "C",
		"citylist": [{
			"dataSpac": "cq",
			"dataTags": "chongqing",
			"dataSzm": "CKG",
			"dataValue": "重庆"
		}, {
			"dataSpac": "cd",
			"dataTags": "chengdu",
			"dataSzm": "CTU",
			"dataValue": "成都"
		}, {
			"dataSpac": "chs",
			"dataTags": "changsha",
			"dataSzm": "CSX",
			"dataValue": "长沙"
		}, {
			"dataSpac": "cc",
			"dataTags": "changchun",
			"dataSzm": "CGQ",
			"dataValue": "长春"
		}, {
			"dataSpac": "cz",
			"dataTags": "changzhou",
			"dataSzm": "CZX",
			"dataValue": "常州"
		}]
	}, {
		"groupname": "D",
		"citylist": [{
			"dataSpac": "dt",
			"dataTags": "datong",
			"dataSzm": "DAT",
			"dataValue": "大同"
		}, {
			"dataSpac": "dl",
			"dataTags": "dalian",
			"dataSzm": "DLC",
			"dataValue": "大连"
		}, {
			"dataSpac": "dali",
			"dataTags": "dali",
			"dataSzm": "DLU",
			"dataValue": "大理"
		}, {
			"dataSpac": "dandong",
			"dataTags": "dandong",
			"dataSzm": "DDG",
			"dataValue": "丹东"
		}, {
			"dataSpac": "dq",
			"dataTags": "daqing",
			"dataSzm": "DQA",
			"dataValue": "大庆"
		}]
	}, {
		"groupname": "E",
		"citylist": [{
			"dataSpac": "erds",
			"dataTags": "eerduosi",
			"dataSzm": "DSN",
			"dataValue": "鄂尔多斯"
		}]
	}, {
		"groupname": "F",
		"citylist": [{
			"dataSpac": "fz",
			"dataTags": "fuzhou",
			"dataSzm": "FOC",
			"dataValue": "福州"
		}, {
			"dataSpac": "fs",
			"dataTags": "foshan",
			"dataSzm": "FUO",
			"dataValue": "佛山"
		}]
	}, {
		"groupname": "G",
		"citylist": [{
			"dataSpac": "gz",
			"dataTags": "guangzhou",
			"dataSzm": "CAN",
			"dataValue": "广州"
		}, {
			"dataSpac": "gl",
			"dataTags": "guilin",
			"dataSzm": "KWL",
			"dataValue": "桂林"
		}, {
			"dataSpac": "gy",
			"dataTags": "guiyang",
			"dataSzm": "KWE",
			"dataValue": "贵阳"
		}, {
			"dataSpac": "gaoxiong",
			"dataTags": "kaohsiung",
			"dataSzm": "KHH",
			"dataValue": "高雄"
		}]
	}, {
		"groupname": "H",
		"citylist": [{
			"dataSpac": "hz",
			"dataTags": "hangzhou",
			"dataSzm": "HGH",
			"dataValue": "杭州"
		}, {
			"dataSpac": "haikou",
			"dataTags": "haikou",
			"dataSzm": "HAK",
			"dataValue": "海口"
		}, {
			"dataSpac": "hk",
			"dataTags": "hongkong",
			"dataSzm": "HKG",
			"dataValue": "香港"
		}, {
			"dataSpac": "hf",
			"dataTags": "hefei",
			"dataSzm": "HFE",
			"dataValue": "合肥"
		}, {
			"dataSpac": "hrb",
			"dataTags": "haerbin",
			"dataSzm": "HRB",
			"dataValue": "哈尔滨"
		}, {
			"dataSpac": "hu",
			"dataTags": "huhehaote",
			"dataSzm": "HET",
			"dataValue": "呼和浩特"
		}, {
			"dataSpac": "hualian",
			"dataTags": "hualian",
			"dataSzm": "HLN",
			"dataValue": "花莲"
		}, {
			"dataSpac": "huizhou",
			"dataTags": "huizhou",
			"dataSzm": "HUZ",
			"dataValue": "惠州"
		}, {
			"dataSpac": "hlbe",
			"dataTags": "hulunbeier",
			"dataSzm": "HLD",
			"dataValue": "呼伦贝尔"
		}, {
			"dataSpac": "ha",
			"dataTags": "huaian",
			"dataSzm": "HIA",
			"dataValue": "淮安"
		}, {
			"dataSpac": "huangshan",
			"dataTags": "huangshan",
			"dataSzm": "TXN",
			"dataValue": "黄山"
		}, {
			"dataSpac": "hle",
			"dataTags": "hailaer",
			"dataSzm": "HLD",
			"dataValue": "海拉尔"
		}]
	}, {
		"groupname": "J",
		"citylist": [{
			"dataSpac": "jn",
			"dataTags": "jinan",
			"dataSzm": "TNA",
			"dataValue": "济南"
		}, {
			"dataSpac": "jj",
			"dataTags": "jiujiang",
			"dataSzm": "JIU",
			"dataValue": "九江"
		}, {
			"dataSpac": "jl",
			"dataTags": "jilin",
			"dataSzm": "JIL",
			"dataValue": "吉林"
		}, {
			"dataSpac": "jx",
			"dataTags": "jiaxing",
			"dataSzm": "HGH",
			"dataValue": "嘉兴"
		}]
	}, {
		"groupname": "K",
		"citylist": [{
			"dataSpac": "km",
			"dataTags": "kunming",
			"dataSzm": "KMG",
			"dataValue": "昆明"
		}]
	}, {
		"groupname": "L",
		"citylist": [{
			"dataSpac": "luoyang",
			"dataTags": "luoyang",
			"dataSzm": "LYA",
			"dataValue": "洛阳"
		}, {
			"dataSpac": "lz",
			"dataTags": "lanzhou",
			"dataSzm": "LHW",
			"dataValue": "兰州"
		}, {
			"dataSpac": "lj",
			"dataTags": "lijiang",
			"dataSzm": "LJG",
			"dataValue": "丽江"
		}, {
			"dataSpac": "lasa",
			"dataTags": "lasa",
			"dataSzm": "LXA",
			"dataValue": "拉萨"
		}, {
			"dataSpac": "liuzhou",
			"dataTags": "liuzhou",
			"dataSzm": "LZH",
			"dataValue": "柳州"
		}, {
			"dataSpac": "linyi",
			"dataTags": "linyi",
			"dataSzm": "LYI",
			"dataValue": "临沂"
		}, {
			"dataSpac": "ly",
			"dataTags": "longyan",
			"dataSzm": "LCX",
			"dataValue": "龙岩"
		}]
	}, {
		"groupname": "M",
		"citylist": [{
			"dataSpac": "mianyang",
			"dataTags": "mianyang",
			"dataSzm": "MIG",
			"dataValue": "绵阳"
		}, {
			"dataSpac": "manzl",
			"dataTags": "manzhouli",
			"dataSzm": "NZH",
			"dataValue": "满洲里"
		}]
	}, {
		"groupname": "N",
		"citylist": [{
			"dataSpac": "nj",
			"dataTags": "nanjing",
			"dataSzm": "NKG",
			"dataValue": "南京"
		}, {
			"dataSpac": "nb",
			"dataTags": "ningbo",
			"dataSzm": "NGB",
			"dataValue": "宁波"
		}, {
			"dataSpac": "nn",
			"dataTags": "nanning",
			"dataSzm": "NNG",
			"dataValue": "南宁"
		}, {
			"dataSpac": "nt",
			"dataTags": "nantong",
			"dataSzm": "NTG",
			"dataValue": "南通"
		}, {
			"dataSpac": "nc",
			"dataTags": "nanchang",
			"dataSzm": "KHN",
			"dataValue": "南昌"
		}]
	}, {
		"groupname": "Q",
		"citylist": [{
			"dataSpac": "qd",
			"dataTags": "qingdao",
			"dataSzm": "TAO",
			"dataValue": "青岛"
		}, {
			"dataSpac": "qz",
			"dataTags": "quanzhou",
			"dataSzm": "JJN",
			"dataValue": "泉州"
		}, {
			"dataSpac": "qf",
			"dataTags": "qufu",
			"dataSzm": "JNG",
			"dataValue": "曲阜"
		}, {
			"dataSpac": "qhd",
			"dataTags": "qinhuangdao",
			"dataSzm": "SHP",
			"dataValue": "秦皇岛"
		}, {
			"dataSpac": "qqhr",
			"dataTags": "qiqihaer",
			"dataSzm": "NDG",
			"dataValue": "齐齐哈尔"
		}]
	}, {
		"groupname": "S",
		"citylist": [{
			"dataSpac": "sh",
			"dataTags": "shanghai",
			"dataSzm": "SHA",
			"dataValue": "上海"
		}, {
			"dataSpac": "sh",
			"dataTags": "shanghai",
			"dataSzm": "PVG",
			"dataValue": "上海"
		}, {
			"dataSpac": "sz",
			"dataTags": "shenzhen",
			"dataSzm": "SZX",
			"dataValue": "深圳"
		}, {
			"dataSpac": "sanya",
			"dataTags": "sanya",
			"dataSzm": "SYX",
			"dataValue": "三亚"
		}, {
			"dataSpac": "sy",
			"dataTags": "shenyang",
			"dataSzm": "SHE",
			"dataValue": "沈阳"
		}, {
			"dataSpac": "su",
			"dataTags": "suzhou",
			"dataSzm": "WUX",
			"dataValue": "苏州"
		}, {
			"dataSpac": "sjz",
			"dataTags": "shijiazhuang",
			"dataSzm": "SJW",
			"dataValue": "石家庄"
		}, {
			"dataSpac": "st",
			"dataTags": "shantou",
			"dataSzm": "SWA",
			"dataValue": "汕头"
		}, {
			"dataSpac": "sx",
			"dataTags": "shaoxing",
			"dataSzm": "HGH",
			"dataValue": "绍兴"
		}]
	}, {
		"groupname": "T",
		"citylist": [{
			"dataSpac": "tj",
			"dataTags": "tianjin",
			"dataSzm": "TSN",
			"dataValue": "天津"
		}, {
			"dataSpac": "ty",
			"dataTags": "taiyuan",
			"dataSzm": "TYN",
			"dataValue": "太原"
		}, {
			"dataSpac": "tb",
			"dataTags": "taipei",
			"dataSzm": "TPE",
			"dataValue": "台北"
		}, {
			"dataSpac": "tb",
			"dataTags": "taipei",
			"dataSzm": "TSA",
			"dataValue": "台北"
		}, {
			"dataSpac": "taizhong",
			"dataTags": "taichung",
			"dataSzm": "RMQ",
			"dataValue": "台中"
		}, {
			"dataSpac": "tz",
			"dataTags": "taizhou",
			"dataSzm": "HYN",
			"dataValue": "台州"
		}]
	}, {
		"groupname": "W",
		"citylist": [{
			"dataSpac": "wh",
			"dataTags": "wuhan",
			"dataSzm": "WUH",
			"dataValue": "武汉"
		}, {
			"dataSpac": "wz",
			"dataTags": "wenzhou",
			"dataSzm": "WNZ",
			"dataValue": "温州"
		}, {
			"dataSpac": "weihai",
			"dataTags": "weihai",
			"dataSzm": "WEH",
			"dataValue": "威海"
		}, {
			"dataSpac": "wx",
			"dataTags": "wuxi",
			"dataSzm": "WUX",
			"dataValue": "无锡"
		}]
	}, {
		"groupname": "X",
		"citylist": [{
			"dataSpac": "xa",
			"dataTags": "xian",
			"dataSzm": "XIY",
			"dataValue": "西安"
		}, {
			"dataSpac": "xm",
			"dataTags": "xiamen",
			"dataSzm": "XMN",
			"dataValue": "厦门"
		}, {
			"dataSpac": "xj",
			"dataTags": "wulumuqi",
			"dataSzm": "URC",
			"dataValue": "乌鲁木齐"
		}, {
			"dataSpac": "xgll",
			"dataTags": "xianggelila",
			"dataSzm": "DIG",
			"dataValue": "香格里拉"
		}, {
			"dataSpac": "xn",
			"dataTags": "xining",
			"dataSzm": "XNN",
			"dataValue": "西宁"
		}, {
			"dataSpac": "xichang",
			"dataTags": "xichang",
			"dataSzm": "XIC",
			"dataValue": "西昌"
		}, {
			"dataSpac": "xz",
			"dataTags": "xuzhou",
			"dataSzm": "XUZ",
			"dataValue": "徐州"
		}]
	}, {
		"groupname": "Y",
		"citylist": [{
			"dataSpac": "yuncheng",
			"dataTags": "yuncheng",
			"dataSzm": "YCU",
			"dataValue": "运城"
		}, {
			"dataSpac": "yt",
			"dataTags": "yantai",
			"dataSzm": "YNT",
			"dataValue": "烟台"
		}, {
			"dataSpac": "yl",
			"dataTags": "yulin",
			"dataSzm": "UYN",
			"dataValue": "榆林"
		}, {
			"dataSpac": "yinchuan",
			"dataTags": "yinchuan",
			"dataSzm": "INC",
			"dataValue": "银川"
		}, {
			"dataSpac": "yz",
			"dataTags": "yangzhou",
			"dataSzm": "YTY",
			"dataValue": "扬州"
		}, {
			"dataSpac": "yiwu",
			"dataTags": "yiwu",
			"dataSzm": "YIW",
			"dataValue": "义乌"
		}]
	}, {
		"groupname": "Z",
		"citylist": [{
			"dataSpac": "zh",
			"dataTags": "zhuhai",
			"dataSzm": "ZUH",
			"dataValue": "珠海"
		}, {
			"dataSpac": "zz",
			"dataTags": "zhengzhou",
			"dataSzm": "CGO",
			"dataValue": "郑州"
		}, {
			"dataSpac": "zunyi",
			"dataTags": "zunyi",
			"dataSzm": "ZYI",
			"dataValue": "遵义"
		}, {
			"dataSpac": "zhoushan",
			"dataTags": "zhoushan",
			"dataSzm": "HSN",
			"dataValue": "舟山"
		}]
	}],
	"hotList": [{
			"dataSpac": "CC",
			"dataTags": "CHANGCHUN",
			"dataSzm": "CGQ",
			"dataValue": "长春"
		}, {
			"dataSpac": "BJ",
			"dataTags": "BEIJING",
			"dataSzm": "PEK",
			"dataValue": "北京"
		}, {
			"dataSpac": "SH",
			"dataTags": "SHANGHAI",
			"dataSzm": "SHA",
			"dataValue": "上海"
		}, {
			"dataSpac": "GZ",
			"dataTags": "GUANGZHOU",
			"dataSzm": "CAN",
			"dataValue": "广州"
		}, {
			"dataSpac": "CD",
			"dataTags": "CHENGDU",
			"dataSzm": "CTU",
			"dataValue": "成都"
		}, {
			"dataSpac": "SZ",
			"dataTags": "SHENZHEN",
			"dataSzm": "SZX",
			"dataValue": "深圳"
		}]
	
}