dataCityJson = {
	list: [{
		groupname: "A",
		citylist: [{
			dataValue: "阿勒泰",
			dataCity: "阿勒泰",
			dataSpac: "ALT",
			dataSzm: "AAT",
			dataTags: "ALETAI"
		}, {
			dataValue: "阿坝",
			dataCity: "阿坝",
			dataSpac: "AB",
			dataSzm: "AHJ",
			dataTags: "ABA"
		}, {
			dataValue: "安康",
			dataCity: "安康",
			dataSpac: "AK",
			dataSzm: "AKA",
			dataTags: "ANKANG"
		}, {
			dataValue: "阿克苏",
			dataCity: "阿克苏",
			dataSpac: "AKS",
			dataSzm: "AKU",
			dataTags: "AKESU"
		}, {
			dataValue: "鞍山",
			dataCity: "鞍山",
			dataSpac: "AS",
			dataSzm: "AOG",
			dataTags: "ANSHAN"
		}, {
			dataValue: "安庆",
			dataCity: "安庆",
			dataSpac: "AQ",
			dataSzm: "AQG",
			dataTags: "ANQING"
		}, {
			dataValue: "安顺",
			dataCity: "安顺",
			dataSpac: "AS",
			dataSzm: "AVA",
			dataTags: "ANSHUN"
		}, {
			dataValue: "阿拉善左旗",
			dataCity: "阿拉善左旗",
			dataSpac: "ALS",
			dataSzm: "AXF",
			dataTags: "ALASHAN"
		}, {
			dataValue: "阿里",
			dataCity: "阿里",
			dataSpac: "AL",
			dataSzm: "NGQ",
			dataTags: "ALI"
		}, {
			dataValue: "阿拉善右旗",
			dataCity: "阿拉善右旗",
			dataSpac: "ALS",
			dataSzm: "RHT",
			dataTags: "ALASHAN"
		}, {
			dataValue: "阿尔山",
			dataCity: "阿尔山",
			dataSpac: "AES",
			dataSzm: "YIE",
			dataTags: "AERSHAN"
		}]
	}, {
		groupname: "B",
		citylist: [{
			dataValue: "百色",
			dataCity: "百色",
			dataSpac: "BS",
			dataSzm: "AEB",
			dataTags: "BAISE"
		}, {
			dataValue: "包头",
			dataCity: "包头",
			dataSpac: "BT",
			dataSzm: "BAV",
			dataTags: "BAOTOU"
		}, {
			dataValue: "毕节",
			dataCity: "毕节",
			dataSpac: "BJ",
			dataSzm: "BFJ",
			dataTags: "BIJIE"
		}, {
			dataValue: "蚌埠",
			dataCity: "蚌埠",
			dataSpac: "BB",
			dataSzm: "BFU",
			dataTags: "BENGBU"
		}, {
			dataValue: "北海",
			dataCity: "北海",
			dataSpac: "BH",
			dataSzm: "BHY",
			dataTags: "BEIHAI"
		}, {
			dataValue: "博乐",
			dataCity: "博乐",
			dataSpac: "BL",
			dataSzm: "BPL",
			dataTags: "BOLE"
		}, {
			dataValue: "保山",
			dataCity: "保山",
			dataSpac: "BS",
			dataSzm: "BSD",
			dataTags: "BAOSHAN"
		}, {
			dataValue: "北京",
			dataCity: "北京",
			dataSpac: "BJ",
			dataSzm: "PEK",
			dataTags: "BEIJING"
		}, {
			dataValue: "巴彦淖尔",
			dataCity: "巴彦淖尔",
			dataSpac: "BYNE",
			dataSzm: "RLK",
			dataTags: "BAYANNAOER"
		}]
	}, {
		groupname: "C",
		citylist: [{
			dataValue: "昌都",
			dataCity: "昌都",
			dataSpac: "CD",
			dataSzm: "BPX",
			dataTags: "CHANGDU"
		}, {
			dataValue: "广州",
			dataCity: "广州",
			dataSpac: "GZ",
			dataSzm: "CAN",
			dataTags: "CHUANGZHOU"
		}, {
			dataValue: "常德",
			dataCity: "常德",
			dataSpac: "CD",
			dataSzm: "CGD",
			dataTags: "CHANGDE"
		}, {
			dataValue: "长春",
			dataCity: "长春",
			dataSpac: "CC",
			dataSzm: "CGQ",
			dataTags: "CHANGCHUN"
		}, {
			dataValue: "朝阳",
			dataCity: "朝阳",
			dataSpac: "CY",
			dataSzm: "CHG",
			dataTags: "CHAOYANG"
		}, {
			dataValue: "赤峰",
			dataCity: "赤峰",
			dataSpac: "CF",
			dataSzm: "CIF",
			dataTags: "CHIFENG"
		}, {
			dataValue: "长治",
			dataCity: "长治",
			dataSpac: "CZ",
			dataSzm: "CIH",
			dataTags: "CHANGZHI"
		}, {
			dataValue: "重庆",
			dataCity: "重庆",
			dataSpac: "CQ",
			dataSzm: "CKG",
			dataTags: "CHONGQING"
		}, {
			dataValue: "长海",
			dataCity: "长海",
			dataSpac: "CH",
			dataSzm: "CNI",
			dataTags: "CHANGHAI"
		}, {
			dataValue: "长沙",
			dataCity: "长沙",
			dataSpac: "CS",
			dataSzm: "CSX",
			dataTags: "CHANGSHA"
		}, {
			dataValue: "成都",
			dataCity: "成都",
			dataSpac: "CD",
			dataSzm: "CTU",
			dataTags: "CHENGDU"
		}, {
			dataValue: "沧源",
			dataCity: "沧源",
			dataSpac: "CY",
			dataSzm: "CWJ",
			dataTags: "CANGYUAN"
		}, {
			dataValue: "常州",
			dataCity: "常州",
			dataSpac: "CZ",
			dataSzm: "CZX",
			dataTags: "CHANGZHOU"
		}, {
			dataValue: "长白山",
			dataCity: "长白山",
			dataSpac: "CBS",
			dataSzm: "NBS",
			dataTags: "CHANGBAISHAN"
		}]
	}, {
		groupname: "D",
		citylist: [{
			dataValue: "大同",
			dataCity: "大同",
			dataSpac: "DT",
			dataSzm: "DAT",
			dataTags: "DATONG"
		}, {
			dataValue: "达州",
			dataCity: "达州",
			dataSpac: "DZ",
			dataSzm: "DAX",
			dataTags: "DAZHOU"
		}, {
			dataValue: "稻城",
			dataCity: "稻城",
			dataSpac: "DC",
			dataSzm: "DCY",
			dataTags: "DAOCHENG"
		}, {
			dataValue: "丹东",
			dataCity: "丹东",
			dataSpac: "DD",
			dataSzm: "DDG",
			dataTags: "DANDONG"
		}, {
			dataValue: "迪庆",
			dataCity: "迪庆",
			dataSpac: "DQ",
			dataSzm: "DIG",
			dataTags: "DIQING"
		}, {
			dataValue: "大连",
			dataCity: "大连",
			dataSpac: "DL",
			dataSzm: "DLC",
			dataTags: "DALIAN"
		}, {
			dataValue: "大理",
			dataCity: "大理",
			dataSpac: "DL",
			dataSzm: "DLU",
			dataTags: "DALI"
		}, {
			dataValue: "敦煌",
			dataCity: "敦煌",
			dataSpac: "DH",
			dataSzm: "DNH",
			dataTags: "DUNHUANG"
		}, {
			dataValue: "东营",
			dataCity: "东营",
			dataSpac: "DY",
			dataSzm: "DOY",
			dataTags: "DONGYING"
		}, {
			dataValue: "大庆",
			dataCity: "大庆",
			dataSpac: "DQ",
			dataSzm: "DQA",
			dataTags: "DAQING"
		}, {
			dataValue: "德令哈",
			dataCity: "德令哈",
			dataSpac: "DLH",
			dataSzm: "HXD",
			dataTags: "DELINGHA"
		}]
	}, {
		groupname: "E",
		citylist: [{
			dataValue: "鄂尔多斯",
			dataCity: "鄂尔多斯",
			dataSpac: "ERDS",
			dataSzm: "DSN",
			dataTags: "EERDUOSI"
		}, {
			dataValue: "额济纳旗",
			dataCity: "额济纳旗",
			dataSpac: "EJNQ",
			dataSzm: "EJN",
			dataTags: "EJINAQI"
		}, {
			dataValue: "恩施",
			dataCity: "恩施",
			dataSpac: "ES",
			dataSzm: "ENH",
			dataTags: "ENSHI"
		}, {
			dataValue: "二连浩特",
			dataCity: "二连浩特",
			dataSpac: "ELHT",
			dataSzm: "ERL",
			dataTags: "ERLIANHAOTE"
		}]
	}, {
		groupname: "F",
		citylist: [{
			dataValue: "福州",
			dataCity: "福州",
			dataSpac: "FZ",
			dataSzm: "FOC",
			dataTags: "FUZHOU"
		}, {
			dataValue: "阜阳",
			dataCity: "阜阳",
			dataSpac: "FY",
			dataSzm: "FUG",
			dataTags: "FUYANG"
		}, {
			dataValue: "佛山",
			dataCity: "佛山",
			dataSpac: "FS",
			dataSzm: "FUO",
			dataTags: "FUOSHAN"
		}, {
			dataValue: "抚远",
			dataCity: "抚远",
			dataSpac: "FY",
			dataSzm: "FYJ",
			dataTags: "FUYUAN"
		}, {
			dataValue: "富蕴",
			dataCity: "富蕴",
			dataSpac: "FY",
			dataSzm: "FYN",
			dataTags: "FUYUN"
		}]
	}, {
		groupname: "G",
		citylist: [{
			dataValue: "果洛",
			dataCity: "果洛",
			dataSpac: "GL",
			dataSzm: "GMQ",
			dataTags: "GUOLUO"
		}, {
			dataValue: "格尔木",
			dataCity: "格尔木",
			dataSpac: "GEM",
			dataSzm: "GOQ",
			dataTags: "GEERMU"
		}, {
			dataValue: "广元",
			dataCity: "广元",
			dataSpac: "GY",
			dataSzm: "GYS",
			dataTags: "GUANGYUAN"
		}, {
			dataValue: "固原",
			dataCity: "固原",
			dataSpac: "GY",
			dataSzm: "GYU",
			dataTags: "GUYUAN"
		}, {
			dataValue: "甘南",
			dataCity: "甘南",
			dataSpac: "GN",
			dataSzm: "JXH",
			dataTags: "GANNAN"
		}, {
			dataValue: "赣州",
			dataCity: "赣州",
			dataSpac: "GZ",
			dataSzm: "KOW",
			dataTags: "GANZHOU"
		}, {
			dataValue: "贵阳",
			dataCity: "贵阳",
			dataSpac: "GY",
			dataSzm: "KWE",
			dataTags: "GUIYANG"
		}, {
			dataValue: "桂林",
			dataCity: "桂林",
			dataSpac: "GL",
			dataSzm: "KWL",
			dataTags: "GUILIN"
		}]
	}, {
		groupname: "H",
		citylist: [{
			dataValue: "海口",
			dataCity: "海口",
			dataSpac: "HK",
			dataSzm: "HAK",
			dataTags: "HAIKOU"
		}, {
			dataValue: "河池",
			dataCity: "河池",
			dataSpac: "HC",
			dataSzm: "HCJ",
			dataTags: "HECHI"
		}, {
			dataValue: "邯郸",
			dataCity: "邯郸",
			dataSpac: "HD",
			dataSzm: "HDG",
			dataTags: "HANDAN"
		}, {
			dataValue: "黑河",
			dataCity: "黑河",
			dataSpac: "HH",
			dataSzm: "HEK",
			dataTags: "HEIHE"
		}, {
			dataValue: "呼和浩特",
			dataCity: "呼和浩特",
			dataSpac: "HHHT",
			dataSzm: "HET",
			dataTags: "HUHEHAOTE"
		}, {
			dataValue: "合肥",
			dataCity: "合肥",
			dataSpac: "HF",
			dataSzm: "HFE",
			dataTags: "HEFEI"
		}, {
			dataValue: "杭州",
			dataCity: "杭州",
			dataSpac: "HZ",
			dataSzm: "HGH",
			dataTags: "HANGZHOU"
		}, {
			dataValue: "淮安",
			dataCity: "淮安",
			dataSpac: "HA",
			dataSzm: "HIA",
			dataTags: "HUAIAN"
		}, {
			dataValue: "怀化",
			dataCity: "怀化",
			dataSpac: "HH",
			dataSzm: "HJJ",
			dataTags: "HUAIHUA"
		}, {
			dataValue: "呼伦贝尔",
			dataCity: "呼伦贝尔",
			dataSpac: "HLBE",
			dataSzm: "HLD",
			dataTags: "HULUNBEIER"
		}, {
			dataValue: "哈密",
			dataCity: "哈密",
			dataSpac: "HM",
			dataSzm: "HMI",
			dataTags: "HAMI"
		}, {
			dataValue: "衡阳",
			dataCity: "衡阳",
			dataSpac: "HY",
			dataSzm: "HNY",
			dataTags: "HENGYANG"
		}, {
			dataValue: "哈尔滨",
			dataCity: "哈尔滨",
			dataSpac: "HEB",
			dataSzm: "HRB",
			dataTags: "HAERBIN"
		}, {
			dataValue: "和田",
			dataCity: "和田",
			dataSpac: "HT",
			dataSzm: "HTN",
			dataTags: "HETIAN"
		}, {
			dataValue: "惠州",
			dataCity: "惠州",
			dataSpac: "HZ",
			dataSzm: "HUZ",
			dataTags: "HUIZHOU"
		}, {
			dataValue: "汉中",
			dataCity: "汉中",
			dataSpac: "HZ",
			dataSzm: "HZG",
			dataTags: "HANZHONG"
		}, {
			dataValue: "黄山",
			dataCity: "黄山",
			dataSpac: "HS",
			dataSzm: "TXN",
			dataTags: "HUANGSHAN"
		}]
	}, {
		groupname: "J",
		citylist: [{
			dataValue: "景德镇",
			dataCity: "景德镇",
			dataSpac: "JDZ",
			dataSzm: "JDZ",
			dataTags: "JINGDEZHEN"
		}, {
			dataValue: "加格达奇",
			dataCity: "加格达奇",
			dataSpac: "JGDQ",
			dataSzm: "JGD",
			dataTags: "JIAGEDAQI"
		}, {
			dataValue: "嘉峪关",
			dataCity: "嘉峪关",
			dataSpac: "JYG",
			dataSzm: "JGN",
			dataTags: "JIAYUGUAN"
		}, {
			dataValue: "井冈山",
			dataCity: "井冈山",
			dataSpac: "JGS",
			dataSzm: "JGS",
			dataTags: "JINGANGSHAN"
		}, {
			dataValue: "金昌",
			dataCity: "金昌",
			dataSpac: "JC",
			dataSzm: "JIC",
			dataTags: "JINCHANG"
		}, {
			dataValue: "晋江",
			dataCity: "晋江",
			dataSpac: "JQ",
			dataSzm: "JJN",
			dataTags: "JINJIANG"
		}, {
			dataValue: "佳木斯",
			dataCity: "佳木斯",
			dataSpac: "JMS",
			dataSzm: "JMU",
			dataTags: "JIAMUSI"
		}, {
			dataValue: "济宁",
			dataCity: "济宁",
			dataSpac: "JN",
			dataSzm: "JNG",
			dataTags: "JINING"
		}, {
			dataValue: "锦州",
			dataCity: "锦州",
			dataSpac: "JZ",
			dataSzm: "JNZ",
			dataTags: "JINZHOU"
		}, {
			dataValue: "九华山",
			dataCity: "九华山",
			dataSpac: "JHS",
			dataSzm: "JUH",
			dataTags: "JIUHUASHAN"
		}, {
			dataValue: "鸡西",
			dataCity: "鸡西",
			dataSpac: "JX",
			dataSzm: "JXA",
			dataTags: "JIXI"
		}, {
			dataValue: "九寨沟",
			dataCity: "九寨沟",
			dataSpac: "JZG",
			dataSzm: "JZH",
			dataTags: "JIUZHANGOU"
		}, {
			dataValue: "揭阳",
			dataCity: "揭阳",
			dataSpac: "JY",
			dataSzm: "SWA",
			dataTags: "JIEYANG"
		}, {
			dataValue: "济南",
			dataCity: "济南",
			dataSpac: "JN",
			dataSzm: "TNA",
			dataTags: "JINAN"
		}]
	}, {
		groupname: "K",
		citylist: [{
			dataValue: "库车",
			dataCity: "库车",
			dataSpac: "KC",
			dataSzm: "KCA",
			dataTags: "KUCHE"
		}, {
			dataValue: "康定",
			dataCity: "康定",
			dataSpac: "KD",
			dataSzm: "KGT",
			dataTags: "KANGDING"
		}, {
			dataValue: "喀什",
			dataCity: "喀什",
			dataSpac: "KS",
			dataSzm: "KHG",
			dataTags: "KASHI"
		}, {
			dataValue: "凯里",
			dataCity: "凯里",
			dataSpac: "KL",
			dataSzm: "KJH",
			dataTags: "KAILI"
		}, {
			dataValue: "喀纳斯",
			dataCity: "喀纳斯",
			dataSpac: "KNS",
			dataSzm: "KJI",
			dataTags: "KANASI"
		}, {
			dataValue: "昆明",
			dataCity: "昆明",
			dataSpac: "KM",
			dataSzm: "KMG",
			dataTags: "KUNMING"
		}, {
			dataValue: "库尔勒",
			dataCity: "库尔勒",
			dataSpac: "KEL",
			dataSzm: "KRL",
			dataTags: "KUERLE"
		}, {
			dataValue: "克拉玛依",
			dataCity: "克拉玛依",
			dataSpac: "KLMY",
			dataSzm: "KRY",
			dataTags: "KELAMAYI"
		}]
	}, {
		groupname: "L",
		citylist: [{
			dataValue: "黎平",
			dataCity: "黎平",
			dataSpac: "LP",
			dataSzm: "HZH",
			dataTags: "LIPING"
		}, {
			dataValue: "龙岩",
			dataCity: "龙岩",
			dataSpac: "LC",
			dataSzm: "LCX",
			dataTags: "LONGYAN"
		}, {
			dataValue: "临汾",
			dataCity: "临汾",
			dataSpac: "LF",
			dataSzm: "LFQ",
			dataTags: "LINFEN"
		}, {
			dataValue: "兰州",
			dataCity: "兰州",
			dataSpac: "LZ",
			dataSzm: "LHW",
			dataTags: "LANZHOU"
		}, {
			dataValue: "丽江",
			dataCity: "丽江",
			dataSpac: "LJ",
			dataSzm: "LJG",
			dataTags: "LIJIANG"
		}, {
			dataValue: "荔波",
			dataCity: "荔波",
			dataSpac: "LB",
			dataSzm: "LLB",
			dataTags: "LIBO"
		}, {
			dataValue: "吕梁",
			dataCity: "吕梁",
			dataSpac: "LL",
			dataSzm: "LLV",
			dataTags: "LVLIANG"
		}, {
			dataValue: "临沧",
			dataCity: "临沧",
			dataSpac: "LC",
			dataSzm: "LNJ",
			dataTags: "LINCHANG"
		}, {
			dataValue: "六盘水",
			dataCity: "六盘水",
			dataSpac: "LPS",
			dataSzm: "LPF",
			dataTags: "LIUPANSHUI"
		}, {
			dataValue: "拉萨",
			dataCity: "拉萨",
			dataSpac: "LS",
			dataSzm: "LXA",
			dataTags: "LASA"
		}, {
			dataValue: "洛阳",
			dataCity: "洛阳",
			dataSpac: "LY",
			dataSzm: "LYA",
			dataTags: "LUOYANG"
		}, {
			dataValue: "连云港",
			dataCity: "连云港",
			dataSpac: "LYG",
			dataSzm: "LYG",
			dataTags: "LIANYUNGANG"
		}, {
			dataValue: "临沂",
			dataCity: "临沂",
			dataSpac: "LY",
			dataSzm: "LYI",
			dataTags: "LINYI"
		}, {
			dataValue: "柳州",
			dataCity: "柳州",
			dataSpac: "LZ",
			dataSzm: "LZH",
			dataTags: "LIUZHOU"
		}, {
			dataValue: "泸州",
			dataCity: "泸州",
			dataSpac: "LZ",
			dataSzm: "LZO",
			dataTags: "LUZHOU"
		}, {
			dataValue: "林芝",
			dataCity: "林芝",
			dataSpac: "LZ",
			dataSzm: "LZY",
			dataTags: "LINZHI"
		}]
	}, {
		groupname: "M",
		citylist: [{
			dataValue: "茫崖",
			dataCity: "茫崖",
			dataSpac: "MY",
			dataSzm: "HTT",
			dataTags: "MANGYA"
		}, {
			dataValue: "芒市",
			dataCity: "芒市",
			dataSpac: "MS",
			dataSzm: "LUM",
			dataTags: "MANG"
		}, {
			dataValue: "牡丹江",
			dataCity: "牡丹江",
			dataSpac: "MDJ",
			dataSzm: "MDG",
			dataTags: "MUDANJIANG"
		}, {
			dataValue: "绵阳",
			dataCity: "绵阳",
			dataSpac: "MY",
			dataSzm: "MIG",
			dataTags: "MIANYANG"
		}, {
			dataValue: "梅县",
			dataCity: "梅县",
			dataSpac: "MX",
			dataSzm: "MXZ",
			dataTags: "MEIXIAN"
		}, {
			dataValue: "满洲里",
			dataCity: "满洲里",
			dataSpac: "MZL",
			dataSzm: "NZH",
			dataTags: "MANZHOULI"
		}, {
			dataValue: "漠河",
			dataCity: "漠河",
			dataSpac: "MH",
			dataSzm: "OHE",
			dataTags: "MOHE"
		}]
	}, {
		groupname: "N",
		citylist: [{
			dataValue: "南昌",
			dataCity: "南昌",
			dataSpac: "NC",
			dataSzm: "KHN",
			dataTags: "NANCHANG"
		}, {
			dataValue: "南充",
			dataCity: "南充",
			dataSpac: "NC",
			dataSzm: "NAO",
			dataTags: "NANCHONG"
		}, {
			dataValue: "宁波",
			dataCity: "宁波",
			dataSpac: "NB",
			dataSzm: "NGB",
			dataTags: "NINGBO"
		}, {
			dataValue: "南京",
			dataCity: "南京",
			dataSpac: "NJ",
			dataSzm: "NKG",
			dataTags: "NANJING"
		}, {
			dataValue: "宁蒗",
			dataCity: "宁蒗",
			dataSpac: "NL",
			dataSzm: "NLH",
			dataTags: "NINGLANG"
		}, {
			dataValue: "南宁",
			dataCity: "南宁",
			dataSpac: "NN",
			dataSzm: "NNG",
			dataTags: "NANNING"
		}, {
			dataValue: "南阳",
			dataCity: "南阳",
			dataSpac: "NY",
			dataSzm: "NNY",
			dataTags: "NANYANG"
		}, {
			dataValue: "南通",
			dataCity: "南通",
			dataSpac: "NT",
			dataSzm: "NTG",
			dataTags: "NANTONG"
		}]
	}, {
		groupname: "P",
		citylist: [{
			dataValue: "攀枝花",
			dataCity: "攀枝花",
			dataSpac: "PZH",
			dataSzm: "PZI",
			dataTags: "PANZHIHUA"
		}, {
			dataValue: "普洱",
			dataCity: "普洱",
			dataSpac: "PE",
			dataSzm: "SYM",
			dataTags: "PUER"
		}]
	}, {
		groupname: "Q",
		citylist: [{
			dataValue: "琼海",
			dataCity: "琼海",
			dataSpac: "QH",
			dataSzm: "BAR",
			dataTags: "QIONGHAI"
		}, {
			dataValue: "秦皇岛",
			dataCity: "秦皇岛",
			dataSpac: "QHD",
			dataSzm: "BPE",
			dataTags: "QINHUANGDAO"
		}, {
			dataValue: "且末",
			dataCity: "且末",
			dataSpac: "QM",
			dataSzm: "IQM",
			dataTags: "QIEMO"
		}, {
			dataValue: "庆阳",
			dataCity: "庆阳",
			dataSpac: "QY",
			dataSzm: "IQN",
			dataTags: "QINGYANG"
		}, {
			dataValue: "黔江",
			dataCity: "黔江",
			dataSpac: "QJ",
			dataSzm: "JIQ",
			dataTags: "QIANJIANG"
		}, {
			dataValue: "衢州",
			dataCity: "衢州",
			dataSpac: "QZ",
			dataSzm: "JUZ",
			dataTags: "QUZHOU"
		}, {
			dataValue: "齐齐哈尔",
			dataCity: "齐齐哈尔",
			dataSpac: "QQHE",
			dataSzm: "NDG",
			dataTags: "QIQIHAER"
		}, {
			dataValue: "青岛",
			dataCity: "青岛",
			dataSpac: "QD",
			dataSzm: "TAO",
			dataTags: "QINGDAO"
		}]
	}, {
		groupname: "R",
		citylist: [{
			dataValue: "日照",
			dataCity: "日照",
			dataSpac: "RZ",
			dataSzm: "RIZ",
			dataTags: "RIZHAO"
		}, {
			dataValue: "日喀则",
			dataCity: "日喀则",
			dataSpac: "RKZ",
			dataSzm: "RKZ",
			dataTags: "RIKEZE"
		}]
	}, {
		groupname: "S",
		citylist: [{
			dataValue: "神农架",
			dataCity: "神农架",
			dataSpac: "SNJ",
			dataSzm: "HPG",
			dataTags: "SHENNONGJIA"
		}, {
			dataValue: "韶关",
			dataCity: "韶关",
			dataSpac: "SG",
			dataSzm: "HSC",
			dataTags: "SHAOGUAN"
		}, {
			dataValue: "上海",
			dataCity: "上海",
			dataSpac: "SH",
			dataSzm: "SHA",
			dataTags: "SHANGHAI"
		}, {
			dataValue: "沈阳",
			dataCity: "沈阳",
			dataSpac: "SY",
			dataSzm: "SHE",
			dataTags: "SHENYANG"
		}, {
			dataValue: "石河子",
			dataCity: "石河子",
			dataSpac: "SHZ",
			dataSzm: "SHF",
			dataTags: "SHIHEZI"
		}, {
			dataValue: "石家庄",
			dataCity: "石家庄",
			dataSpac: "SJZ",
			dataSzm: "SJW",
			dataTags: "SHIJIAZHUANG"
		}, {
			dataValue: "三明",
			dataCity: "三明",
			dataSpac: "SM",
			dataSzm: "SQJ",
			dataTags: "SANMING"
		}, {
			dataValue: "遂宁",
			dataCity: "遂宁",
			dataSpac: "SN",
			dataSzm: "SUN",
			dataTags: "SUINING"
		}, {
			dataValue: "三亚",
			dataCity: "三亚",
			dataSpac: "SY",
			dataSzm: "SYX",
			dataTags: "SANYA"
		}, {
			dataValue: "深圳",
			dataCity: "深圳",
			dataSpac: "SZ",
			dataSzm: "SZX",
			dataTags: "SHENZHEN"
		}, {
			dataValue: "十堰",
			dataCity: "十堰",
			dataSpac: "SY",
			dataSzm: "WDS",
			dataTags: "SHIYAN"
		}, {
			dataValue: "三沙",
			dataCity: "三沙",
			dataSpac: "SY",
			dataSzm: "YXG",
			dataTags: "SHANSHA"
		}]
	}, {
		groupname: "T",
		citylist: [{
			dataValue: "台州",
			dataCity: "台州",
			dataSpac: "TZ",
			dataSzm: "HYN",
			dataTags: "TAIZHOU"
		}, {
			dataValue: "塔城",
			dataCity: "塔城",
			dataSpac: "TC",
			dataSzm: "TCG",
			dataTags: "TACHENG"
		}, {
			dataValue: "腾冲",
			dataCity: "腾冲",
			dataSpac: "TC",
			dataSzm: "TCZ",
			dataTags: "TENGCHONG"
		}, {
			dataValue: "铜仁",
			dataCity: "铜仁",
			dataSpac: "TR",
			dataSzm: "TEN",
			dataTags: "TONGREN"
		}, {
			dataValue: "通辽",
			dataCity: "通辽",
			dataSpac: "TL",
			dataSzm: "TGO",
			dataTags: "TONGLIAO"
		}, {
			dataValue: "天水",
			dataCity: "天水",
			dataSpac: "TS",
			dataSzm: "THQ",
			dataTags: "TIANSHUI"
		}, {
			dataValue: "吐鲁番",
			dataCity: "吐鲁番",
			dataSpac: "TLF",
			dataSzm: "TLQ",
			dataTags: "TULUFAN"
		}, {
			dataValue: "通化",
			dataCity: "通化",
			dataSpac: "TH",
			dataSzm: "TNH",
			dataTags: "TONGHUA"
		}, {
			dataValue: "天津",
			dataCity: "天津",
			dataSpac: "TJ",
			dataSzm: "TSN",
			dataTags: "TIANJIN"
		}, {
			dataValue: "唐山",
			dataCity: "唐山",
			dataSpac: "TS",
			dataSzm: "TVS",
			dataTags: "TANGSHAN"
		}, {
			dataValue: "太原",
			dataCity: "太原",
			dataSpac: "TY",
			dataSzm: "TYN",
			dataTags: "TAIYUAN"
		}]
	}, {
		groupname: "W",
		citylist: [{
			dataValue: "乌兰浩特",
			dataCity: "乌兰浩特",
			dataSpac: "WLHT",
			dataSzm: "HLH",
			dataTags: "WULANHAOTE"
		}, {
			dataValue: "乌兰察布",
			dataCity: "乌兰察布",
			dataSpac: "WLCB",
			dataSzm: "UCB",
			dataTags: "WULANCHABU"
		}, {
			dataValue: "乌鲁木齐",
			dataCity: "乌鲁木齐",
			dataSpac: "WLMQ",
			dataSzm: "URC",
			dataTags: "WULUMUQI"
		}, {
			dataValue: "潍坊",
			dataCity: "潍坊",
			dataSpac: "WF",
			dataSzm: "WEF",
			dataTags: "WEIFANG"
		}, {
			dataValue: "威海",
			dataCity: "威海",
			dataSpac: "WH",
			dataSzm: "WEH",
			dataTags: "WEIHAI"
		}, {
			dataValue: "文山",
			dataCity: "文山",
			dataSpac: "WS",
			dataSzm: "WNH",
			dataTags: "WENSHAN"
		}, {
			dataValue: "温州",
			dataCity: "温州",
			dataSpac: "WZ",
			dataSzm: "WNZ",
			dataTags: "WENZHOU"
		}, {
			dataValue: "乌海",
			dataCity: "乌海",
			dataSpac: "WH",
			dataSzm: "WUA",
			dataTags: "WUHAI"
		}, {
			dataValue: "武汉",
			dataCity: "武汉",
			dataSpac: "WH",
			dataSzm: "WUH",
			dataTags: "WUHAN"
		}, {
			dataValue: "武夷山",
			dataCity: "武夷山",
			dataSpac: "WYS",
			dataSzm: "WUS",
			dataTags: "WUYISHAN"
		}, {
			dataValue: "无锡",
			dataCity: "无锡",
			dataSpac: "WX",
			dataSzm: "WUX",
			dataTags: "WUXI"
		}, {
			dataValue: "梧州",
			dataCity: "梧州",
			dataSpac: "WZ",
			dataSzm: "WUZ",
			dataTags: "WUZHOU"
		}, {
			dataValue: "万州",
			dataCity: "万州",
			dataSpac: "WZ",
			dataSzm: "WXN",
			dataTags: "WANZHOU"
		}]
	}, {
		groupname: "X",
		citylist: [{
			dataValue: "兴义",
			dataCity: "兴义",
			dataSpac: "XY",
			dataSzm: "ACX",
			dataTags: "XINGYI"
		}, {
			dataValue: "西双版纳",
			dataCity: "西双版纳",
			dataSpac: "XSBN",
			dataSzm: "JHG",
			dataTags: "XISHUANGBANNA"
		}, {
			dataValue: "新源",
			dataCity: "新源",
			dataSpac: "XY",
			dataSzm: "NLT",
			dataTags: "XINYUAN"
		}, {
			dataValue: "忻州",
			dataCity: "忻州",
			dataSpac: "XZ",
			dataSzm: "WUT",
			dataTags: "XINZHOU"
		}, {
			dataValue: "襄阳",
			dataCity: "襄阳",
			dataSpac: "XY",
			dataSzm: "XFN",
			dataTags: "XIANGYANG"
		}, {
			dataValue: "西昌",
			dataCity: "西昌",
			dataSpac: "XC",
			dataSzm: "XIC",
			dataTags: "XICHANG"
		}, {
			dataValue: "锡林浩特",
			dataCity: "锡林浩特",
			dataSpac: "XLHT",
			dataSzm: "XIL",
			dataTags: "XILINHAOTE"
		}, {
			dataValue: "西安",
			dataCity: "西安",
			dataSpac: "XA",
			dataSzm: "XIY",
			dataTags: "XIAN"
		}, {
			dataValue: "厦门",
			dataCity: "厦门",
			dataSpac: "XM",
			dataSzm: "XMN",
			dataTags: "XIAMEN"
		}, {
			dataValue: "西宁",
			dataCity: "西宁",
			dataSpac: "XN",
			dataSzm: "XNN",
			dataTags: "XINING"
		}, {
			dataValue: "邢台",
			dataCity: "邢台",
			dataSpac: "XT",
			dataSzm: "XNT",
			dataTags: "XINGTAI"
		}, {
			dataValue: "徐州",
			dataCity: "徐州",
			dataSpac: "XZ",
			dataSzm: "XUZ",
			dataTags: "XUZHOU"
		}]
	}, {
		groupname: "Y",
		citylist: [{
			dataValue: "延安",
			dataCity: "延安",
			dataSpac: "YA",
			dataSzm: "ENY",
			dataTags: "YANAN"
		}, {
			dataValue: "银川",
			dataCity: "银川",
			dataSpac: "YC",
			dataSzm: "INC",
			dataTags: "YINCHUAN"
		}, {
			dataValue: "伊春",
			dataCity: "伊春",
			dataSpac: "YC",
			dataSzm: "LDS",
			dataTags: "YICHUN"
		}, {
			dataValue: "永州",
			dataCity: "永州",
			dataSpac: "YZ",
			dataSzm: "LLF",
			dataTags: "YONGLING"
		}, {
			dataValue: "榆林",
			dataCity: "榆林",
			dataSpac: "YL",
			dataSzm: "UYN",
			dataTags: "YULIN"
		}, {
			dataValue: "宜宾",
			dataCity: "宜宾",
			dataSpac: "YB",
			dataSzm: "YBP",
			dataTags: "YIBIN"
		}, {
			dataValue: "运城",
			dataCity: "运城",
			dataSpac: "YC",
			dataSzm: "YCU",
			dataTags: "YUNCHENG"
		}, {
			dataValue: "宜春",
			dataCity: "宜春",
			dataSpac: "YC",
			dataSzm: "YIC",
			dataTags: "YICHUN"
		}, {
			dataValue: "宜昌",
			dataCity: "宜昌",
			dataSpac: "YC",
			dataSzm: "YIH",
			dataTags: "YICHUN"
		}, {
			dataValue: "伊宁",
			dataCity: "伊宁",
			dataSpac: "YN",
			dataSzm: "YIN",
			dataTags: "YINING"
		}, {
			dataValue: "义乌",
			dataCity: "义乌",
			dataSpac: "YW",
			dataSzm: "YIW",
			dataTags: "YIWU"
		}, {
			dataValue: "营口",
			dataCity: "营口",
			dataSpac: "YK",
			dataSzm: "YKH",
			dataTags: "YINGKOU"
		}, {
			dataValue: "延吉",
			dataCity: "延吉",
			dataSpac: "YJ",
			dataSzm: "YNJ",
			dataTags: "YANJI"
		}, {
			dataValue: "烟台",
			dataCity: "烟台",
			dataSpac: "YT",
			dataSzm: "YNT",
			dataTags: "YANTAI"
		}, {
			dataValue: "盐城",
			dataCity: "盐城",
			dataSpac: "YC",
			dataSzm: "YNZ",
			dataTags: "YANCHENG"
		}, {
			dataValue: "扬州",
			dataCity: "扬州",
			dataSpac: "YZ",
			dataSzm: "YTY",
			dataTags: "YANGZHOU"
		}, {
			dataValue: "玉树",
			dataCity: "玉树",
			dataSpac: "YS",
			dataSzm: "YUS",
			dataTags: "YUSHU"
		}]
	}, {
		groupname: "Z",
		citylist: [{
			dataValue: "郑州",
			dataCity: "郑州",
			dataSpac: "ZZ",
			dataSzm: "CGO",
			dataTags: "ZHENGZHOU"
		}, {
			dataValue: "张家界",
			dataCity: "张家界",
			dataSpac: "ZJJ",
			dataSzm: "DYG",
			dataTags: "ZHANGJIAJIE"
		}, {
			dataValue: "舟山",
			dataCity: "舟山",
			dataSpac: "ZS",
			dataSzm: "HSN",
			dataTags: "ZHOUSHAN"
		}, {
			dataValue: "扎兰屯",
			dataCity: "扎兰屯",
			dataSpac: "ZLT",
			dataSzm: "NZL",
			dataTags: "ZHALANTUN"
		}, {
			dataValue: "张掖",
			dataCity: "张掖",
			dataSpac: "ZY",
			dataSzm: "YZY",
			dataTags: "ZHANGYE"
		}, {
			dataValue: "昭通",
			dataCity: "昭通",
			dataSpac: "ZT",
			dataSzm: "ZAT",
			dataTags: "ZHAOTONG"
		}, {
			dataValue: "湛江",
			dataCity: "湛江",
			dataSpac: "ZJ",
			dataSzm: "ZHA",
			dataTags: "ZHANJIANG"
		}, {
			dataValue: "中卫",
			dataCity: "中卫",
			dataSpac: "ZW",
			dataSzm: "ZHY",
			dataTags: "ZHONGWEI"
		}, {
			dataValue: "张家口",
			dataCity: "张家口",
			dataSpac: "ZJK",
			dataSzm: "ZQZ",
			dataTags: "ZHANGJIAKOU"
		}, {
			dataValue: "珠海",
			dataCity: "珠海",
			dataSpac: "ZH",
			dataSzm: "ZUH",
			dataTags: "ZHUHAI"
		}, {
			dataValue: "遵义",
			dataCity: "遵义",
			dataSpac: "ZY",
			dataSzm: "ZYI",
			dataTags: "ZUNYI"
		}]
	}],
	hotList: [{
		dataValue: "北京",
		dataCity: "北京",
		dataSpac: "BJ",
		dataSzm: "PEK",
		dataTags: "BEIJING",
		dataLat: 40.08,
		dataLon: 116.5844444
	}, {
		dataValue: "上海",
		dataCity: "上海",
		dataSpac: "SH",
		dataSzm: "SHA",
		dataTags: "SHANGHAI",
		dataLat: 31.19805556,
		dataLon: 121.3363889
	}, {
		dataValue: "深圳",
		dataCity: "深圳",
		dataSpac: "SZ",
		dataSzm: "SZX",
		dataTags: "SHENZHEN",
		dataLat: 22.62611111,
		dataLon: 113.8125
	}, {
		dataValue: "广州",
		dataCity: "广州",
		dataSpac: "GZ",
		dataSzm: "CAN",
		dataTags: "GUANGZHOU",
		dataLat: 23.3925,
		dataLon: 113.2988889
	}, {
		dataValue: "郑州",
		dataCity: "郑州",
		dataSpac: "ZZ",
		dataSzm: "CGO",
		dataTags: "ZHENGZHOU",
		dataLat: 34.51972222,
		dataLon: 113.8408333
	}, {
		dataValue: "长春",
		dataCity: "长春",
		dataSpac: "CC",
		dataSzm: "CGQ",
		dataTags: "CHANGCHUN",
		dataLat: 43.99611111,
		dataLon: 125.6852778
	}, {
		dataValue: "重庆",
		dataCity: "重庆",
		dataSpac: "CQ",
		dataSzm: "CKG",
		dataTags: "CHONGQING",
		dataLat: 29.71916667,
		dataLon: 106.6416667
	}, {
		dataValue: "长沙",
		dataCity: "长沙",
		dataSpac: "CS",
		dataSzm: "CSX",
		dataTags: "CHANGSHA",
		dataLat: 28.19666667,
		dataLon: 113.2208333
	}, {
		dataValue: "成都",
		dataCity: "成都",
		dataSpac: "CD",
		dataSzm: "CTU",
		dataTags: "CHENGDU",
		dataLat: 30.57833333,
		dataLon: 103.9469444
	}, {
		dataValue: "海口",
		dataCity: "海口",
		dataSpac: "HK",
		dataSzm: "HAK",
		dataTags: "HAIKOU",
		dataLat: 19.93472222,
		dataLon: 110.4588889
	}, {
		dataValue: "杭州",
		dataCity: "杭州",
		dataSpac: "HZ",
		dataSzm: "HGH",
		dataTags: "HANGZHOU",
		dataLat: 30.22944444,
		dataLon: 120.4344444
	}, {
		dataValue: "哈尔滨",
		dataCity: "哈尔滨",
		dataSpac: "HEB",
		dataSzm: "HRB",
		dataTags: "HAERBIN",
		dataLat: 45.62333333,
		dataLon: 126.2502778
	}, {
		dataValue: "昆明",
		dataCity: "昆明",
		dataSpac: "KM",
		dataSzm: "KMG",
		dataTags: "KUNMING",
		dataLat: 25.09916667,
		dataLon: 102.9266667
	}, {
		dataValue: "贵阳",
		dataCity: "贵阳",
		dataSpac: "GY",
		dataSzm: "KWE",
		dataTags: "GUIYANG",
		dataLat: 26.53861111,
		dataLon: 106.8008333
	}, {
		dataValue: "南京",
		dataCity: "南京",
		dataSpac: "NJ",
		dataSzm: "NKG",
		dataTags: "NANJING",
		dataLat: 31.74222222,
		dataLon: 118.8619444
	}, {
		dataValue: "青岛",
		dataCity: "青岛",
		dataSpac: "QD",
		dataSzm: "TAO",
		dataTags: "QINGDAO",
		dataLat: 36.26694444,
		dataLon: 120.3861111
	}, {
		dataValue: "济南",
		dataCity: "济南",
		dataSpac: "JN",
		dataSzm: "TNA",
		dataTags: "JINAN",
		dataLat: 36.85722222,
		dataLon: 117.2161111
	}, {
		dataValue: "天津",
		dataCity: "天津",
		dataSpac: "TJ",
		dataSzm: "TSN",
		dataTags: "TIANJIN",
		dataLat: 39.12444444,
		dataLon: 117.3461111
	}, {
		dataValue: "乌鲁木齐",
		dataCity: "乌鲁木齐",
		dataSpac: "WLMQ",
		dataSzm: "URC",
		dataTags: "WULUMUQI",
		dataLat: 43.90722222,
		dataLon: 87.47416667
	}, {
		dataValue: "西安",
		dataCity: "西安",
		dataSpac: "XA",
		dataSzm: "XIY",
		dataTags: "XIAN",
		dataLat: 34.44722222,
		dataLon: 108.7516667
	}, {
		dataValue: "厦门",
		dataCity: "厦门",
		dataSpac: "XM",
		dataSzm: "XMN",
		dataTags: "XIAMEN",
		dataLat: 24.53444444,
		dataLon: 118.1319444
	}]
}