dataCityJson = {
	list: [{
		groupname: "A",
		citylist: [{
			dataSpac: "AESS",
			dataValue: "阿尔山",
			dataSzm: "YIE",
			dataTags: "AERSHANSHI"
		}, {
			dataSpac: "ALSZQ",
			dataValue: "阿拉善左旗",
			dataSzm: "AXF",
			dataTags: "ALASHANZUOQI"
		}, {
			dataSpac: "ALSYQ",
			dataValue: "阿拉善右旗",
			dataSzm: "RHT",
			dataTags: "ALASHANYOUQI"
		}, {
			dataSpac: "AS",
			dataValue: "鞍山",
			dataSzm: "IOB",
			dataTags: "AN SHA"
		}, {
			dataSpac: "AQ",
			dataValue: "安庆",
			dataSzm: "AQG",
			dataTags: "ANQING"
		}, {
			dataSpac: "AY",
			dataValue: "安阳",
			dataSzm: "AYG",
			dataTags: "ANYANG"
		}, {
			dataSpac: "AS",
			dataValue: "安顺",
			dataSzm: "AVA",
			dataTags: "ANSHU"
		}, {
			dataSpac: "ALDQ",
			dataValue: "阿里",
			dataSzm: "NGQ",
			dataTags: "ALIDIQU"
		}, {
			dataSpac: "AK",
			dataValue: "安康",
			dataSzm: "AKA",
			dataTags: "ANKANG"
		}, {
			dataSpac: "AKS",
			dataValue: "阿克苏",
			dataSzm: "AKU",
			dataTags: "AKESU"
		}, {
			dataSpac: "ALT",
			dataValue: "阿勒泰",
			dataSzm: "AAT",
			dataTags: "ALETAI"
		}, {
			dataSpac: "AM",
			dataValue: "澳门",
			dataSzm: "MFM",
			dataTags: "AOMEN"
		}, {
			dataSpac: "AKL",
			dataValue: "奥克兰",
			dataSzm: "AKL",
			dataTags: "AOKELAN"
		}, {
			dataSpac: "ALD",
			dataValue: "奥兰多",
			dataSzm: "ORL",
			dataTags: "AOLANDUO"
		}, {
			dataSpac: "ADMD",
			dataValue: "埃德蒙顿",
			dataSzm: "YEA",
			dataTags: "AIDEMENGDUN"
		}, {
			dataSpac: "AMSTD",
			dataValue: "阿姆斯特丹",
			dataSzm: "AMS",
			dataTags: "AMUSITEDAN"
		}, {
			dataSpac: "ADB",
			dataValue: "爱丁堡",
			dataSzm: "EDI",
			dataTags: "AIDINGBAO"
		}, {
			dataSpac: "AKL",
			dataValue: "阿克拉",
			dataSzm: "ACC",
			dataTags: "AKELA"
		}, {
			dataSpac: "AEJE",
			dataValue: "阿尔及尔",
			dataSzm: "ALG",
			dataTags: "AERJIER"
		}, {
			dataSpac: "ABJ",
			dataValue: "阿布贾",
			dataSzm: "ABV",
			dataTags: "ABUJIA"
		}]
	}, {
		groupname: "B",
		citylist: [{
			dataSpac: "BJ",
			dataValue: "北京",
			dataSzm: "BJS",
			dataTags: "BEIJING"
		}, {
			dataSpac: "BT",
			dataValue: "包头",
			dataSzm: "BAV",
			dataTags: "BAOTOU"
		}, {
			dataSpac: "BYNES",
			dataValue: "巴彦淖尔",
			dataSzm: "RLK",
			dataTags: "BAYANNAOERSHI"
		}, {
			dataSpac: "BS",
			dataValue: "白山",
			dataSzm: "NBS",
			dataTags: "BAISHA"
		}, {
			dataSpac: "BH",
			dataValue: "北海",
			dataSzm: "BHY",
			dataTags: "BEIHAI"
		}, {
			dataSpac: "BSS",
			dataValue: "百色",
			dataSzm: "AEB",
			dataTags: "BAISESHI"
		}, {
			dataSpac: "BJS",
			dataValue: "毕节",
			dataSzm: "BFJ",
			dataTags: "BIJIESHI"
		}, {
			dataSpac: "BS",
			dataValue: "保山",
			dataSzm: "BSD",
			dataTags: "BAOSHA"
		}, {
			dataSpac: "BLS",
			dataValue: "博乐",
			dataSzm: "BPL",
			dataTags: "BOLESHI"
		}, {
			dataSpac: "BEJX",
			dataValue: "布尔津",
			dataSzm: "KJI",
			dataTags: "BUERJINXIAN"
		}, {
			dataSpac: "BL",
			dataValue: "巴黎(法国)",
			dataSzm: "PAR",
			dataTags: "BALI"
		}, {
			dataSpac: "BLD",
			dataValue: "巴厘岛",
			dataSzm: "DPS",
			dataTags: "BALIDAO"
		}, {
			dataSpac: "BLSB",
			dataValue: "布里斯班",
			dataSzm: "BNE",
			dataTags: "BULISIBAN"
		}, {
			dataSpac: "BC",
			dataValue: "槟城",
			dataSzm: "PEN",
			dataTags: "BINCHENG"
		}, {
			dataSpac: "BSD",
			dataValue: "波士顿",
			dataSzm: "BOS",
			dataTags: "BOSHIDUN"
		}, {
			dataSpac: "BYNSALS",
			dataValue: "布宜诺斯艾利斯",
			dataSzm: "BUE",
			dataTags: "BUYINUOSIAILISI"
		}, {
			dataSpac: "BL",
			dataValue: "柏林",
			dataSzm: "BER",
			dataTags: "BOLIN"
		}, {
			dataSpac: "BMH",
			dataValue: "伯明翰",
			dataSzm: "BHX",
			dataTags: "BOMINGHAN"
		}, {
			dataSpac: "BSLN",
			dataValue: "巴塞罗那",
			dataSzm: "BCN",
			dataTags: "BASAILUONA"
		}, {
			dataSpac: "BLSE",
			dataValue: "布鲁塞尔",
			dataSzm: "BRU",
			dataTags: "BULUSAIER"
		}, {
			dataSpac: "BLG",
			dataValue: "布拉格",
			dataSzm: "PRG",
			dataTags: "BULAGE"
		}, {
			dataSpac: "BDPS",
			dataValue: "布达佩斯",
			dataSzm: "BUD",
			dataTags: "BUDAPEISI"
		}]
	}, {
		groupname: "C",
		citylist: [{
			dataSpac: "CZ",
			dataValue: "长治",
			dataSzm: "CIH",
			dataTags: "CHANG ZHI"
		}, {
			dataSpac: "CF",
			dataValue: "赤峰",
			dataSzm: "CIF",
			dataTags: "CHIFENG"
		}, {
			dataSpac: "CH",
			dataValue: "长海",
			dataSzm: "CNI",
			dataTags: "CHANGHAI"
		}, {
			dataSpac: "CY",
			dataValue: "朝阳",
			dataSzm: "CHG",
			dataTags: "CHAO YANG"
		}, {
			dataSpac: "CC",
			dataValue: "长春",
			dataSzm: "CGQ",
			dataTags: "CHANGCHUN"
		}, {
			dataSpac: "CZ",
			dataValue: "常州",
			dataSzm: "CZX",
			dataTags: "CHANGZHOU"
		}, {
			dataSpac: "CZS",
			dataValue: "池州",
			dataSzm: "JUH",
			dataTags: "CHIZHOUSHI"
		}, {
			dataSpac: "CS",
			dataValue: "长沙",
			dataSzm: "CSX",
			dataTags: "CHANGSHA"
		}, {
			dataSpac: "CD",
			dataValue: "常德",
			dataSzm: "CGD",
			dataTags: "CHANGDE"
		}, {
			dataSpac: "CQ",
			dataValue: "重庆",
			dataSzm: "CKG",
			dataTags: "CHONGQING"
		}, {
			dataSpac: "CD",
			dataValue: "成都",
			dataSzm: "CTU",
			dataTags: "CHENGDU"
		}, {
			dataSpac: "CDX",
			dataValue: "昌都",
			dataSzm: "BPX",
			dataTags: "CHANGDUXIAN"
		}]
	}, {
		groupname: "D",
		citylist: [{
			dataSpac: "DT",
			dataValue: "大同",
			dataSzm: "DAT",
			dataTags: "DATONG"
		}, {
			dataSpac: "DL",
			dataValue: "大连",
			dataSzm: "DLC",
			dataTags: "DA LIAN"
		}, {
			dataSpac: "DD",
			dataValue: "丹东",
			dataSzm: "DDG",
			dataTags: "DAN DONG"
		}, {
			dataSpac: "DQS",
			dataValue: "大庆",
			dataSzm: "DQA",
			dataTags: "DAQINGSHI"
		}, {
			dataSpac: "DXALDQ",
			dataValue: "大兴安岭",
			dataSzm: "JGD",
			dataTags: "DAXINGANLINGDIQU"
		}, {
			dataSpac: "DY",
			dataValue: "东营",
			dataSzm: "DOY",
			dataTags: "DONGYING"
		}, {
			dataSpac: "DZ",
			dataValue: "达州",
			dataSzm: "DAX",
			dataTags: "DAZHOU"
		}, {
			dataSpac: "DCX",
			dataValue: "稻城",
			dataSzm: "DCY",
			dataTags: "DAOCHENGXIAN"
		}, {
			dataSpac: "DL",
			dataValue: "大理",
			dataSzm: "DLU",
			dataTags: "DALI"
		}, {
			dataSpac: "DH",
			dataValue: "德宏芒市",
			dataSzm: "LUM",
			dataTags: "DEHONG"
		}, {
			dataSpac: "DQ",
			dataValue: "迪庆",
			dataSzm: "DIG",
			dataTags: "DIQING"
		}, {
			dataSpac: "DH",
			dataValue: "敦煌",
			dataSzm: "DNH",
			dataTags: "DUNHUANG"
		}, {
			dataSpac: "DL",
			dataValue: "大连",
			dataSzm: "DLC",
			dataTags: "DALIAN"
		}, {
			dataSpac: "DJ",
			dataValue: "东京",
			dataSzm: "TYO",
			dataTags: "DONGJING"
		}, {
			dataSpac: "DB",
			dataValue: "大阪",
			dataSzm: "OSA",
			dataTags: "DABAN"
		}, {
			dataSpac: "DLD",
			dataValue: "多伦多",
			dataSzm: "YTO",
			dataTags: "DUOLUNDUO"
		}, {
			dataSpac: "DB",
			dataValue: "迪拜",
			dataSzm: "DXB",
			dataTags: "DIBAI"
		}, {
			dataSpac: "DTL",
			dataValue: "底特律",
			dataSzm: "DTT",
			dataTags: "DITELV"
		}, {
			dataSpac: "DLS",
			dataValue: "达拉斯",
			dataSzm: "DFW",
			dataTags: "DALASI"
		}, {
			dataSpac: "DF",
			dataValue: "丹佛",
			dataSzm: "DEN",
			dataTags: "DANFO"
		}, {
			dataSpac: "DBL",
			dataValue: "都柏林",
			dataSzm: "DUB",
			dataTags: "DUBOLIN"
		}, {
			dataSpac: "DSEDF",
			dataValue: "杜塞尔多夫",
			dataSzm: "DUS",
			dataTags: "DUSAIERDUOFU"
		}, {
			dataSpac: "DLSSLM",
			dataValue: "达累斯萨拉姆",
			dataSzm: "DAR",
			dataTags: "DALEISISALAMU"
		}, {
			dataSpac: "DLBL",
			dataValue: "的黎波里",
			dataSzm: "TIP",
			dataTags: "DELIBOLI"
		}]
	}, {
		groupname: "E",
		citylist: [{
			dataSpac: "EEDSS",
			dataValue: "鄂尔多斯",
			dataSzm: "DSN",
			dataTags: "EERDUOSISHI"
		}, {
			dataSpac: "ELHTS",
			dataValue: "二连浩特",
			dataSzm: "ERL",
			dataTags: "ERLIANHAOTESHI"
		}, {
			dataSpac: "EJNQ",
			dataValue: "额济纳旗",
			dataSzm: "EJN",
			dataTags: "EJINAQI"
		}, {
			dataSpac: "ES",
			dataValue: "恩施",
			dataSzm: "ENH",
			dataTags: "ENSHI"
		}]
	}, {
		groupname: "F",
		citylist: [{
			dataSpac: "FY",
			dataValue: "阜阳",
			dataSzm: "FUG",
			dataTags: "FUYANG"
		}, {
			dataSpac: "FZ",
			dataValue: "福州",
			dataSzm: "FOC",
			dataTags: "FUZHOU"
		}, {
			dataSpac: "FS",
			dataValue: "佛山",
			dataSzm: "FUO",
			dataTags: "FOSHA"
		}, {
			dataSpac: "FY",
			dataValue: "富蕴",
			dataSzm: "FYN",
			dataTags: "FUYU"
		}, {
			dataSpac: "FS",
			dataValue: "釜山",
			dataSzm: "PUS",
			dataTags: "FUSHAN"
		}, {
			dataSpac: "FG",
			dataValue: "福冈",
			dataSzm: "FUK",
			dataTags: "FUGANG"
		}, {
			dataSpac: "FLKF",
			dataValue: "法兰克福",
			dataSzm: "FRA",
			dataTags: "FALANKEFU"
		}, {
			dataSpac: "FC",
			dataValue: "费城",
			dataSzm: "PHI",
			dataTags: "FEICHENG"
		}, {
			dataSpac: "FHC",
			dataValue: "凤凰城",
			dataSzm: "PHX",
			dataTags: "FENGHUANGCHENG"
		}, {
			dataSpac: "FT",
			dataValue: "福田",
			dataSzm: "FTT",
			dataTags: "FUTIAN"
		}]
	}, {
		groupname: "G",
		citylist: [{
			dataSpac: "GZ",
			dataValue: "赣州",
			dataSzm: "KOW",
			dataTags: "GANZHOU"
		}, {
			dataSpac: "GZ",
			dataValue: "广州",
			dataSzm: "CAN",
			dataTags: "GUANGZHOU"
		}, {
			dataSpac: "GL",
			dataValue: "桂林",
			dataSzm: "KWL",
			dataTags: "GUILI"
		}, {
			dataSpac: "GH",
			dataValue: "广汉",
			dataSzm: "GHN",
			dataTags: "GUANGHA"
		}, {
			dataSpac: "GY",
			dataValue: "广元",
			dataSzm: "GYS",
			dataTags: "GUANGYUA"
		}, {
			dataSpac: "GY",
			dataValue: "贵阳",
			dataSzm: "KWE",
			dataTags: "GUIYANG"
		}, {
			dataSpac: "GEM",
			dataValue: "格尔木",
			dataSzm: "COQ",
			dataTags: "GEERMU"
		}, {
			dataSpac: "GYS",
			dataValue: "固原",
			dataSzm: "GYU",
			dataTags: "GUYUANSHI"
		}, {
			dataSpac: "GX",
			dataValue: "高雄",
			dataSzm: "KHH",
			dataTags: "GAOXIONG"
		}, {
			dataSpac: "GBHG",
			dataValue: "哥本哈根",
			dataSzm: "CPH",
			dataTags: "GEBENHAGEN"
		}, {
			dataSpac: "GLSG",
			dataValue: "格拉斯哥",
			dataSzm: "GLA",
			dataTags: "GELASIGE"
		}]
	}, {
		groupname: "H",
		citylist: [{
			dataSpac: "HDS",
			dataValue: "邯郸",
			dataSzm: "HDG",
			dataTags: "HANDANSHI"
		}, {
			dataSpac: "HHHT",
			dataValue: "呼和浩特",
			dataSzm: "HET",
			dataTags: "HUHEHAOTE"
		}, {
			dataSpac: "HLE",
			dataValue: "呼伦贝尔",
			dataSzm: "HLD",
			dataTags: "HAILAER"
		}, {
			dataSpac: "HRB",
			dataValue: "哈尔滨",
			dataSzm: "HRB",
			dataTags: "HAERBI"
		}, {
			dataSpac: "HH",
			dataValue: "黑河",
			dataSzm: "HEK",
			dataTags: "HEIHE"
		}, {
			dataSpac: "HAS",
			dataValue: "淮安",
			dataSzm: "HIA",
			dataTags: "HUAIANSHI"
		}, {
			dataSpac: "HZ",
			dataValue: "杭州",
			dataSzm: "HGH",
			dataTags: "HANGZHOU"
		}, {
			dataSpac: "HF",
			dataValue: "合肥",
			dataSzm: "HFE",
			dataTags: "HEFEI"
		}, {
			dataSpac: "HS",
			dataValue: "黄山",
			dataSzm: "TXN",
			dataTags: "HUANGSHA"
		}, {
			dataSpac: "HY",
			dataValue: "衡阳",
			dataSzm: "HNY",
			dataTags: "HENGYANG"
		}, {
			dataSpac: "HH",
			dataValue: "怀化",
			dataSzm: "HJJ",
			dataTags: "HUAIHUA"
		}, {
			dataSpac: "HZ",
			dataValue: "惠州",
			dataSzm: "HUZ",
			dataTags: "HUIZHOU"
		}, {
			dataSpac: "HK",
			dataValue: "海口",
			dataSzm: "HAK",
			dataTags: "HAIKOU"
		}, {
			dataSpac: "HZ",
			dataValue: "汉中",
			dataSzm: "HZG",
			dataTags: "HANZHONG"
		}, {
			dataSpac: "HM",
			dataValue: "哈密",
			dataSzm: "HMT",
			dataTags: "HAMI"
		}, {
			dataSpac: "HT",
			dataValue: "和田",
			dataSzm: "HTN",
			dataTags: "HETIA"
		}, {
			dataSpac: "HL",
			dataValue: "花莲",
			dataSzm: "HUN",
			dataTags: "HUALIAN"
		}, {
			dataSpac: "HEB",
			dataValue: "哈尔滨",
			dataSzm: "HRB",
			dataTags: "HAERBIN"
		}, {
			dataSpac: "HZMS",
			dataValue: "胡志明市",
			dataSzm: "SGN",
			dataTags: "HUZHIMINGSHI"
		}, {
			dataSpac: "HN",
			dataValue: "河内",
			dataSzm: "HAN",
			dataTags: "HENEI"
		}, {
			dataSpac: "HSD",
			dataValue: "华盛顿",
			dataSzm: "WAS",
			dataTags: "HUASHENGDUN"
		}, {
			dataSpac: "HNLL",
			dataValue: "火奴鲁鲁",
			dataSzm: "HNL",
			dataTags: "HUONULULU"
		}, {
			dataSpac: "HEXJ",
			dataValue: "赫尔辛基",
			dataSzm: "HEL",
			dataTags: "HEERXINJI"
		}, {
			dataSpac: "HB",
			dataValue: "汉堡",
			dataSzm: "HAM",
			dataTags: "HANBAO"
		}]
	}, {
		groupname: "J",
		citylist: [{
			dataSpac: "JZ",
			dataValue: "锦州",
			dataSzm: "JNZ",
			dataTags: "JIN ZHOU"
		}, {
			dataSpac: "JXS",
			dataValue: "鸡西",
			dataSzm: "JXA",
			dataTags: "JIXISHI"
		}, {
			dataSpac: "JMS",
			dataValue: "佳木斯",
			dataSzm: "JMU",
			dataTags: "JIAMUSI"
		}, {
			dataSpac: "JJ",
			dataValue: "晋江",
			dataSzm: "JJN",
			dataTags: "JINJIANG"
		}, {
			dataSpac: "JDZ",
			dataValue: "景德镇",
			dataSzm: "JDZ",
			dataTags: "JINGDEZHE"
		}, {
			dataSpac: "JJ",
			dataValue: "九江",
			dataSzm: "JIU",
			dataTags: "JIUJIANG"
		}, {
			dataSpac: "JGS",
			dataValue: "井冈山",
			dataSzm: "JGS",
			dataTags: "JINGGANGSHA"
		}, {
			dataSpac: "J",
			dataValue: "济南",
			dataSzm: "TNA",
			dataTags: "JINA"
		}, {
			dataSpac: "J",
			dataValue: "济宁",
			dataSzm: "JNG",
			dataTags: "JINING"
		}, {
			dataSpac: "JZ",
			dataValue: "荆州",
			dataSzm: "SHS",
			dataTags: "JINGZHOU"
		}, {
			dataSpac: "JYS",
			dataValue: "揭阳",
			dataSzm: "SWA",
			dataTags: "JIEYANGSHI"
		}, {
			dataSpac: "JZG",
			dataValue: "九寨沟",
			dataSzm: "JZH",
			dataTags: "JIUZHAIU"
		}, {
			dataSpac: "JH",
			dataValue: "景洪",
			dataSzm: "JHG",
			dataTags: "JINGHONG"
		}, {
			dataSpac: "JYG",
			dataValue: "嘉峪关",
			dataSzm: "JGN",
			dataTags: "JIAYUGUA"
		}, {
			dataSpac: "JCS",
			dataValue: "金昌",
			dataSzm: "JIC",
			dataTags: "JINCHANGSHI"
		}, {
			dataSpac: "JY",
			dataValue: "嘉义",
			dataSzm: "CYI",
			dataTags: "JIAYI"
		}, {
			dataSpac: "JM",
			dataValue: "金门",
			dataSzm: "KNH",
			dataTags: "JINMEN"
		}, {
			dataSpac: "JN",
			dataValue: "济南",
			dataSzm: "TNA",
			dataTags: "JINAN"
		}, {
			dataSpac: "JLP",
			dataValue: "吉隆坡",
			dataSzm: "KUL",
			dataTags: "JILONGPO"
		}, {
			dataSpac: "JZD",
			dataValue: "济州岛",
			dataSzm: "CJU",
			dataTags: "JIZHOUDAO"
		}, {
			dataSpac: "JJS",
			dataValue: "旧金山",
			dataSzm: "SFO",
			dataTags: "JIUJINSHAN"
		}, {
			dataSpac: "JDMD",
			dataValue: "加德满都",
			dataSzm: "KTM",
			dataTags: "JIADEMANDU"
		}, {
			dataSpac: "JB",
			dataValue: "金边",
			dataSzm: "PNH",
			dataTags: "JINBIAN"
		}, {
			dataSpac: "JF",
			dataValue: "基辅",
			dataSzm: "IEV",
			dataTags: "JIFU"
		}]
	}, {
		groupname: "K",
		citylist: [{
			dataSpac: "KDX",
			dataValue: "康定",
			dataSzm: "KGT",
			dataTags: "KANGDINGXIAN"
		}, {
			dataSpac: "KLS",
			dataValue: "凯里",
			dataSzm: "KJH",
			dataTags: "KAILISHI"
		}, {
			dataSpac: "KM",
			dataValue: "昆明",
			dataSzm: "KMG",
			dataTags: "KUNMING"
		}, {
			dataSpac: "KLMY",
			dataValue: "克拉玛依",
			dataSzm: "KRY",
			dataTags: "KELAMAYI"
		}, {
			dataSpac: "KEL",
			dataValue: "库尔勒",
			dataSzm: "KRL",
			dataTags: "KUERLE"
		}, {
			dataSpac: "KC",
			dataValue: "库车",
			dataSzm: "KCA",
			dataTags: "KUCHE"
		}, {
			dataSpac: "KS",
			dataValue: "喀什",
			dataSzm: "KHG",
			dataTags: "KESHI"
		}, {
			dataSpac: "KEJL",
			dataValue: "卡尔加里",
			dataSzm: "YYC",
			dataTags: "KAERJIALI"
		}, {
			dataSpac: "KL",
			dataValue: "开罗",
			dataSzm: "CAI",
			dataTags: "KAILUO"
		}, {
			dataSpac: "KPD",
			dataValue: "开普敦",
			dataSzm: "CPT",
			dataTags: "KAIPUDUN"
		}, {
			dataSpac: "KTM",
			dataValue: "喀土穆",
			dataSzm: "KRT",
			dataTags: "KATUMU"
		}, {
			dataSpac: "KSBLK",
			dataValue: "卡萨布兰卡",
			dataSzm: "CAS",
			dataTags: "KASABULANKA"
		}]
	}, {
		groupname: "L",
		citylist: [{
			dataSpac: "LLS",
			dataValue: "吕梁",
			dataSzm: "LLV",
			dataTags: "LVLIANGSHI"
		}, {
			dataSpac: "LXX",
			dataValue: "林西",
			dataSzm: "UYN",
			dataTags: "LINXIXIAN"
		}, {
			dataSpac: "LYG",
			dataValue: "连云港",
			dataSzm: "LYG",
			dataTags: "LIANYUNGANG"
		}, {
			dataSpac: "LYS",
			dataValue: "龙岩",
			dataSzm: "LCX",
			dataTags: "LONGYANSHI"
		}, {
			dataSpac: "LY",
			dataValue: "临沂",
			dataSzm: "LYI",
			dataTags: "LINYI"
		}, {
			dataSpac: "LY",
			dataValue: "洛阳",
			dataSzm: "LYA",
			dataTags: "LUOYANG"
		}, {
			dataSpac: "LHKS",
			dataValue: "老河口",
			dataSzm: "LHK",
			dataTags: "LAOHEKOUSHI"
		}, {
			dataSpac: "LZ",
			dataValue: "柳州",
			dataSzm: "LZH",
			dataTags: "LIUZHOU"
		}, {
			dataSpac: "LPX",
			dataValue: "梁平",
			dataSzm: "LIA",
			dataTags: "LIANGPINGXIAN"
		}, {
			dataSpac: "LZ",
			dataValue: "泸州",
			dataSzm: "LZO",
			dataTags: "LUZHOU"
		}, {
			dataSpac: "LP",
			dataValue: "黎平",
			dataSzm: "HZH",
			dataTags: "LIPING"
		}, {
			dataSpac: "LBX",
			dataValue: "荔波",
			dataSzm: "LLB",
			dataTags: "LIBOXIAN"
		}, {
			dataSpac: "LJ",
			dataValue: "丽江",
			dataSzm: "LJG",
			dataTags: "LIJIANG"
		}, {
			dataSpac: "LC",
			dataValue: "临沧",
			dataSzm: "LNJ",
			dataTags: "LINCANG"
		}, {
			dataSpac: "LS",
			dataValue: "拉萨",
			dataSzm: "LXA",
			dataTags: "LASA"
		}, {
			dataSpac: "LZX",
			dataValue: "林芝",
			dataSzm: "MZY",
			dataTags: "LINZHIXIAN"
		}, {
			dataSpac: "LZ",
			dataValue: "兰州",
			dataSzm: "LHW",
			dataTags: "LANZHOU"
		}, {
			dataSpac: "LSJ",
			dataValue: "洛杉矶",
			dataSzm: "LAX",
			dataTags: "LUOSHANJI"
		}, {
			dataSpac: "LD",
			dataValue: "伦敦(英国)",
			dataSzm: "LON",
			dataTags: "LUNDUN"
		}, {
			dataSpac: "LSWJS",
			dataValue: "拉斯维加斯",
			dataSzm: "LAS",
			dataTags: "LASIWEIJIASI"
		}, {
			dataSpac: "LYRNL",
			dataValue: "里约热内卢",
			dataSzm: "RIO",
			dataTags: "LIYUERENEILU"
		}, {
			dataSpac: "LM",
			dataValue: "罗马",
			dataSzm: "ROM",
			dataTags: "LUOMA"
		}, {
			dataSpac: "LGS",
			dataValue: "拉各斯",
			dataSzm: "LOS",
			dataTags: "LAGESI"
		}, {
			dataSpac: "LPS",
			dataValue: "六盘水",
			dataSzm: "LPF",
			dataTags: "LIUPANSHUI"
		}]
	}, {
		groupname: "M",
		citylist: [{
			dataSpac: "MZLS",
			dataValue: "满洲里",
			dataSzm: "NZH",
			dataTags: "MANZHOULISHI"
		}, {
			dataSpac: "MDJ",
			dataValue: "牡丹江",
			dataSzm: "MDG",
			dataTags: "MUDANJIANG"
		}, {
			dataSpac: "MHX",
			dataValue: "漠河",
			dataSzm: "OHE",
			dataTags: "MOHEXIAN"
		}, {
			dataSpac: "MZ",
			dataValue: "梅州",
			dataSzm: "MEI",
			dataTags: "MEIZHOU"
		}, {
			dataSpac: "MY",
			dataValue: "绵阳",
			dataSzm: "MIG",
			dataTags: "MIANYANG"
		}, {
			dataSpac: "MGW",
			dataValue: "名古屋",
			dataSzm: "NGO",
			dataTags: "MINGGUWU"
		}, {
			dataSpac: "MG",
			dataValue: "曼谷",
			dataSzm: "BKK",
			dataTags: "MANGU"
		}, {
			dataSpac: "MEB",
			dataValue: "墨尔本",
			dataSzm: "MEL",
			dataTags: "MOERBEN"
		}, {
			dataSpac: "MNL",
			dataValue: "马尼拉",
			dataSzm: "MNL",
			dataTags: "MANILA"
		}, {
			dataSpac: "ML",
			dataValue: "马累",
			dataSzm: "MLE",
			dataTags: "MALEI"
		}, {
			dataSpac: "MTLE",
			dataValue: "蒙特利尔",
			dataSzm: "YMQ",
			dataTags: "MENGTELIER"
		}, {
			dataSpac: "MNABLS",
			dataValue: "明尼阿波利斯",
			dataSzm: "MSP",
			dataTags: "MINGNIABOLISI"
		}, {
			dataSpac: "MXGC",
			dataValue: "墨西哥城",
			dataSzm: "MEX",
			dataTags: "MOXIGECHENG"
		}, {
			dataSpac: "MAM",
			dataValue: "迈阿密",
			dataSzm: "MIA",
			dataTags: "MAIAMI"
		}, {
			dataSpac: "MSK",
			dataValue: "莫斯科",
			dataSzm: "MOS",
			dataTags: "MOSIKE"
		}, {
			dataSpac: "ML",
			dataValue: "米兰",
			dataSzm: "MIL",
			dataTags: "MILAN"
		}, {
			dataSpac: "MDL",
			dataValue: "马德里",
			dataSzm: "MAD",
			dataTags: "MADELI"
		}, {
			dataSpac: "MNH",
			dataValue: "慕尼黑",
			dataSzm: "MUC",
			dataTags: "MUNIHEI"
		}, {
			dataSpac: "MLQS",
			dataValue: "毛里求斯",
			dataSzm: "MRU",
			dataTags: "MAOLIQIUSI"
		}]
	}, {
		groupname: "N",
		citylist: [{
			dataSpac: "NJ",
			dataValue: "南京",
			dataSzm: "NKG",
			dataTags: "NANJING"
		}, {
			dataSpac: "NT",
			dataValue: "南通",
			dataSzm: "NTG",
			dataTags: "NANTONG"
		}, {
			dataSpac: "NB",
			dataValue: "宁波",
			dataSzm: "NGB",
			dataTags: "NINGBO"
		}, {
			dataSpac: "NC",
			dataValue: "南昌",
			dataSzm: "KHN",
			dataTags: "NANCHANG"
		}, {
			dataSpac: "NY",
			dataValue: "南阳",
			dataSzm: "NNY",
			dataTags: "NANYANG"
		}, {
			dataSpac: "N",
			dataValue: "南宁",
			dataSzm: "NNG",
			dataTags: "NANNING"
		}, {
			dataSpac: "NC",
			dataValue: "南充",
			dataSzm: "NAO",
			dataTags: "NANCHONG"
		}, {
			dataSpac: "NY",
			dataValue: "纽约",
			dataSzm: "NYC",
			dataTags: "NIUYUE"
		}, {
			dataSpac: "NLB",
			dataValue: "内罗毕",
			dataSzm: "NBO",
			dataTags: "NEILUOBI"
		}]
	}, {
		groupname: "P",
		citylist: [{
			dataSpac: "PZH",
			dataValue: "攀枝花",
			dataSzm: "PZI",
			dataTags: "PANZHIHUA"
		}, {
			dataSpac: "PE",
			dataValue: "普洱",
			dataSzm: "SYM",
			dataTags: "PUER"
		}, {
			dataSpac: "PH",
			dataValue: "澎湖",
			dataSzm: "MZG",
			dataTags: "PENGHU"
		}, {
			dataSpac: "PJ",
			dataValue: "普吉",
			dataSzm: "HKT",
			dataTags: "PUJI"
		}, {
			dataSpac: "PZB",
			dataValue: "匹兹堡",
			dataSzm: "PIT",
			dataTags: "PIZIBAO"
		}]
	}, {
		groupname: "Q",
		citylist: [{
			dataSpac: "QHD",
			dataValue: "秦皇岛",
			dataSzm: "SHF",
			dataTags: "QINHUANGDAO"
		}, {
			dataSpac: "QQHE",
			dataValue: "齐齐哈尔",
			dataSzm: "NDG",
			dataTags: "QIQIHAER"
		}, {
			dataSpac: "QZ",
			dataValue: "衢州",
			dataSzm: "JUZ",
			dataTags: "QUZHOU"
		}, {
			dataSpac: "QD",
			dataValue: "青岛",
			dataSzm: "TAO",
			dataTags: "QINGDAO"
		}, {
			dataSpac: "QJS",
			dataValue: "黔江市",
			dataSzm: "JIQ",
			dataTags: "QIANJIANGSHI"
		}, {
			dataSpac: "QY",
			dataValue: "庆阳",
			dataSzm: "IQN",
			dataTags: "QINGYANG"
		}, {
			dataSpac: "QM",
			dataValue: "且末",
			dataSzm: "IQM",
			dataTags: "QIEMO"
		}]
	}, {
		groupname: "R",
		citylist: [{
			dataSpac: "RKZS",
			dataValue: "日喀则",
			dataSzm: "RKZ",
			dataTags: "RIKAZESHI"
		}, {
			dataSpac: "RNW",
			dataValue: "日内瓦",
			dataSzm: "GVA",
			dataTags: "RINEIWA"
		}]
	}, {
		groupname: "S",
		citylist: [{
			dataSpac: "SJZ",
			dataValue: "石家庄",
			dataSzm: "SJW",
			dataTags: "SHIJIAZHUANG"
		}, {
			dataSpac: "SY",
			dataValue: "沈阳",
			dataSzm: "SHE",
			dataTags: "SHEN YANG"
		}, {
			dataSpac: "SH",
			dataValue: "上海",
			dataSzm: "SHA",
			dataTags: "SHANGHAI"
		}, {
			dataSpac: "SZ",
			dataValue: "深圳",
			dataSzm: "SZX",
			dataTags: "SHENZHE"
		}, {
			dataSpac: "SY",
			dataValue: "三亚",
			dataSzm: "SYX",
			dataTags: "SANYA"
		}, {
			dataSpac: "SZ",
			dataValue: "深圳",
			dataSzm: "SZX",
			dataTags: "SHENZHEN"
		}, {
			dataSpac: "SY",
			dataValue: "沈阳",
			dataSzm: "SHE",
			dataTags: "SHENYANG"
		}, {
			dataSpac: "SE",
			dataValue: "首尔",
			dataSzm: "SEL",
			dataTags: "SHOUER"
		}, {
			dataSpac: "SBL",
			dataValue: "圣保罗",
			dataSzm: "SAO",
			dataTags: "SHENGBAOLUO"
		}, {
			dataSpac: "SDGEM",
			dataValue: "斯德哥尔摩",
			dataSzm: "STO",
			dataTags: "SIDEGEERMO"
		}, {
			dataSpac: "SLS",
			dataValue: "苏黎世",
			dataSzm: "ZRH",
			dataTags: "SULISHI"
		}, {
			dataSpac: "SBDB",
			dataValue: "圣彼得堡",
			dataSzm: "LED",
			dataTags: "SHENGBIDEBAO"
		}, {
			dataSpac: "SSE",
			dataValue: "塞舌尔",
			dataSzm: "SEZ",
			dataTags: "SAISHEER"
		}, {
			dataSpac: "SY",
			dataValue: "十堰",
			dataSzm: "WDS",
			dataTags: "SHIYAN"
		}]
	}, {
		groupname: "T",
		citylist: [{
			dataSpac: "TJ",
			dataValue: "天津",
			dataSzm: "TSN",
			dataTags: "TIANJI"
		}, {
			dataSpac: "TSS",
			dataValue: "唐山",
			dataSzm: "TVS",
			dataTags: "TANGSHANSHI"
		}, {
			dataSpac: "TY",
			dataValue: "太原",
			dataSzm: "TYN",
			dataTags: "TAIYUA"
		}, {
			dataSpac: "TL",
			dataValue: "通辽",
			dataSzm: "TGO",
			dataTags: "TONGLIAO"
		}, {
			dataSpac: "TZ",
			dataValue: "台州",
			dataSzm: "HYN",
			dataTags: "TAIZHOU"
		}, {
			dataSpac: "TR",
			dataValue: "铜仁",
			dataSzm: "TEN",
			dataTags: "TONGREN"
		}, {
			dataSpac: "TCX",
			dataValue: "腾冲",
			dataSzm: "TCZ",
			dataTags: "TENGCHONGXIAN"
		}, {
			dataSpac: "TSS",
			dataValue: "天水",
			dataSzm: "THQ",
			dataTags: "TIANSHUISHI"
		}, {
			dataSpac: "TLFS",
			dataValue: "吐鲁番",
			dataSzm: "TLQ",
			dataTags: "TULUFANSHI"
		}, {
			dataSpac: "TC",
			dataValue: "塔城",
			dataSzm: "TCG",
			dataTags: "TACHENG"
		}, {
			dataSpac: "TB",
			dataValue: "台北",
			dataSzm: "TPE",
			dataTags: "TAIBEI"
		}, {
			dataSpac: "TZ",
			dataValue: "台中",
			dataSzm: "RMQ",
			dataTags: "TAIZHONG"
		}, {
			dataSpac: "TD",
			dataValue: "台东",
			dataSzm: "TTT",
			dataTags: "TAIDONG"
		}, {
			dataSpac: "TJ",
			dataValue: "天津",
			dataSzm: "TSN",
			dataTags: "TIANJIN"
		}, {
			dataSpac: "TY",
			dataValue: "太原",
			dataSzm: "TYN",
			dataTags: "TAIYUAN"
		}, {
			dataSpac: "TNS",
			dataValue: "突尼斯",
			dataSzm: "TUN",
			dataTags: "TUNISI"
		}]
	}, {
		groupname: "W",
		citylist: [{
			dataSpac: "WH",
			dataValue: "乌海",
			dataSzm: "WUA",
			dataTags: "WUHAI"
		}, {
			dataSpac: "WLHT",
			dataValue: "乌兰浩特",
			dataSzm: "HLH",
			dataTags: "WULANHAOTE"
		}, {
			dataSpac: "WX",
			dataValue: "无锡",
			dataSzm: "WUX",
			dataTags: "WUXI"
		}, {
			dataSpac: "WZ",
			dataValue: "温州",
			dataSzm: "WNZ",
			dataTags: "WENZHOU"
		}, {
			dataSpac: "WYS",
			dataValue: "武夷山",
			dataSzm: "WUS",
			dataTags: "WUYISHA"
		}, {
			dataSpac: "WF",
			dataValue: "潍坊",
			dataSzm: "WEF",
			dataTags: "WEIFANG"
		}, {
			dataSpac: "WH",
			dataValue: "威海",
			dataSzm: "WEH",
			dataTags: "WEIHAI"
		}, {
			dataSpac: "WH",
			dataValue: "武汉",
			dataSzm: "WUH",
			dataTags: "WUHA"
		}, {
			dataSpac: "WZ",
			dataValue: "梧州",
			dataSzm: "WUZ",
			dataTags: "WUZHOU"
		}, {
			dataSpac: "WZS",
			dataValue: "万州市",
			dataSzm: "WXN",
			dataTags: "WANZHOUSHI"
		}, {
			dataSpac: "WSS",
			dataValue: "文山",
			dataSzm: "WSS",
			dataTags: "WENSHANSHI"
		}, {
			dataSpac: "WLMQ",
			dataValue: "乌鲁木齐",
			dataSzm: "URC",
			dataTags: "WULUMUQI"
		}, {
			dataSpac: "WH",
			dataValue: "武汉",
			dataSzm: "WUH",
			dataTags: "WUHAN"
		}, {
			dataSpac: "WGH",
			dataValue: "温哥华",
			dataSzm: "YVR",
			dataTags: "WENGEHUA"
		}, {
			dataSpac: "WTH",
			dataValue: "渥太华",
			dataSzm: "YOW",
			dataTags: "WOTAIHUA"
		}, {
			dataSpac: "WYN",
			dataValue: "维也纳",
			dataSzm: "VIE",
			dataTags: "WEIYENA"
		}, {
			dataSpac: "WLCB",
			dataValue: "乌兰察布",
			dataSzm: "UCB",
			dataTags: "WULANCHABU"
		}]
	}, {
		groupname: "X",
		citylist: [{
			dataSpac: "XLHT",
			dataValue: "锡林浩特",
			dataSzm: "XIL",
			dataTags: "XINLINHAOTE"
		}, {
			dataSpac: "XC",
			dataValue: "兴城",
			dataSzm: "XEN",
			dataTags: "XING CHENG"
		}, {
			dataSpac: "XZ",
			dataValue: "徐州",
			dataSzm: "XUZ",
			dataTags: "XUZHOU"
		}, {
			dataSpac: "XM",
			dataValue: "厦门",
			dataSzm: "XMN",
			dataTags: "XIAME"
		}, {
			dataSpac: "XY",
			dataValue: "襄阳",
			dataSzm: "XFN",
			dataTags: "XIANGYANG"
		}, {
			dataSpac: "XC",
			dataValue: "西昌",
			dataSzm: "XIC",
			dataTags: "XICHANG"
		}, {
			dataSpac: "XY",
			dataValue: "兴义",
			dataSzm: "ACX",
			dataTags: "XINGYI"
		}, {
			dataSpac: "XA",
			dataValue: "西安",
			dataSzm: "XIY",
			dataTags: "XIA"
		}, {
			dataSpac: "XHX",
			dataValue: "夏河",
			dataSzm: "GXH",
			dataTags: "XIAHEXIAN"
		}, {
			dataSpac: "X",
			dataValue: "西宁",
			dataSzm: "XNN",
			dataTags: "XINING"
		}, {
			dataSpac: "XYX",
			dataValue: "新源",
			dataSzm: "NLT",
			dataTags: "XINYUANXIAN"
		}, {
			dataSpac: "XG",
			dataValue: "香港",
			dataSzm: "HKG",
			dataTags: "XIANGGANG"
		}, {
			dataSpac: "XA",
			dataValue: "西安",
			dataSzm: "SIA",
			dataTags: "XIAN"
		}, {
			dataSpac: "XM",
			dataValue: "厦门",
			dataSzm: "XMN",
			dataTags: "XIAMEN"
		}, {
			dataSpac: "XJP",
			dataValue: "新加坡",
			dataSzm: "SIN",
			dataTags: "XINJIAPO"
		}, {
			dataSpac: "XN",
			dataValue: "悉尼",
			dataSzm: "SYD",
			dataTags: "XINI"
		}, {
			dataSpac: "XWY",
			dataValue: "夏威夷",
			dataSzm: "FUK",
			dataTags: "XIAWEIYI"
		}, {
			dataSpac: "XL",
			dataValue: "暹粒",
			dataSzm: "REP",
			dataTags: "XIANLI"
		}, {
			dataSpac: "XDL",
			dataValue: "新德里",
			dataSzm: "DEL",
			dataTags: "XINDELI"
		}, {
			dataSpac: "XYT",
			dataValue: "西雅图",
			dataSzm: "SEA",
			dataTags: "XIYATU"
		}, {
			dataSpac: "XSD",
			dataValue: "休斯敦",
			dataSzm: "HOU",
			dataTags: "XIUSIDUN"
		}]
	}, {
		groupname: "Y",
		citylist: [{
			dataSpac: "YC",
			dataValue: "运城",
			dataSzm: "YCU",
			dataTags: "YUNCHENG"
		}, {
			dataSpac: "YJ",
			dataValue: "延吉",
			dataSzm: "YNJ",
			dataTags: "YANJI"
		}, {
			dataSpac: "YCS",
			dataValue: "伊春",
			dataSzm: "LDS",
			dataTags: "YICHUNSHI"
		}, {
			dataSpac: "YC",
			dataValue: "盐城",
			dataSzm: "YNZ",
			dataTags: "YANCHENG"
		}, {
			dataSpac: "YZS",
			dataValue: "扬州",
			dataSzm: "YTY",
			dataTags: "YANGZHOUSHI"
		}, {
			dataSpac: "YW",
			dataValue: "义乌",
			dataSzm: "YIW",
			dataTags: "YIWU"
		}, {
			dataSpac: "YT",
			dataValue: "烟台",
			dataSzm: "YNT",
			dataTags: "YANTAI"
		}, {
			dataSpac: "YC",
			dataValue: "宜昌",
			dataSzm: "YIH",
			dataTags: "YICHANG"
		}, {
			dataSpac: "YZ",
			dataValue: "永州",
			dataSzm: "LLF",
			dataTags: "YONGZHOU"
		}, {
			dataSpac: "YB",
			dataValue: "宜宾",
			dataSzm: "YBP",
			dataTags: "YIBI"
		}, {
			dataSpac: "YA",
			dataValue: "延安",
			dataSzm: "ENY",
			dataTags: "YANA"
		}, {
			dataSpac: "YL",
			dataValue: "榆林",
			dataSzm: "UYN",
			dataTags: "YULI"
		}, {
			dataSpac: "YSS",
			dataValue: "玉树",
			dataSzm: "YUS",
			dataTags: "YUSHUSHI"
		}, {
			dataSpac: "YC",
			dataValue: "银川",
			dataSzm: "INC",
			dataTags: "YINCHUA"
		}, {
			dataSpac: "Y",
			dataValue: "伊宁",
			dataSzm: "YIN",
			dataTags: "YINING"
		}, {
			dataSpac: "YJD",
			dataValue: "雅加达",
			dataSzm: "JKT",
			dataTags: "YAJIADA"
		}, {
			dataSpac: "YTLD",
			dataValue: "亚特兰大",
			dataSzm: "ATL",
			dataTags: "YATELANDA"
		}, {
			dataSpac: "YSTBE",
			dataValue: "伊斯坦布尔",
			dataSzm: "IST",
			dataTags: "YISITANBUER"
		}, {
			dataSpac: "YD",
			dataValue: "雅典",
			dataSzm: "ATH",
			dataTags: "YADIAN"
		}, {
			dataSpac: "YHNSB",
			dataValue: "约翰内斯堡",
			dataSzm: "JNB",
			dataTags: "YUEHANNEISIBAO"
		}, {
			dataSpac: "YDSYBB",
			dataValue: "亚的斯亚贝巴",
			dataSzm: "ADD",
			dataTags: "YADESIYABEIBA"
		}]
	}, {
		groupname: "Z",
		citylist: [{
			dataSpac: "ZJKS",
			dataValue: "张家口",
			dataSzm: "ZQZ",
			dataTags: "ZHANGJIAKOUSHI"
		}, {
			dataSpac: "ZS",
			dataValue: "舟山",
			dataSzm: "HSN",
			dataTags: "ZHOUSHA"
		}, {
			dataSpac: "ZZ",
			dataValue: "郑州",
			dataSzm: "CGO",
			dataTags: "ZHENGZHOU"
		}, {
			dataSpac: "ZJJ",
			dataValue: "张家界",
			dataSzm: "DYG",
			dataTags: "ZHANGJIAJIE"
		}, {
			dataSpac: "ZH",
			dataValue: "珠海",
			dataSzm: "ZUH",
			dataTags: "ZHUHAI"
		}, {
			dataSpac: "ZJS",
			dataValue: "湛江",
			dataSzm: "ZHA",
			dataTags: "ZHANJIANGSHI"
		}, {
			dataSpac: "ZY",
			dataValue: "遵义",
			dataSzm: "ZYI",
			dataTags: "ZUIYI"
		}, {
			dataSpac: "ZT",
			dataValue: "昭通",
			dataSzm: "ZAT",
			dataTags: "ZHAOTONG"
		}, {
			dataSpac: "ZYS",
			dataValue: "张掖",
			dataSzm: "YZY",
			dataTags: "ZHANGYESHI"
		}, {
			dataSpac: "ZWS",
			dataValue: "中卫",
			dataSzm: "ZHY",
			dataTags: "ZHONGWEISHI"
		}, {
			dataSpac: "ZJG",
			dataValue: "芝加哥",
			dataSzm: "CHI",
			dataTags: "ZHIJIAGE"
		}]
	}],
	hotList: [{
		dataSpac: "BJ",
		dataValue: "北京",
		dataSzm: "BJS",
		dataTags: "BEIJING"
	}, {
		dataSpac: "TJ",
		dataValue: "天津",
		dataSzm: "TSN",
		dataTags: "TIANJI"
	}, {
		dataSpac: "DL",
		dataValue: "大连",
		dataSzm: "DLC",
		dataTags: "DA LIAN"
	}, {
		dataSpac: "CC",
		dataValue: "长春",
		dataSzm: "CGQ",
		dataTags: "CHANGCHUN"
	}, {
		dataSpac: "SH",
		dataValue: "上海",
		dataSzm: "SHA",
		dataTags: "SHANGHAI"
	}, {
		dataSpac: "NJ",
		dataValue: "南京",
		dataSzm: "NKG",
		dataTags: "NANJING"
	}, {
		dataSpac: "HZ",
		dataValue: "杭州",
		dataSzm: "HGH",
		dataTags: "HANGZHOU"
	}, {
		dataSpac: "XM",
		dataValue: "厦门",
		dataSzm: "XMN",
		dataTags: "XIAME"
	}, {
		dataSpac: "J",
		dataValue: "济南",
		dataSzm: "TNA",
		dataTags: "JINA"
	}, {
		dataSpac: "QD",
		dataValue: "青岛",
		dataSzm: "TAO",
		dataTags: "QINGDAO"
	}, {
		dataSpac: "ZZ",
		dataValue: "郑州",
		dataSzm: "CGO",
		dataTags: "ZHENGZHOU"
	}, {
		dataSpac: "WH",
		dataValue: "武汉",
		dataSzm: "WUH",
		dataTags: "WUHA"
	}, {
		dataSpac: "CS",
		dataValue: "长沙",
		dataSzm: "CSX",
		dataTags: "CHANGSHA"
	}, {
		dataSpac: "GZ",
		dataValue: "广州",
		dataSzm: "CAN",
		dataTags: "GUANGZHOU"
	}, {
		dataSpac: "SZ",
		dataValue: "深圳",
		dataSzm: "SZX",
		dataTags: "SHENZHE"
	}, {
		dataSpac: "SY",
		dataValue: "三亚",
		dataSzm: "SYX",
		dataTags: "SANYA"
	}, {
		dataSpac: "CQ",
		dataValue: "重庆",
		dataSzm: "CKG",
		dataTags: "CHONGQING"
	}, {
		dataSpac: "CD",
		dataValue: "成都",
		dataSzm: "CTU",
		dataTags: "CHENGDU"
	}, {
		dataSpac: "KM",
		dataValue: "昆明",
		dataSzm: "KMG",
		dataTags: "KUNMING"
	}, {
		dataSpac: "XA",
		dataValue: "西安",
		dataSzm: "XIY",
		dataTags: "XIA"
	}]
}