dataCityJson = {
	list: [{
		groupname: "A",
		citylist: [{
			dataSpac: "AM",
			dataValue: "澳门",
			dataSzm: "MFM",
			dataTags: "AOMEN"
		}, {
			dataSpac: "AKL",
			dataValue: "奥克兰",
			dataSzm: "AKL",
			dataTags: "AOKELAN"
		}, {
			dataSpac: "ALD",
			dataValue: "奥兰多",
			dataSzm: "ORL",
			dataTags: "AOLANDUO"
		}, {
			dataSpac: "ADMD",
			dataValue: "埃德蒙顿",
			dataSzm: "YEA",
			dataTags: "AIDEMENGDUN"
		}, {
			dataSpac: "AMSTD",
			dataValue: "阿姆斯特丹",
			dataSzm: "AMS",
			dataTags: "AMUSITEDAN"
		}, {
			dataSpac: "ADB",
			dataValue: "爱丁堡",
			dataSzm: "EDI",
			dataTags: "AIDINGBAO"
		}, {
			dataSpac: "AKL",
			dataValue: "阿克拉",
			dataSzm: "ACC",
			dataTags: "AKELA"
		}, {
			dataSpac: "AEJE",
			dataValue: "阿尔及尔",
			dataSzm: "ALG",
			dataTags: "AERJIER"
		}, {
			dataSpac: "ABJ",
			dataValue: "阿布贾",
			dataSzm: "ABV",
			dataTags: "ABUJIA"
		}]
	}, {
		groupname: "B",
		citylist: [{
			dataSpac: "BJ",
			dataValue: "北京",
			dataSzm: "BJS",
			dataTags: "BEIJING"
		}, {
			dataSpac: "BL",
			dataValue: "巴黎(法国)",
			dataSzm: "PAR",
			dataTags: "BALI"
		}, {
			dataSpac: "BLD",
			dataValue: "巴厘岛",
			dataSzm: "DPS",
			dataTags: "BALIDAO"
		}, {
			dataSpac: "BLSB",
			dataValue: "布里斯班",
			dataSzm: "BNE",
			dataTags: "BULISIBAN"
		}, {
			dataSpac: "BC",
			dataValue: "槟城",
			dataSzm: "PEN",
			dataTags: "BINCHENG"
		}, {
			dataSpac: "BSD",
			dataValue: "波士顿",
			dataSzm: "BOS",
			dataTags: "BOSHIDUN"
		}, {
			dataSpac: "BYNSALS",
			dataValue: "布宜诺斯艾利斯",
			dataSzm: "BUE",
			dataTags: "BUYINUOSIAILISI"
		}, {
			dataSpac: "BL",
			dataValue: "柏林",
			dataSzm: "BER",
			dataTags: "BOLIN"
		}, {
			dataSpac: "BMH",
			dataValue: "伯明翰",
			dataSzm: "BHX",
			dataTags: "BOMINGHAN"
		}, {
			dataSpac: "BSLN",
			dataValue: "巴塞罗那",
			dataSzm: "BCN",
			dataTags: "BASAILUONA"
		}, {
			dataSpac: "BLSE",
			dataValue: "布鲁塞尔",
			dataSzm: "BRU",
			dataTags: "BULUSAIER"
		}, {
			dataSpac: "BLG",
			dataValue: "布拉格",
			dataSzm: "PRG",
			dataTags: "BULAGE"
		}, {
			dataSpac: "BDPS",
			dataValue: "布达佩斯",
			dataSzm: "BUD",
			dataTags: "BUDAPEISI"
		}]
	}, {
		groupname: "C",
		citylist: [{
			dataSpac: "DC",
			dataValue: "成都",
			dataSzm: "CTU",
			dataTags: "CHENGDU"
		}, {
			dataSpac: "CQ",
			dataValue: "重庆",
			dataSzm: "CKG",
			dataTags: "CHONGQING"
		}, {
			dataSpac: "CS",
			dataValue: "长沙",
			dataSzm: "CSX",
			dataTags: "CHANGSHA"
		}, {
			dataSpac: "CC",
			dataValue: "长春",
			dataSzm: "CGQ",
			dataTags: "CHANGCHUN"
		}]
	}, {
		groupname: "D",
		citylist: [{
			dataSpac: "DL",
			dataValue: "大连",
			dataSzm: "DLC",
			dataTags: "DALIAN"
		}, {
			dataSpac: "DJ",
			dataValue: "东京",
			dataSzm: "TYO",
			dataTags: "DONGJING"
		}, {
			dataSpac: "DB",
			dataValue: "大阪",
			dataSzm: "OSA",
			dataTags: "DABAN"
		}, {
			dataSpac: "DLD",
			dataValue: "多伦多",
			dataSzm: "YTO",
			dataTags: "DUOLUNDUO"
		}, {
			dataSpac: "DB",
			dataValue: "迪拜",
			dataSzm: "DXB",
			dataTags: "DIBAI"
		}, {
			dataSpac: "DTL",
			dataValue: "底特律",
			dataSzm: "DTT",
			dataTags: "DITELV"
		}, {
			dataSpac: "DLS",
			dataValue: "达拉斯",
			dataSzm: "DFW",
			dataTags: "DALASI"
		}, {
			dataSpac: "DF",
			dataValue: "丹佛",
			dataSzm: "DEN",
			dataTags: "DANFO"
		}, {
			dataSpac: "DBL",
			dataValue: "都柏林",
			dataSzm: "DUB",
			dataTags: "DUBOLIN"
		}, {
			dataSpac: "DSEDF",
			dataValue: "杜塞尔多夫",
			dataSzm: "DUS",
			dataTags: "DUSAIERDUOFU"
		}, {
			dataSpac: "DLSSLM",
			dataValue: "达累斯萨拉姆",
			dataSzm: "DAR",
			dataTags: "DALEISISALAMU"
		}, {
			dataSpac: "DLBL",
			dataValue: "的黎波里",
			dataSzm: "TIP",
			dataTags: "DELIBOLI"
		}]
	}, {
		groupname: "F",
		citylist: [{
			dataSpac: "FZ",
			dataValue: "福州",
			dataSzm: "FOC",
			dataTags: "FUZHOU"
		}, {
			dataSpac: "FS",
			dataValue: "釜山",
			dataSzm: "PUS",
			dataTags: "FUSHAN"
		}, {
			dataSpac: "FG",
			dataValue: "福冈",
			dataSzm: "FUK",
			dataTags: "FUGANG"
		}, {
			dataSpac: "FLKF",
			dataValue: "法兰克福",
			dataSzm: "FRA",
			dataTags: "FALANKEFU"
		}, {
			dataSpac: "FC",
			dataValue: "费城",
			dataSzm: "PHI",
			dataTags: "FEICHENG"
		}, {
			dataSpac: "FHC",
			dataValue: "凤凰城",
			dataSzm: "PHX",
			dataTags: "FENGHUANGCHENG"
		}]
	}, {
		groupname: "G",
		citylist: [{
			dataSpac: "GZ",
			dataValue: "广州",
			dataSzm: "CAN",
			dataTags: "GUANGZHOU"
		}, {
			dataSpac: "GY",
			dataValue: "贵阳",
			dataSzm: "KWE",
			dataTags: "GUIYANG"
		}, {
			dataSpac: "GX",
			dataValue: "高雄",
			dataSzm: "KHH",
			dataTags: "GAOXIONG"
		}, {
			dataSpac: "GBHG",
			dataValue: "哥本哈根",
			dataSzm: "CPH",
			dataTags: "GEBENHAGEN"
		}, {
			dataSpac: "GLSG",
			dataValue: "格拉斯哥",
			dataSzm: "GLA",
			dataTags: "GELASIGE"
		}]
	}, {
		groupname: "H",
		citylist: [{
			dataSpac: "HZ",
			dataValue: "杭州",
			dataSzm: "HGH",
			dataTags: "HANGZHOU"
		}, {
			dataSpac: "HK",
			dataValue: "海口",
			dataSzm: "HAK",
			dataTags: "HAIKOU"
		}, {
			dataSpac: "HEB",
			dataValue: "哈尔滨",
			dataSzm: "HRB",
			dataTags: "HAERBIN"
		}, {
			dataSpac: "HZMS",
			dataValue: "胡志明市",
			dataSzm: "SGN",
			dataTags: "HUZHIMINGSHI"
		}, {
			dataSpac: "HN",
			dataValue: "河内",
			dataSzm: "HAN",
			dataTags: "HENEI"
		}, {
			dataSpac: "HSD",
			dataValue: "华盛顿",
			dataSzm: "WAS",
			dataTags: "HUASHENGDUN"
		}, {
			dataSpac: "HNLL",
			dataValue: "火奴鲁鲁",
			dataSzm: "HNL",
			dataTags: "HUONULULU"
		}, {
			dataSpac: "HEXJ",
			dataValue: "赫尔辛基",
			dataSzm: "HEL",
			dataTags: "HEERXINJI"
		}, {
			dataSpac: "HB",
			dataValue: "汉堡",
			dataSzm: "HAM",
			dataTags: "HANBAO"
		}]
	}, {
		groupname: "J",
		citylist: [{
			dataSpac: "JN",
			dataValue: "济南",
			dataSzm: "TNA",
			dataTags: "JINAN"
		}, {
			dataSpac: "JLP",
			dataValue: "吉隆坡",
			dataSzm: "KUL",
			dataTags: "JILONGPO"
		}, {
			dataSpac: "JZD",
			dataValue: "济州岛",
			dataSzm: "CJU",
			dataTags: "JIZHOUDAO"
		}, {
			dataSpac: "JJS",
			dataValue: "旧金山",
			dataSzm: "SFO",
			dataTags: "JIUJINSHAN"
		}, {
			dataSpac: "JDMD",
			dataValue: "加德满都",
			dataSzm: "KTM",
			dataTags: "JIADEMANDU"
		}, {
			dataSpac: "JB",
			dataValue: "金边",
			dataSzm: "PNH",
			dataTags: "JINBIAN"
		}, {
			dataSpac: "JF",
			dataValue: "基辅",
			dataSzm: "IEV",
			dataTags: "JIFU"
		}]
	}, {
		groupname: "K",
		citylist: [{
			dataSpac: "KM",
			dataValue: "昆明",
			dataSzm: "KMG",
			dataTags: "KUNMING"
		}, {
			dataSpac: "KEJL",
			dataValue: "卡尔加里",
			dataSzm: "YYC",
			dataTags: "KAERJIALI"
		}, {
			dataSpac: "KL",
			dataValue: "开罗",
			dataSzm: "CAI",
			dataTags: "KAILUO"
		}, {
			dataSpac: "KPD",
			dataValue: "开普敦",
			dataSzm: "CPT",
			dataTags: "KAIPUDUN"
		}, {
			dataSpac: "KTM",
			dataValue: "喀土穆",
			dataSzm: "KRT",
			dataTags: "KATUMU"
		}, {
			dataSpac: "KSBLK",
			dataValue: "卡萨布兰卡",
			dataSzm: "CAS",
			dataTags: "KASABULANKA"
		}]
	}, {
		groupname: "L",
		citylist: [{
			dataSpac: "LJ",
			dataValue: "丽江",
			dataSzm: "LJG",
			dataTags: "LIJIANG"
		}, {
			dataSpac: "LSJ",
			dataValue: "洛杉矶",
			dataSzm: "LAX",
			dataTags: "LUOSHANJI"
		}, {
			dataSpac: "LD",
			dataValue: "伦敦(英国)",
			dataSzm: "LON",
			dataTags: "LUNDUN"
		}, {
			dataSpac: "LSWJS",
			dataValue: "拉斯维加斯",
			dataSzm: "LAS",
			dataTags: "LASIWEIJIASI"
		}, {
			dataSpac: "LYRNL",
			dataValue: "里约热内卢",
			dataSzm: "RIO",
			dataTags: "LIYUERENEILU"
		}, {
			dataSpac: "LM",
			dataValue: "罗马",
			dataSzm: "ROM",
			dataTags: "LUOMA"
		}, {
			dataSpac: "LGS",
			dataValue: "拉各斯",
			dataSzm: "LOS",
			dataTags: "LAGESI"
		}]
	}, {
		groupname: "M",
		citylist: [{
			dataSpac: "MGW",
			dataValue: "名古屋",
			dataSzm: "NGO",
			dataTags: "MINGGUWU"
		}, {
			dataSpac: "MG",
			dataValue: "曼谷",
			dataSzm: "BKK",
			dataTags: "MANGU"
		}, {
			dataSpac: "MEB",
			dataValue: "墨尔本",
			dataSzm: "MEL",
			dataTags: "MOERBEN"
		}, {
			dataSpac: "MNL",
			dataValue: "马尼拉",
			dataSzm: "MNL",
			dataTags: "MANILA"
		}, {
			dataSpac: "ML",
			dataValue: "马累",
			dataSzm: "MLE",
			dataTags: "MALEI"
		}, {
			dataSpac: "MTLE",
			dataValue: "蒙特利尔",
			dataSzm: "YMQ",
			dataTags: "MENGTELIER"
		}, {
			dataSpac: "MNABLS",
			dataValue: "明尼阿波利斯",
			dataSzm: "MSP",
			dataTags: "MINGNIABOLISI"
		}, {
			dataSpac: "MXGC",
			dataValue: "墨西哥城",
			dataSzm: "MEX",
			dataTags: "MOXIGECHENG"
		}, {
			dataSpac: "MAM",
			dataValue: "迈阿密",
			dataSzm: "MIA",
			dataTags: "MAIAMI"
		}, {
			dataSpac: "MSK",
			dataValue: "莫斯科",
			dataSzm: "MOS",
			dataTags: "MOSIKE"
		}, {
			dataSpac: "ML",
			dataValue: "米兰",
			dataSzm: "MIL",
			dataTags: "MILAN"
		}, {
			dataSpac: "MDL",
			dataValue: "马德里",
			dataSzm: "MAD",
			dataTags: "MADELI"
		}, {
			dataSpac: "MNH",
			dataValue: "慕尼黑",
			dataSzm: "MUC",
			dataTags: "MUNIHEI"
		}, {
			dataSpac: "MLQS",
			dataValue: "毛里求斯",
			dataSzm: "MRU",
			dataTags: "MAOLIQIUSI"
		}]
	}, {
		groupname: "N",
		citylist: [{
			dataSpac: "NJ",
			dataValue: "南京",
			dataSzm: "NKG",
			dataTags: "NANJING"
		}, {
			dataSpac: "NN",
			dataValue: "南宁",
			dataSzm: "NNG",
			dataTags: "NANNING"
		}, {
			dataSpac: "NC",
			dataValue: "南昌",
			dataSzm: "KHN",
			dataTags: "NANCHANG"
		}, {
			dataSpac: "NY",
			dataValue: "纽约",
			dataSzm: "NYC",
			dataTags: "NIUYUE"
		}, {
			dataSpac: "NLB",
			dataValue: "内罗毕",
			dataSzm: "NBO",
			dataTags: "NEILUOBI"
		}]
	}, {
		groupname: "P",
		citylist: [{
			dataSpac: "PJ",
			dataValue: "普吉",
			dataSzm: "HKT",
			dataTags: "PUJI"
		}, {
			dataSpac: "PZB",
			dataValue: "匹兹堡",
			dataSzm: "PIT",
			dataTags: "PIZIBAO"
		}]
	}, {
		groupname: "Q",
		citylist: [{
			dataSpac: "QD",
			dataValue: "青岛",
			dataSzm: "TAO",
			dataTags: "QINGDAO"
		}]
	}, {
		groupname: "R",
		citylist: [{
			dataSpac: "RNW",
			dataValue: "日内瓦",
			dataSzm: "GVA",
			dataTags: "RINEIWA"
		}]
	}, {
		groupname: "S",
		citylist: [{
			dataSpac: "SH",
			dataValue: "上海",
			dataSzm: "SHA",
			dataTags: "SHANGHAI"
		}, {
			dataSpac: "SZ",
			dataValue: "深圳",
			dataSzm: "SZX",
			dataTags: "SHENZHEN"
		}, {
			dataSpac: "SY",
			dataValue: "沈阳",
			dataSzm: "SHE",
			dataTags: "SHENYANG"
		}, {
			dataSpac: "SY",
			dataValue: "三亚",
			dataSzm: "SYX",
			dataTags: "SANYA"
		}, {
			dataSpac: "SE",
			dataValue: "首尔",
			dataSzm: "SEL",
			dataTags: "SHOUER"
		}, {
			dataSpac: "SBL",
			dataValue: "圣保罗",
			dataSzm: "SAO",
			dataTags: "SHENGBAOLUO"
		}, {
			dataSpac: "SDGEM",
			dataValue: "斯德哥尔摩",
			dataSzm: "STO",
			dataTags: "SIDEGEERMO"
		}, {
			dataSpac: "SLS",
			dataValue: "苏黎世",
			dataSzm: "ZRH",
			dataTags: "SULISHI"
		}, {
			dataSpac: "SBDB",
			dataValue: "圣彼得堡",
			dataSzm: "LED",
			dataTags: "SHENGBIDEBAO"
		}, {
			dataSpac: "SSE",
			dataValue: "塞舌尔",
			dataSzm: "SEZ",
			dataTags: "SAISHEER"
		}]
	}, {
		groupname: "T",
		citylist: [{
			dataSpac: "TJ",
			dataValue: "天津",
			dataSzm: "TSN",
			dataTags: "TIANJIN"
		}, {
			dataSpac: "TY",
			dataValue: "太原",
			dataSzm: "TYN",
			dataTags: "TAIYUAN"
		}, {
			dataSpac: "TB",
			dataValue: "台北",
			dataSzm: "TPE",
			dataTags: "TAIBEI"
		}, {
			dataSpac: "TNS",
			dataValue: "突尼斯",
			dataSzm: "TUN",
			dataTags: "TUNISI"
		}]
	}, {
		groupname: "W",
		citylist: [{
			dataSpac: "WLMQ",
			dataValue: "乌鲁木齐",
			dataSzm: "URC",
			dataTags: "WULUMUQI"
		}, {
			dataSpac: "WH",
			dataValue: "武汉",
			dataSzm: "WUH",
			dataTags: "WUHAN"
		}, {
			dataSpac: "WGH",
			dataValue: "温哥华",
			dataSzm: "YVR",
			dataTags: "WENGEHUA"
		}, {
			dataSpac: "WTH",
			dataValue: "渥太华",
			dataSzm: "YOW",
			dataTags: "WOTAIHUA"
		}, {
			dataSpac: "WYN",
			dataValue: "维也纳",
			dataSzm: "VIE",
			dataTags: "WEIYENA"
		}]
	}, {
		groupname: "X",
		citylist: [{
			dataSpac: "XA",
			dataValue: "西安",
			dataSzm: "SIA",
			dataTags: "XIAN"
		}, {
			dataSpac: "XM",
			dataValue: "厦门",
			dataSzm: "XMN",
			dataTags: "XIAMEN"
		}, {
			dataSpac: "XG",
			dataValue: "香港",
			dataSzm: "HKG",
			dataTags: "XIANGGANG"
		}, {
			dataSpac: "XJP",
			dataValue: "新加坡",
			dataSzm: "SIN",
			dataTags: "XINJIAPO"
		}, {
			dataSpac: "XN",
			dataValue: "悉尼",
			dataSzm: "SYD",
			dataTags: "XINI"
		}, {
			dataSpac: "XWY",
			dataValue: "夏威夷",
			dataSzm: "FUK",
			dataTags: "XIAWEIYI"
		}, {
			dataSpac: "XL",
			dataValue: "暹粒",
			dataSzm: "REP",
			dataTags: "XIANLI"
		}, {
			dataSpac: "XDL",
			dataValue: "新德里",
			dataSzm: "DEL",
			dataTags: "XINDELI"
		}, {
			dataSpac: "XYT",
			dataValue: "西雅图",
			dataSzm: "SEA",
			dataTags: "XIYATU"
		}, {
			dataSpac: "XSD",
			dataValue: "休斯敦",
			dataSzm: "HOU",
			dataTags: "XIUSIDUN"
		}]
	}, {
		groupname: "Y",
		citylist: [{
			dataSpac: "YJD",
			dataValue: "雅加达",
			dataSzm: "JKT",
			dataTags: "YAJIADA"
		}, {
			dataSpac: "YTLD",
			dataValue: "亚特兰大",
			dataSzm: "ATL",
			dataTags: "YATELANDA"
		}, {
			dataSpac: "YSTBE",
			dataValue: "伊斯坦布尔",
			dataSzm: "IST",
			dataTags: "YISITANBUER"
		}, {
			dataSpac: "YD",
			dataValue: "雅典",
			dataSzm: "ATH",
			dataTags: "YADIAN"
		}, {
			dataSpac: "YHNSB",
			dataValue: "约翰内斯堡",
			dataSzm: "JNB",
			dataTags: "YUEHANNEISIBAO"
		}, {
			dataSpac: "YDSYBB",
			dataValue: "亚的斯亚贝巴",
			dataSzm: "ADD",
			dataTags: "YADESIYABEIBA"
		}]
	}, {
		groupname: "Z",
		citylist: [{
			dataSpac: "ZZ",
			dataValue: "郑州",
			dataSzm: "CGO",
			dataTags: "ZHENGZHOU"
		}, {
			dataSpac: "ZJG",
			dataValue: "芝加哥",
			dataSzm: "CHI",
			dataTags: "ZHIJIAGE"
		}]
	}],
	hotList: [{
		dataSpac: "XG",
		dataValue: "香港",
		dataSzm: "HKG",
		dataTags: "XIANGGANG"
	}, {
		dataSpac: "SE",
		dataValue: "首尔",
		dataSzm: "SEL",
		dataTags: "SHOUER"
	}, {
		dataSpac: "XJP",
		dataValue: "新加坡",
		dataSzm: "SIN",
		dataTags: "XINJIAPO"
	}, {
		dataSpac: "MG",
		dataValue: "曼谷",
		dataSzm: "BKK",
		dataTags: "MANGU"
	}, {
		dataSpac: "DJ",
		dataValue: "东京",
		dataSzm: "TYO",
		dataTags: "DONGJING"
	}, {
		dataSpac: "TB",
		dataValue: "台北",
		dataSzm: "TPE",
		dataTags: "TAIBEI"
	}, {
		dataSpac: "LSJ",
		dataValue: "洛杉矶",
		dataSzm: "LAX",
		dataTags: "LUOSHANJI"
	}, {
		dataSpac: "DB",
		dataValue: "大阪",
		dataSzm: "OSA",
		dataTags: "DABAN"
	}, {
		dataSpac: "AM",
		dataValue: "澳门",
		dataSzm: "MFM",
		dataTags: "AOMEN"
	}]
}