dataCityJson = {
		list: [{
			groupname: "A",
			citylist: [{
				dataSpac: "ADLY",
				dataTags: "AODALIYA",
				dataEnglish: "Australia",
				dataSzm: "AU",
				dataValue: "澳大利亚"
			}, {
				dataSpac: "ADE",
				dataTags: "ANDAOER",
				dataEnglish: "Andorra",
				dataSzm: "AD",
				dataValue: "安道尔"
			}, {
				dataSpac: "ALQ",
				dataTags: "ALIANQIU",
				dataEnglish: "United Arab Emirates",
				dataSzm: "AE",
				dataValue: "阿联酋"
			}, {
				dataSpac: "AFH",
				dataTags: "AFUHAN",
				dataEnglish: "Afghanistan",
				dataSzm: "AF",
				dataValue: "阿富汗"
			}, {
				dataSpac: "ATGHBBD",
				dataTags: "ANTIGUAHEBABUDA",
				dataEnglish: "Antigua and barbuda",
				dataSzm: "AG",
				dataValue: "安提瓜和巴布达"
			}, {
				dataSpac: "AGL",
				dataTags: "ANGUILA",
				dataEnglish: "Anguilla",
				dataSzm: "AI",
				dataValue: "安圭拉"
			}, {
				dataSpac: "AEBNY",
				dataTags: "AERBANIYA",
				dataEnglish: "Albania",
				dataSzm: "AL",
				dataValue: "阿尔巴尼亚"
			}, {
				dataSpac: "AGL",
				dataTags: "ANGELA",
				dataEnglish: "Angola",
				dataSzm: "AO",
				dataValue: "安哥拉"
			}, {
				dataSpac: "AGT",
				dataTags: "AGENTING",
				dataEnglish: "Argentina",
				dataSzm: "AR",
				dataValue: "阿根廷"
			}, {
				dataSpac: "ADL",
				dataTags: "AODILI",
				dataEnglish: "Austria",
				dataSzm: "AT",
				dataValue: "奥地利"
			}, {
				dataSpac: "ALB",
				dataTags: "ALUBA",
				dataEnglish: "Aruba",
				dataSzm: "AW",
				dataValue: "阿鲁巴"
			}, {
				dataSpac: "ASBJ",
				dataTags: "ASAIBAIJIANG",
				dataEnglish: "Azerbaijan",
				dataSzm: "AZ",
				dataValue: "阿塞拜疆"
			}, {
				dataSpac: "AEJLY",
				dataTags: "AERJILIYA",
				dataEnglish: "Algeria",
				dataSzm: "DZ",
				dataValue: "阿尔及利亚"
			}, {
				dataSpac: "ASNY",
				dataTags: "AISHANIYA",
				dataEnglish: "Estonia",
				dataSzm: "EE",
				dataValue: "爱沙尼亚"
			}, {
				dataSpac: "AJ",
				dataTags: "AIJI",
				dataEnglish: "Egypt",
				dataSzm: "EG",
				dataValue: "埃及"
			}, {
				dataSpac: "ASEBY",
				dataTags: "AISAIEBIYA",
				dataEnglish: "Ethiopia",
				dataSzm: "ET",
				dataValue: "埃塞俄比亚"
			}, {
				dataSpac: "AEL",
				dataTags: "AIERLAN",
				dataEnglish: "Ireland",
				dataSzm: "IE",
				dataValue: "爱尔兰"
			}, {
				dataSpac: "AM",
				dataTags: "AMAN",
				dataEnglish: "Oman",
				dataSzm: "OM",
				dataValue: "阿曼"
			}]
		}, {
			groupname: "B",
			citylist: [{
				dataSpac: "BJST",
				dataTags: "BAJISITAN",
				dataEnglish: "Pakistan",
				dataSzm: "PK",
				dataValue: "巴基斯坦"
			}, {
				dataSpac: "BX",
				dataTags: "BAXI",
				dataEnglish: "Brazil",
				dataSzm: "BR",
				dataValue: "巴西"
			}, {
				dataSpac: "BH",
				dataTags: "BOHEI",
				dataEnglish: "Bosnia and Herzegovina",
				dataSzm: "BA",
				dataValue: "波黑"
			}, {
				dataSpac: "BBDS",
				dataTags: "BABADUOSI",
				dataEnglish: "Barbados",
				dataSzm: "BB",
				dataValue: "巴巴多斯"
			}, {
				dataSpac: "BLS",
				dataTags: "BILISHI",
				dataEnglish: "Belgium",
				dataSzm: "BE",
				dataValue: "比利时"
			}, {
				dataSpac: "BJNFS",
				dataTags: "BUJINAFASUO",
				dataEnglish: "Burkina Faso",
				dataSzm: "BF",
				dataValue: "布基纳法索"
			}, {
				dataSpac: "BJLY",
				dataTags: "BAOJIALIYA",
				dataEnglish: "Bulgaria",
				dataSzm: "BG",
				dataValue: "保加利亚"
			}, {
				dataSpac: "BL",
				dataTags: "BALIN",
				dataEnglish: "Bahrain",
				dataSzm: "BH",
				dataValue: "巴林"
			}, {
				dataSpac: "BLD",
				dataTags: "BULONGDI",
				dataEnglish: "Burundi",
				dataSzm: "BI",
				dataValue: "布隆迪"
			}, {
				dataSpac: "BN",
				dataTags: "BEINING",
				dataEnglish: "Benin",
				dataSzm: "BJ",
				dataValue: "贝宁"
			}, {
				dataSpac: "BMD",
				dataTags: "BAIMUDA",
				dataEnglish: "Bermuda",
				dataSzm: "BM",
				dataValue: "百慕大"
			}, {
				dataSpac: "BLWY",
				dataTags: "BOLIWEIYA",
				dataEnglish: "Bolivia",
				dataSzm: "BO",
				dataValue: "玻利维亚"
			}, {
				dataSpac: "BHM",
				dataTags: "BAHAMA",
				dataEnglish: "Bahamas",
				dataSzm: "BS",
				dataValue: "巴哈马"
			}, {
				dataSpac: "BD",
				dataTags: "BUDAN",
				dataEnglish: "Bhutan",
				dataSzm: "BT",
				dataValue: "不丹"
			}, {
				dataSpac: "BWD",
				dataTags: "BUWEIDAO",
				dataEnglish: "Bouvet Island",
				dataSzm: "BV",
				dataValue: "布维岛"
			}, {
				dataSpac: "BCWN",
				dataTags: "BOCIWANA",
				dataEnglish: "Botswana",
				dataSzm: "BW",
				dataValue: "博茨瓦纳"
			}, {
				dataSpac: "BELS",
				dataTags: "BAIELUOSI",
				dataEnglish: "Belarus",
				dataSzm: "BY",
				dataValue: "白俄罗斯"
			}, {
				dataSpac: "BLZ",
				dataTags: "BOLIZI",
				dataEnglish: "Belize",
				dataSzm: "BZ",
				dataValue: "伯利兹"
			}, {
				dataSpac: "BD",
				dataTags: "BINGDAO",
				dataEnglish: "Iceland",
				dataSzm: "IS",
				dataValue: "冰岛"
			}, {
				dataSpac: "BMLYN",
				dataTags: "BEIMALIYANA",
				dataEnglish: "Northern Marianas Islands",
				dataSzm: "MP",
				dataValue: "北马里亚纳"
			}, {
				dataSpac: "BNM",
				dataTags: "BANAMA",
				dataEnglish: "Panama",
				dataSzm: "PA",
				dataValue: "巴拿马"
			}, {
				dataSpac: "BBYXJNY",
				dataTags: "BABUYAXINJINEIYA",
				dataEnglish: "Papua New Guinea",
				dataSzm: "PG",
				dataValue: "巴布亚新几内亚"
			}, {
				dataSpac: "BL",
				dataTags: "BOLAN",
				dataEnglish: "Poland",
				dataSzm: "PL",
				dataValue: "波兰"
			}, {
				dataSpac: "BDLG",
				dataTags: "BODUOLIGE",
				dataEnglish: "Puerto Rico",
				dataSzm: "PR",
				dataValue: "波多黎各"
			}, {
				dataSpac: "BLST",
				dataTags: "BALESITAN",
				dataEnglish: "Palestine",
				dataSzm: "PS",
				dataValue: "巴勒斯坦"
			}, {
				dataSpac: "BLG",
				dataTags: "BALAGUI",
				dataEnglish: "Paraguay",
				dataSzm: "PY",
				dataValue: "巴拉圭"
			}]
		}, {
			groupname: "C",
			citylist: [{
				dataSpac: "CDJNY",
				dataTags: "CHIDAOJINEIYA",
				dataEnglish: "Equatorial Guinea",
				dataSzm: "GQ",
				dataValue: "赤道几内亚"
			}, {
				dataSpac: "CX",
				dataTags: "CHAOXIAN",
				dataEnglish: "Korea, Democratic Peoples Republic of",
				dataSzm: "KP",
				dataValue: "朝鲜"
			}]
		}, {
			groupname: "D",
			citylist: [{
				dataSpac: "DG",
				dataTags: "DEGUO",
				dataEnglish: "Germany",
				dataSzm: "DE",
				dataValue: "德国"
			}, {
				dataSpac: "DM",
				dataTags: "DANMAI",
				dataEnglish: "Denmark",
				dataSzm: "DK",
				dataValue: "丹麦"
			}, {
				dataSpac: "DMNK",
				dataTags: "DUOMINIKE",
				dataEnglish: "Dominica",
				dataSzm: "DM",
				dataValue: "多米尼克"
			}, {
				dataSpac: "DMNJ",
				dataTags: "DUOMINIJIA",
				dataEnglish: "Dominican Republic",
				dataSzm: "DO",
				dataValue: "多米尼加"
			}, {
				dataSpac: "DG",
				dataTags: "DUOGE",
				dataEnglish: "Togo",
				dataSzm: "TG",
				dataValue: "多哥"
			}, {
				dataSpac: "DDW",
				dataTags: "DONGDIWEN",
				dataEnglish: "East Timor",
				dataSzm: "TP",
				dataValue: "东帝汶"
			}]
		}, {
			groupname: "E",
			citylist: [{
				dataSpac: "ELS",
				dataTags: "ELUOSI",
				dataEnglish: "Russia",
				dataSzm: "RU",
				dataValue: "俄罗斯"
			}, {
				dataSpac: "EGDE",
				dataTags: "EGUADUOER",
				dataEnglish: "Ecuador",
				dataSzm: "EC",
				dataValue: "厄瓜多尔"
			}, {
				dataSpac: "ELTLY",
				dataTags: "ELITELIYA",
				dataEnglish: "Eritrea",
				dataSzm: "ER",
				dataValue: "厄立特里亚"
			}]
		}, {
			groupname: "F",
			citylist: [{
				dataSpac: "FG",
				dataTags: "FAGUO",
				dataEnglish: "France",
				dataSzm: "FR",
				dataValue: "法国"
			}, {
				dataSpac: "FDJ",
				dataTags: "FODEJIAO",
				dataEnglish: "Cape Verde",
				dataSzm: "CV",
				dataValue: "佛得角"
			}, {
				dataSpac: "FL",
				dataTags: "FENLAN",
				dataEnglish: "Finland",
				dataSzm: "FI",
				dataValue: "芬兰"
			}, {
				dataSpac: "FKLQD(MEWNS)",
				dataTags: "FUKELANQUNDAO(MERWEINASI)",
				dataEnglish: "Falkland Islands (Malvinas)",
				dataSzm: "FK",
				dataValue: "福克兰群岛（马尔维纳斯）"
			}, {
				dataSpac: "FLQD",
				dataTags: "FALUOQUNDAO",
				dataEnglish: "Faroe Islands",
				dataSzm: "FO",
				dataValue: "法罗群岛"
			}, {
				dataSpac: "FSGYN",
				dataTags: "FASHUGUIYANA",
				dataEnglish: "French Guiana",
				dataSzm: "GF",
				dataValue: "法属圭亚那"
			}, {
				dataSpac: "FSBLNXY",
				dataTags: "FASHUBOLINIXIYA",
				dataEnglish: "French Polynesia",
				dataSzm: "PF",
				dataValue: "法属波利尼西亚"
			}, {
				dataSpac: "FLB",
				dataTags: "FEILVBIN",
				dataEnglish: "Philippines",
				dataSzm: "PH",
				dataValue: "菲律宾"
			}, {
				dataSpac: "FSNBLT",
				dataTags: "FASHUNANBULINGTU",
				dataEnglish: "French Southern Territories",
				dataSzm: "TF",
				dataValue: "法属南部领土"
			}, {
				dataSpac: "FDG",
				dataTags: "FANDIGANG",
				dataEnglish: "Vatican",
				dataSzm: "VA",
				dataValue: "梵蒂冈"
			}, {
				dataSpac: "FJ",
				dataTags: "FEIJI",
				dataEnglish: "Fiji",
				dataSzm: "FJ",
				dataValue: "斐济"
			}]
		}, {
			groupname: "G",
			citylist: [{
				dataSpac: "GG(J)",
				dataTags: "GANGGUO(JIN)",
				dataEnglish: "Congo",
				dataSzm: "CD",
				dataValue: "刚果(金)"
			}, {
				dataSpac: "GG(B)",
				dataTags: "GANGGUO(BU)",
				dataEnglish: "Congo",
				dataSzm: "CG",
				dataValue: "刚果（布）"
			}, {
				dataSpac: "GLBY",
				dataTags: "GELUNBIYA",
				dataEnglish: "Columbia",
				dataSzm: "CO",
				dataValue: "哥伦比亚"
			}, {
				dataSpac: "GSDLJ",
				dataTags: "GESIDALIJIA",
				dataEnglish: "Costa Rica",
				dataSzm: "CR",
				dataValue: "哥斯达黎加"
			}, {
				dataSpac: "GB",
				dataTags: "GUBA",
				dataEnglish: "Cuba",
				dataSzm: "CU",
				dataValue: "古巴"
			}, {
				dataSpac: "GLND",
				dataTags: "GELINNADA",
				dataEnglish: "Grenada",
				dataSzm: "GD",
				dataValue: "格林纳达"
			}, {
				dataSpac: "GLJY",
				dataTags: "GELUJIYA",
				dataEnglish: "Georgia",
				dataSzm: "GE",
				dataValue: "格鲁吉亚"
			}, {
				dataSpac: "GLL",
				dataTags: "GELINGLAN",
				dataEnglish: "Greenland",
				dataSzm: "GL",
				dataValue: "格陵兰"
			}, {
				dataSpac: "GBY",
				dataTags: "GANGBIYA",
				dataEnglish: "Gambia",
				dataSzm: "GM",
				dataValue: "冈比亚"
			}, {
				dataSpac: "GDLP",
				dataTags: "GUADELUOPU",
				dataEnglish: "Guadeloupe",
				dataSzm: "GP",
				dataValue: "瓜德罗普"
			}, {
				dataSpac: "GD",
				dataTags: "GUANDAO",
				dataEnglish: "Guam",
				dataSzm: "GU",
				dataValue: "关岛"
			}, {
				dataSpac: "GYN",
				dataTags: "GUIYANA",
				dataEnglish: "Guyana",
				dataSzm: "GY",
				dataValue: "圭亚那"
			}]
		}, {
			groupname: "H",
			citylist: [{
				dataSpac: "HG",
				dataTags: "HANGUO",
				dataEnglish: "Korea,Republic of",
				dataSzm: "KR",
				dataValue: "韩国"
			}, {
				dataSpac: "HSADLS",
				dataTags: "HESHULANDELIESI",
				dataEnglish: "Netherlands Antilles",
				dataSzm: "AN",
				dataValue: "荷属安的列斯"
			}, {
				dataSpac: "HDDHMKTND",
				dataTags: "HEDEDAOHEMAIKETANGNADAO",
				dataEnglish: "Heard Islands and McDonald Islands",
				dataSzm: "HM",
				dataValue: "赫德岛和麦克唐纳岛"
			}, {
				dataSpac: "HDLS",
				dataTags: "HONGDULASI",
				dataEnglish: "Honduras",
				dataSzm: "HN",
				dataValue: "洪都拉斯"
			}, {
				dataSpac: "HD",
				dataTags: "HAIDI",
				dataEnglish: "Haiti",
				dataSzm: "HT",
				dataValue: "海地"
			}, {
				dataSpac: "HSKST",
				dataTags: "HASAKESITAN",
				dataEnglish: "Kazakstan",
				dataSzm: "KZ",
				dataValue: "哈萨克斯坦"
			}, {
				dataSpac: "HL",
				dataTags: "HELAN",
				dataEnglish: "Netherlands",
				dataSzm: "NL",
				dataValue: "荷兰"
			}]
		}, {
			groupname: "J",
			citylist: [{
				dataSpac: "JND",
				dataTags: "JIANADA",
				dataEnglish: "Canada",
				dataSzm: "CA",
				dataValue: "加拿大"
			}, {
				dataSpac: "JK",
				dataTags: "JIEKE",
				dataEnglish: "Czech Republic",
				dataSzm: "CZ",
				dataValue: "捷克"
			}, {
				dataSpac: "JBT",
				dataTags: "JIBUTI",
				dataEnglish: "Djibouti",
				dataSzm: "DJ",
				dataValue: "吉布提"
			}, {
				dataSpac: "JP",
				dataTags: "JIAPENG",
				dataEnglish: "Gabon",
				dataSzm: "GA",
				dataValue: "加蓬"
			}, {
				dataSpac: "JN",
				dataTags: "JIANA",
				dataEnglish: "Ghana",
				dataSzm: "GH",
				dataValue: "加纳"
			}, {
				dataSpac: "JNY",
				dataTags: "JINEIYA",
				dataEnglish: "Guinea",
				dataSzm: "GN",
				dataValue: "几内亚"
			}, {
				dataSpac: "JNYBS",
				dataTags: "JINEIYABISHAO",
				dataEnglish: "Guinea-bissau",
				dataSzm: "GW",
				dataValue: "几内亚比绍"
			}, {
				dataSpac: "JEJSST",
				dataTags: "JIERJISISITAN",
				dataEnglish: "Kyrgyzstan",
				dataSzm: "KG",
				dataValue: "吉尔吉斯斯坦"
			}, {
				dataSpac: "JPZ",
				dataTags: "JIANPUZHAI",
				dataEnglish: "Cambodia",
				dataSzm: "KH",
				dataValue: "柬埔寨"
			}, {
				dataSpac: "JLBS",
				dataTags: "JILIBASI",
				dataEnglish: "Kiribati",
				dataSzm: "KI",
				dataValue: "基里巴斯"
			}, {
				dataSpac: "JBBW",
				dataTags: "JINBABUWEI",
				dataEnglish: "Zimbabwe",
				dataSzm: "ZW",
				dataValue: "津巴布韦"
			}]
		}, {
			groupname: "K",
			citylist: [{
				dataSpac: "KKSQD",
				dataTags: "KEKESIQUNDAO",
				dataEnglish: "Coccs(Keeling) Islands",
				dataSzm: "CC",
				dataValue: "科科斯群岛"
			}, {
				dataSpac: "KTDW",
				dataTags: "KETEDIWA",
				dataEnglish: "Cote dIvoire",
				dataSzm: "CI",
				dataValue: "科特迪瓦"
			}, {
				dataSpac: "KML",
				dataTags: "KAMAILONG",
				dataEnglish: "Cameroon",
				dataSzm: "CM",
				dataValue: "喀麦隆"
			}, {
				dataSpac: "KLDY",
				dataTags: "KELUODIYA",
				dataEnglish: "Croatia",
				dataSzm: "HR",
				dataValue: "克罗地亚"
			}, {
				dataSpac: "KNY",
				dataTags: "KENNIYA",
				dataEnglish: "Kenya",
				dataSzm: "KE",
				dataValue: "肯尼亚"
			}, {
				dataSpac: "KML",
				dataTags: "KEMOLUO",
				dataEnglish: "Comoros",
				dataSzm: "KM",
				dataValue: "科摩罗"
			}, {
				dataSpac: "KWT",
				dataTags: "KEWEITE",
				dataEnglish: "Kuwait",
				dataSzm: "KW",
				dataValue: "科威特"
			}, {
				dataSpac: "KMQD",
				dataTags: "KAIMANQUNDAO",
				dataEnglish: "Cayman Islands",
				dataSzm: "KY",
				dataValue: "开曼群岛"
			}, {
				dataSpac: "KTE",
				dataTags: "KATAER",
				dataEnglish: "Qatar",
				dataSzm: "QA",
				dataValue: "卡塔尔"
			}]
		}, {
			groupname: "L",
			citylist: [{
				dataSpac: "LW",
				dataTags: "LAOWO",
				dataEnglish: "Lao",
				dataSzm: "LA",
				dataValue: "老挝"
			}, {
				dataSpac: "LBN",
				dataTags: "LIBANEN",
				dataEnglish: "Lebanon",
				dataSzm: "LB",
				dataValue: "黎巴嫩"
			}, {
				dataSpac: "LZDSD",
				dataTags: "LIEZHIDUNSHIDENG",
				dataEnglish: "Liechtenstein",
				dataSzm: "LI",
				dataValue: "列支敦士登"
			}, {
				dataSpac: "LBLY",
				dataTags: "LIBILIYA",
				dataEnglish: "Liberia",
				dataSzm: "LR",
				dataValue: "利比里亚"
			}, {
				dataSpac: "LST",
				dataTags: "LAISUOTUO",
				dataEnglish: "Lesotho",
				dataSzm: "LS",
				dataValue: "莱索托"
			}, {
				dataSpac: "LTW",
				dataTags: "LITAOWAN",
				dataEnglish: "Lithuania",
				dataSzm: "LT",
				dataValue: "立陶宛"
			}, {
				dataSpac: "LSB",
				dataTags: "LUSENBAO",
				dataEnglish: "Luxembourg",
				dataSzm: "LU",
				dataValue: "卢森堡"
			}, {
				dataSpac: "LTWY",
				dataTags: "LATUOWEIYA",
				dataEnglish: "Latvia",
				dataSzm: "LV",
				dataValue: "拉脱维亚"
			}, {
				dataSpac: "LBY",
				dataTags: "LIBIYA",
				dataEnglish: "Libya",
				dataSzm: "LY",
				dataValue: "利比亚"
			}, {
				dataSpac: "LNW",
				dataTags: "LIUNIWANG",
				dataEnglish: "Reunion",
				dataSzm: "RE",
				dataValue: "留尼汪"
			}, {
				dataSpac: "LMNY",
				dataTags: "LUOMANIYA",
				dataEnglish: "Romania",
				dataSzm: "RO",
				dataValue: "罗马尼亚"
			}, {
				dataSpac: "LWD",
				dataTags: "LUWANGDA",
				dataEnglish: "Rwanda",
				dataSzm: "RW",
				dataValue: "卢旺达"
			}]
		}, {
			groupname: "M",
			citylist: [{
				dataSpac: "MG",
				dataTags: "MEIGUO",
				dataEnglish: "United States",
				dataSzm: "US",
				dataValue: "美国"
			}, {
				dataSpac: "MLXY",
				dataTags: "MALAIXIYA",
				dataEnglish: "Malaysia",
				dataSzm: "MY",
				dataValue: "马来西亚"
			}, {
				dataSpac: "MSSMY",
				dataTags: "MEISHUSAMOYA",
				dataEnglish: "American Samoa",
				dataSzm: "AS",
				dataValue: "美属萨摩亚"
			}, {
				dataSpac: "MJLG",
				dataTags: "MENGJIALAGUO",
				dataEnglish: "Bangladesh",
				dataSzm: "BD",
				dataValue: "孟加拉国"
			}, {
				dataSpac: "MKLNXY",
				dataTags: "MIKELUONIXIYA",
				dataEnglish: "Micronesia",
				dataSzm: "FM",
				dataValue: "密克罗尼西亚"
			}, {
				dataSpac: "MLG",
				dataTags: "MOLUOGE",
				dataEnglish: "Morocco",
				dataSzm: "MA",
				dataValue: "摩洛哥"
			}, {
				dataSpac: "MNG",
				dataTags: "MONAGE",
				dataEnglish: "Monaco",
				dataSzm: "MC",
				dataValue: "摩纳哥"
			}, {
				dataSpac: "MEDW",
				dataTags: "MOERDUOWA",
				dataEnglish: "Moldova",
				dataSzm: "MD",
				dataValue: "摩尔多瓦"
			}, {
				dataSpac: "MDLSJ",
				dataTags: "MADALASIJIA",
				dataEnglish: "Madagascar",
				dataSzm: "MG",
				dataValue: "马达加斯加"
			}, {
				dataSpac: "MSEQD",
				dataTags: "MASHAOERQUNDAO",
				dataEnglish: "Marshall Islands",
				dataSzm: "MH",
				dataValue: "马绍尔群岛"
			}, {
				dataSpac: "ML",
				dataTags: "MALI",
				dataEnglish: "Mali",
				dataSzm: "ML",
				dataValue: "马里"
			}, {
				dataSpac: "MD",
				dataTags: "MIANDIAN",
				dataEnglish: "Myanmar",
				dataSzm: "MM",
				dataValue: "缅甸"
			}, {
				dataSpac: "MG",
				dataTags: "MENGGU",
				dataEnglish: "Mongolia",
				dataSzm: "MN",
				dataValue: "蒙古"
			}, {
				dataSpac: "MTNK",
				dataTags: "MATINIKE",
				dataEnglish: "Martinique",
				dataSzm: "MQ",
				dataValue: "马提尼克"
			}, {
				dataSpac: "MLTNY",
				dataTags: "MAOLITANIYA",
				dataEnglish: "Mauritania",
				dataSzm: "MR",
				dataValue: "毛里塔尼亚"
			}, {
				dataSpac: "MTSLT",
				dataTags: "MENGTESAILATE",
				dataEnglish: "Montserrat",
				dataSzm: "MS",
				dataValue: "蒙特塞拉特"
			}, {
				dataSpac: "MET",
				dataTags: "MAERTA",
				dataEnglish: "Malta",
				dataSzm: "MT",
				dataValue: "马耳他"
			}, {
				dataSpac: "MLQS",
				dataTags: "MAOLIQIUSI",
				dataEnglish: "Mauritius",
				dataSzm: "MU",
				dataValue: "毛里求斯"
			}, {
				dataSpac: "MEDF",
				dataTags: "MAERDAIFU",
				dataEnglish: "Maldives",
				dataSzm: "MV",
				dataValue: "马尔代夫"
			}, {
				dataSpac: "MLW",
				dataTags: "MALAWEI",
				dataEnglish: "Malawi",
				dataSzm: "MW",
				dataValue: "马拉维"
			}, {
				dataSpac: "MSBK",
				dataTags: "MOSANGBIKE",
				dataEnglish: "Mozambique",
				dataSzm: "MZ",
				dataValue: "莫桑比克"
			}, {
				dataSpac: "ML",
				dataTags: "MILU",
				dataEnglish: "Peru",
				dataSzm: "PE",
				dataValue: "秘鲁"
			}, {
				dataSpac: "MGBTWXDY",
				dataTags: "MEIGUOBENTUWAIXIAODAOYU",
				dataEnglish: "United States Minor outlying Islands",
				dataSzm: "UM",
				dataValue: "美国本土外小岛屿"
			}, {
				dataSpac: "MYT",
				dataTags: "MAYUETE",
				dataEnglish: "Mayotte",
				dataSzm: "YT",
				dataValue: "马约特"
			}, {
				dataSpac: "MXG",
				dataTags: "MOXIGE",
				dataEnglish: "Mexico",
				dataSzm: "MX",
				dataValue: "墨西哥"
			}]
		}, {
			groupname: "N",
			citylist: [{
				dataSpac: "NF",
				dataTags: "NANFEI",
				dataEnglish: "South Africa",
				dataSzm: "ZA",
				dataValue: "南非"
			}, {
				dataSpac: "NL",
				dataTags: "NAOLU",
				dataEnglish: "Nauru",
				dataSzm: "NR",
				dataValue: "瑙鲁"
			}, {
				dataSpac: "NJZ",
				dataTags: "NANJIZHOU",
				dataEnglish: "Antarctica",
				dataSzm: "AQ",
				dataValue: "南极洲"
			}, {
				dataSpac: "NQZYDHNSDWQD",
				dataTags: "NANQIAOZHIYADAOHENANSANGDEWEIQIDAO",
				dataEnglish: "South Georgia and the SouthSandwich Islands",
				dataSzm: "GS",
				dataValue: "南乔治亚岛 和 南桑德韦奇岛"
			}, {
				dataSpac: "NMNY",
				dataTags: "NAMINIYA",
				dataEnglish: "Namibia",
				dataSzm: "NA",
				dataValue: "纳米尼亚"
			}, {
				dataSpac: "NRE",
				dataTags: "NIRIER",
				dataEnglish: "Niger",
				dataSzm: "NE",
				dataValue: "尼日尔"
			}, {
				dataSpac: "NFKD",
				dataTags: "NUOFUKEDAO",
				dataEnglish: "Norfolk Island",
				dataSzm: "NF",
				dataValue: "诺福克岛"
			}, {
				dataSpac: "NRLY",
				dataTags: "NIRILIYA",
				dataEnglish: "Nigeria",
				dataSzm: "NG",
				dataValue: "尼日利亚"
			}, {
				dataSpac: "NJLG",
				dataTags: "NIJIALAGUA",
				dataEnglish: "Nicaragua",
				dataSzm: "NI",
				dataValue: "尼加拉瓜"
			}, {
				dataSpac: "NW",
				dataTags: "NUOWEI",
				dataEnglish: "Norway",
				dataSzm: "NO",
				dataValue: "挪威"
			}, {
				dataSpac: "NBE",
				dataTags: "NIBOER",
				dataEnglish: "Nepal",
				dataSzm: "NP",
				dataValue: "尼泊尔"
			}, {
				dataSpac: "NA",
				dataTags: "NIUAI",
				dataEnglish: "Niue",
				dataSzm: "NU",
				dataValue: "纽埃"
			}, {
				dataSpac: "NSLF",
				dataTags: "NANSILAFU",
				dataEnglish: "Yugoslavia",
				dataSzm: "YU",
				dataValue: "南斯拉夫"
			}]
		}, {
			groupname: "P",
			citylist: [{
				dataSpac: "PTY",
				dataTags: "PUTAOYA",
				dataEnglish: "Portugal",
				dataSzm: "PT",
				dataValue: "葡萄牙"
			}, {
				dataSpac: "PKQD",
				dataTags: "PANGKEQUNDAO",
				dataEnglish: "Cook Islands",
				dataSzm: "CK",
				dataValue: "库克群岛"
			}, {
				dataSpac: "PTKE",
				dataTags: "PITEKAIEN",
				dataEnglish: "Pitcairn",
				dataSzm: "PN",
				dataValue: "皮特凯恩"
			}, {
				dataSpac: "PL",
				dataTags: "PALAO",
				dataEnglish: "Palau",
				dataSzm: "PW",
				dataValue: "帕劳"
			}]
		}, {
			groupname: "Q",
			citylist: [{
				dataSpac: "QNMSD",
				dataTags: "QIANNANMASIDUN",
				dataEnglish: "Macedonia",
				dataSzm: "MK",
				dataValue: "前南马其顿"
			}]
		}, {
			groupname: "R",
			citylist: [{
				dataSpac: "RB",
				dataTags: "RIBEN",
				dataEnglish: "Japan",
				dataSzm: "JP",
				dataValue: "日本"
			}, {
				dataSpac: "RS",
				dataTags: "RUISHI",
				dataEnglish: "Switzerland",
				dataSzm: "CH",
				dataValue: "瑞士"
			}, {
				dataSpac: "RD",
				dataTags: "RUODIAN",
				dataEnglish: "Sweden",
				dataSzm: "SE",
				dataValue: "瑞典"
			}]
		}, {
			groupname: "S",
			citylist: [{
				dataSpac: "SJCHNWS",
				dataTags: "SHENGJICIHENIWEISI",
				dataEnglish: "Saint Kitts and Nevis",
				dataSzm: "KN",
				dataValue: "圣基茨和尼维斯"
			}, {
				dataSpac: "SEWY",
				dataTags: "SAIERWEIYA",
				dataEnglish: "SERBIA AND MONTENEGRO",
				dataSzm: "CS",
				dataValue: "塞尔维亚"
			}, {
				dataSpac: "SDD",
				dataTags: "SHENGDANDAO",
				dataEnglish: "Christmas Island",
				dataSzm: "CX",
				dataValue: "圣诞岛"
			}, {
				dataSpac: "SPLS",
				dataTags: "SAIPULUSI",
				dataEnglish: "Cyprus",
				dataSzm: "CY",
				dataValue: "塞浦路斯"
			}, {
				dataSpac: "SLXY",
				dataTags: "SHENGLUXIYA",
				dataEnglish: "Saint Lucia",
				dataSzm: "LC",
				dataValue: "圣卢西亚"
			}, {
				dataSpac: "SLLK",
				dataTags: "SILILANKA",
				dataEnglish: "Sri Lanka",
				dataSzm: "LK",
				dataValue: "斯里兰卡"
			}, {
				dataSpac: "SPAEHMKL",
				dataTags: "SHENGPIAIERHEMIKELONG",
				dataEnglish: "Saint Pierre and Miquelon",
				dataSzm: "PM",
				dataValue: "圣皮埃尔和密克隆"
			}, {
				dataSpac: "STALB",
				dataTags: "SHATEALABO",
				dataEnglish: "Saudi Arabia",
				dataSzm: "SA",
				dataValue: "沙特阿拉伯"
			}, {
				dataSpac: "SLMQD",
				dataTags: "SUOLUOMENQUNDAO",
				dataEnglish: "Solomon Islands",
				dataSzm: "SB",
				dataValue: "所罗门群岛"
			}, {
				dataSpac: "SSE",
				dataTags: "SAISHEER",
				dataEnglish: "Seychelles",
				dataSzm: "SC",
				dataValue: "塞舌尔"
			}, {
				dataSpac: "SD",
				dataTags: "SUDAN",
				dataEnglish: "Sudan",
				dataSzm: "SD",
				dataValue: "苏丹"
			}, {
				dataSpac: "SHLN",
				dataTags: "SHENGHELENA",
				dataEnglish: "Saint Helena",
				dataSzm: "SH",
				dataValue: "圣赫勒拿"
			}, {
				dataSpac: "SLWNY",
				dataTags: "SILUOWENNIYA",
				dataEnglish: "Slovenia",
				dataSzm: "SI",
				dataValue: "斯洛文尼亚"
			}, {
				dataSpac: "SWEBDHYMYD",
				dataTags: "SIWAERBADAOHEYANGMAYANDAO",
				dataEnglish: "Svalbard and Jan Mayen",
				dataSzm: "SJ",
				dataValue: "斯瓦尔巴岛和扬马延岛"
			}, {
				dataSpac: "SLFK",
				dataTags: "SILUOFAKE",
				dataEnglish: "Slovakia",
				dataSzm: "SK",
				dataValue: "斯洛伐克"
			}, {
				dataSpac: "SLLA",
				dataTags: "SAILALIANG",
				dataEnglish: "Sierra Leone",
				dataSzm: "SL",
				dataValue: "塞拉利昂"
			}, {
				dataSpac: "SMLN",
				dataTags: "SHENGMALINUO",
				dataEnglish: "San Marino",
				dataSzm: "SM",
				dataValue: "圣马力诺"
			}, {
				dataSpac: "SEJE",
				dataTags: "SAIERJIAER",
				dataEnglish: "Senegal",
				dataSzm: "SN",
				dataValue: "塞内加尔"
			}, {
				dataSpac: "SML",
				dataTags: "SUOMALI",
				dataEnglish: "Somalia",
				dataSzm: "SO",
				dataValue: "索马里"
			}, {
				dataSpac: "SLN",
				dataTags: "SULINAN",
				dataEnglish: "Suriname",
				dataSzm: "SR",
				dataValue: "苏里南"
			}, {
				dataSpac: "SDMHPLXB",
				dataTags: "SHENGDUOMEIHEPULINXIBI",
				dataEnglish: "Sao Tome and Principe",
				dataSzm: "ST",
				dataValue: "圣多美和普林西比"
			}, {
				dataSpac: "SEWD",
				dataTags: "SAERWADUO",
				dataEnglish: "El Salvador",
				dataSzm: "SV",
				dataValue: "萨尔瓦多"
			}, {
				dataSpac: "SWSL",
				dataTags: "SIWEISHILAN",
				dataEnglish: "Swaziland",
				dataSzm: "SZ",
				dataValue: "斯威士兰"
			}, {
				dataSpac: "SWSTHGLNDS",
				dataTags: "SHENGWENSENTEHEGELINNADINGSI",
				dataEnglish: "Saint Vincent and Grenadines",
				dataSzm: "VC",
				dataValue: "圣文森特和格林纳丁斯"
			}, {
				dataSpac: "SMY",
				dataTags: "SAMOYA",
				dataEnglish: "Samoa",
				dataSzm: "WS",
				dataValue: "萨摩亚"
			}]
		}, {
			groupname: "T",
			citylist: [{
				dataSpac: "TG",
				dataTags: "TAIGUO",
				dataEnglish: "Thailand",
				dataSzm: "TH",
				dataValue: "泰国"
			}, {
				dataSpac: "TKSHKKSQD",
				dataTags: "TEKESIHEKAIKESIQUNDAO",
				dataEnglish: "Turks and Caicos Islands",
				dataSzm: "TC",
				dataValue: "特克斯和凯科斯群岛"
			}, {
				dataSpac: "TKLST",
				dataTags: "TAJIKESITAN",
				dataEnglish: "Tajikistan",
				dataSzm: "TJ",
				dataValue: "塔吉克斯坦"
			}, {
				dataSpac: "TKL",
				dataTags: "TUOKELAO",
				dataEnglish: "Tokelau",
				dataSzm: "TK",
				dataValue: "托克劳"
			}, {
				dataSpac: "TKMST",
				dataTags: "TUKUMANSITAN",
				dataEnglish: "Turkmenstan",
				dataSzm: "TM",
				dataValue: "土库曼斯坦"
			}, {
				dataSpac: "TNS",
				dataTags: "TUNISI",
				dataEnglish: "Tunisia",
				dataSzm: "TN",
				dataValue: "突尼斯"
			}, {
				dataSpac: "TJ",
				dataTags: "TANGJIA",
				dataEnglish: "Tonga",
				dataSzm: "TO",
				dataValue: "汤加"
			}, {
				dataSpac: "TEQ",
				dataTags: "TUERQI",
				dataEnglish: "Turkey",
				dataSzm: "TR",
				dataValue: "土耳其"
			}, {
				dataSpac: "TLNDHDBG",
				dataTags: "TELINIDAHEDUOBAGE",
				dataEnglish: "Trinidad and Tobago",
				dataSzm: "TT",
				dataValue: "特立尼达和多巴哥"
			}, {
				dataSpac: "TWL",
				dataTags: "TUWALU",
				dataEnglish: "Tuvalu",
				dataSzm: "TV",
				dataValue: "图瓦卢"
			}, {
				dataSpac: "TSNY",
				dataTags: "TANSANGNIYA",
				dataEnglish: "Tanzania",
				dataSzm: "TZ",
				dataValue: "坦桑尼亚"
			}]
		}, {
			groupname: "W",
			citylist: [{
				dataSpac: "WKL",
				dataTags: "WUKELAN",
				dataEnglish: "Ukraine",
				dataSzm: "UA",
				dataValue: "乌克兰"
			}, {
				dataSpac: "WL",
				dataTags: "WENLAI",
				dataEnglish: "Brunei",
				dataSzm: "BN",
				dataValue: "文莱"
			}, {
				dataSpac: "WDML",
				dataTags: "WEIDIMALA",
				dataEnglish: "Guatemala",
				dataSzm: "GT",
				dataValue: "危地马拉"
			}, {
				dataSpac: "WGD",
				dataTags: "WUGANDA",
				dataEnglish: "Uganda",
				dataSzm: "UG",
				dataValue: "乌干达"
			}, {
				dataSpac: "WLG",
				dataTags: "WULAGUI",
				dataEnglish: "Uruguay",
				dataSzm: "UY",
				dataValue: "乌拉圭"
			}, {
				dataSpac: "WZBKST",
				dataTags: "WUZIBIEKESITAN",
				dataEnglish: "Uzbekistan",
				dataSzm: "UZ",
				dataValue: "乌兹别克斯坦"
			}, {
				dataSpac: "WNRL",
				dataTags: "WEINEIRUILA",
				dataEnglish: "Venezuela",
				dataSzm: "VE",
				dataValue: "委内瑞拉"
			}, {
				dataSpac: "WNAT",
				dataTags: "WANUATU",
				dataEnglish: "Vanuatu",
				dataSzm: "VU",
				dataValue: "瓦努阿图"
			}, {
				dataSpac: "WLSHFTN",
				dataTags: "WALISIHEFUTUNA",
				dataEnglish: "Wallis and Futuna",
				dataSzm: "WF",
				dataValue: "瓦利斯和富图纳"
			}]
		}, {
			groupname: "X",
			citylist: [{
				dataSpac: "XBY",
				dataTags: "XIBANYA",
				dataEnglish: "Spain",
				dataSzm: "ES",
				dataValue: "西班牙"
			}, {
				dataSpac: "XJP",
				dataTags: "XINJIAPO",
				dataEnglish: "Singapore",
				dataSzm: "SG",
				dataValue: "新加坡"
			}, {
				dataSpac: "XSHL",
				dataTags: "XISAHALA",
				dataEnglish: "Western Sahara",
				dataSzm: "EH",
				dataValue: "西撒哈拉"
			}, {
				dataSpac: "XL",
				dataTags: "XILA",
				dataEnglish: "Greece",
				dataSzm: "GR",
				dataValue: "希腊"
			}, {
				dataSpac: "XYL",
				dataTags: "XIONGYALI",
				dataEnglish: "Hungary",
				dataSzm: "HU",
				dataValue: "匈牙利"
			}, {
				dataSpac: "XKLDNY",
				dataTags: "XINKALIDUONIYA",
				dataEnglish: "New Caledonia",
				dataSzm: "NC",
				dataValue: "新喀里多尼亚"
			}, {
				dataSpac: "XXL",
				dataTags: "XINXILAN",
				dataEnglish: "New Zealand",
				dataSzm: "NZ",
				dataValue: "新西兰"
			}, {
				dataSpac: "XLY",
				dataTags: "XULIYA",
				dataEnglish: "Syria",
				dataSzm: "SY",
				dataValue: "叙利亚"
			}]
		}, {
			groupname: "Y",
			citylist: [{
				dataSpac: "YG",
				dataTags: "YINGGUO",
				dataEnglish: "United Kingdom",
				dataSzm: "GB",
				dataValue: "英国"
			}, {
				dataSpac: "YDL",
				dataTags: "YIDALI",
				dataEnglish: "Italy",
				dataSzm: "IT",
				dataValue: "意大利"
			}, {
				dataSpac: "YN",
				dataTags: "YUENAN",
				dataEnglish: "Viet Nam",
				dataSzm: "VN",
				dataValue: "越南"
			}, {
				dataSpac: "YD",
				dataTags: "YINDU",
				dataEnglish: "India",
				dataSzm: "IN",
				dataValue: "印度"
			}, {
				dataSpac: "YMNY",
				dataTags: "YAMEINIYA",
				dataEnglish: "Armenia",
				dataSzm: "AM",
				dataValue: "亚美尼亚"
			}, {
				dataSpac: "YDNXY",
				dataTags: "YINDUNIXIYA",
				dataEnglish: "Indonesia",
				dataSzm: "ID",
				dataValue: "印度尼西亚"
			}, {
				dataSpac: "YSL",
				dataTags: "YISELIE",
				dataEnglish: "Israel",
				dataSzm: "IL",
				dataValue: "以色列"
			}, {
				dataSpac: "YSYDYLD",
				dataTags: "YINGSHUYINDUYANGLIGNDI",
				dataEnglish: "British Indian Ocean Territory",
				dataSzm: "IO",
				dataValue: "英属印度洋领地"
			}, {
				dataSpac: "YLK",
				dataTags: "YILAKE",
				dataEnglish: "Iraq",
				dataSzm: "IQ",
				dataValue: "伊拉克"
			}, {
				dataSpac: "YL",
				dataTags: "YILANG",
				dataEnglish: "Iran",
				dataSzm: "IR",
				dataValue: "伊朗"
			}, {
				dataSpac: "YMJ",
				dataTags: "YAMAIJAI",
				dataEnglish: "Jamaica",
				dataSzm: "JM",
				dataValue: "牙买加"
			}, {
				dataSpac: "YT",
				dataTags: "YUETAN",
				dataEnglish: "Jordan",
				dataSzm: "JO",
				dataValue: "约旦"
			}, {
				dataSpac: "YM",
				dataTags: "YEMEN",
				dataEnglish: "Yemen",
				dataSzm: "YE",
				dataValue: "也门"
			}]
		}, {
			groupname: "Z",
			citylist: [{
				dataSpac: "ZGDL",
				dataTags: "ZHONGGUODALU",
				dataEnglish: "China",
				dataSzm: "CN",
				dataValue: "中国大陆"
			}, {
				dataSpac: "ZGXG",
				dataTags: "ZHONGGUOXIANGGANG",
				dataEnglish: "HongKong",
				dataSzm: "HK",
				dataValue: "中国香港"
			}, {
				dataSpac: "ZGTW",
				dataTags: "ZHONGGUOTAIWAN",
				dataEnglish: "Taiwan",
				dataSzm: "TW",
				dataValue: "中国台湾"
			}, {
				dataSpac: "ZGAM",
				dataTags: "ZHONGGUOAOMEN",
				dataEnglish: "Macau",
				dataSzm: "MO",
				dataValue: "中国澳门"
			}, {
				dataSpac: "ZF",
				dataTags: "ZHONGFEI",
				dataEnglish: "Central Africa Republic",
				dataSzm: "CF",
				dataValue: "中非"
			}, {
				dataSpac: "ZL",
				dataTags: "ZHILI",
				dataEnglish: "Chile",
				dataSzm: "CL",
				dataValue: "智利"
			}, {
				dataSpac: "ZBLT",
				dataTags: "ZHIBULUOTUO",
				dataEnglish: "Gibraltar",
				dataSzm: "GI",
				dataValue: "直布罗陀"
			}, {
				dataSpac: "ZD",
				dataTags: "ZHADE",
				dataEnglish: "Chad",
				dataSzm: "TD",
				dataValue: "乍得"
			}, {
				dataSpac: "ZBY",
				dataTags: "ZANBIYA",
				dataEnglish: "Zambia",
				dataSzm: "ZM",
				dataValue: "赞比亚"
			}]
		}],
		hotList: [{
			dataSpac: "ZGDL",
			dataValue: "中国大陆",
			dataSzm: "CN",
			dataEnglish: "CHINA",
			dataTags: "ZHONGGUODALU"
		}, {
			dataSpac: "ZGXG",
			dataValue: "中国香港",
			dataSzm: "HK",
			dataEnglish: "HONGKONG",
			dataTags: "ZHONGGUOXIANGGANG"
		}, {
			dataSpac: "ZGTW",
			dataValue: "中国台湾",
			dataSzm: "TW",
			dataEnglish: "TAIWAN",
			dataTags: "ZHONGGUOTAIWAN"
		}, {
			dataSpac: "ZGAM",
			dataValue: "中国澳门",
			dataSzm: "MO",
			dataEnglish: "MACAU",
			dataTags: "ZHONGGUOAOMEN"
		}, {
			dataSpac: "MG",
			dataValue: "美国",
			dataSzm: "US",
			dataEnglish: "UNITED STATES",
			dataTags: "MEIGUO"
		}, {
			dataSpac: "JND",
			dataValue: "加拿大",
			dataSzm: "CA",
			dataEnglish: "CANADA",
			dataTags: "JIANADA"
		}, {
			dataSpac: "YG",
			dataValue: "英国",
			dataSzm: "GB",
			dataEnglish: "UNITED KINGDOM",
			dataTags: "YINGGUO"
		}, {
			dataSpac: "FG",
			dataValue: "法国",
			dataSzm: "FR",
			dataEnglish: "FRANCE",
			dataTags: "FAGUO"
		}, {
			dataSpac: "RB",
			dataValue: "日本",
			dataSzm: "JP",
			dataEnglish: "JAPAN",
			dataTags: "RIBEN"
		}, {
			dataSpac: "DG",
			dataValue: "德国",
			dataSzm: "DE",
			dataEnglish: "GERMANY",
			dataTags: "DEGUO"
		}, {
			dataSpac: "HG",
			dataValue: "韩国",
			dataSzm: "KR",
			dataEnglish: "KOREA,REPUBLIC OF",
			dataTags: "HANGUO"
		}, {
			dataSpac: "ADLY",
			dataValue: "澳大利亚",
			dataSzm: "AU",
			dataEnglish: "AUSTRALIA",
			dataTags: "AODALIYA"
		}]
	}
