internationalDataCityJson = {
	list: [{
		groupname: "A",
		citylist: [{
			dataSpac: "AM",
			dataValue: "澳门",
			dataSzm: "MFM",
			dataTags: "AOMEN",
			dataType: 1
		}, {
			dataSpac: "AKL",
			dataValue: "奥克兰",
			dataSzm: "AKL",
			dataTags: "AOKELAN",
			dataType: 1
		}, {
			dataSpac: "ALD",
			dataValue: "奥兰多",
			dataSzm: "ORL",
			dataTags: "AOLANDUO",
			dataType: 1
		}, {
			dataSpac: "ADMD",
			dataValue: "埃德蒙顿",
			dataSzm: "YEA",
			dataTags: "AIDEMENGDUN",
			dataType: 1
		}, {
			dataSpac: "AMSTD",
			dataValue: "阿姆斯特丹",
			dataSzm: "AMS",
			dataTags: "AMUSITEDAN",
			dataType: 1
		}, {
			dataSpac: "ADB",
			dataValue: "爱丁堡",
			dataSzm: "EDI",
			dataTags: "AIDINGBAO",
			dataType: 1
		}, {
			dataSpac: "AKL",
			dataValue: "阿克拉",
			dataSzm: "ACC",
			dataTags: "AKELA",
			dataType: 1
		}, {
			dataSpac: "AEJE",
			dataValue: "阿尔及尔",
			dataSzm: "ALG",
			dataTags: "AERJIER",
			dataType: 1
		}, {
			dataSpac: "ABJ",
			dataValue: "阿布贾",
			dataSzm: "ABV",
			dataTags: "ABUJIA",
			dataType: 1
		}, {
			dataSpac: "ALJP",
			dataValue: "阿雷基帕",
			dataSzm: "AQP",
			dataTags: "ALEIJIPA",
			dataType: 1
		}]
	}, {
		groupname: "B",
		citylist: [{
			dataSpac: "BJ",
			dataValue: "北京",
			dataSzm: "BJS",
			dataTags: "BEIJING",
			dataType: 1
		}, {
			dataSpac: "BL",
			dataValue: "巴黎",
			dataSzm: "PAR",
			dataTags: "BALI",
			dataType: 1
		}, {
			dataSpac: "BLD",
			dataValue: "巴厘岛",
			dataSzm: "DPS",
			dataTags: "BALIDAO",
			dataType: 1
		}, {
			dataSpac: "BLSB",
			dataValue: "布里斯班",
			dataSzm: "BNE",
			dataTags: "BULISIBAN",
			dataType: 1
		}, {
			dataSpac: "BC",
			dataValue: "槟城",
			dataSzm: "PEN",
			dataTags: "BINCHENG",
			dataType: 1
		}, {
			dataSpac: "BSD",
			dataValue: "波士顿",
			dataSzm: "BOS",
			dataTags: "BOSHIDUN",
			dataType: 1
		}, {
			dataSpac: "BYNSALS",
			dataValue: "布宜诺斯艾利斯",
			dataSzm: "BUE",
			dataTags: "BUYINUOSIAILISI",
			dataType: 1
		}, {
			dataSpac: "BL",
			dataValue: "柏林",
			dataSzm: "BER",
			dataTags: "BOLIN",
			dataType: 1
		}, {
			dataSpac: "BMH",
			dataValue: "伯明翰",
			dataSzm: "BHX",
			dataTags: "BOMINGHAN",
			dataType: 1
		}, {
			dataSpac: "BSLN",
			dataValue: "巴塞罗那",
			dataSzm: "BCN",
			dataTags: "BASAILUONA",
			dataType: 1
		}, {
			dataSpac: "BLSE",
			dataValue: "布鲁塞尔",
			dataSzm: "BRU",
			dataTags: "BULUSAIER",
			dataType: 1
		}, {
			dataSpac: "BLG",
			dataValue: "布拉格",
			dataSzm: "PRG",
			dataTags: "BULAGE",
			dataType: 1
		}, {
			dataSpac: "BDPS",
			dataValue: "布达佩斯",
			dataSzm: "BUD",
			dataTags: "BUDAPEISI",
			dataType: 1
		}]
	}, {
		groupname: "C",
		citylist: [{
			dataSpac: "DC",
			dataValue: "成都",
			dataSzm: "CTU",
			dataTags: "CHENGDU",
			dataType: 1
		}, {
			dataSpac: "CQ",
			dataValue: "重庆",
			dataSzm: "CKG",
			dataTags: "CHONGQING",
			dataType: 1
		}, {
			dataSpac: "CS",
			dataValue: "长沙",
			dataSzm: "CSX",
			dataTags: "CHANGSHA",
			dataType: 1
		}, {
			dataSpac: "CC",
			dataValue: "长春",
			dataSzm: "CGQ",
			dataTags: "CHANGCHUN",
			dataType: 1
		}]
	}, {
		groupname: "D",
		citylist: [{
			dataSpac: "DL",
			dataValue: "大连",
			dataSzm: "DLC",
			dataTags: "DALIAN",
			dataType: 1
		}, {
			dataSpac: "DJ",
			dataValue: "东京",
			dataSzm: "TYO",
			dataTags: "DONGJING",
			dataType: 1
		}, {
			dataSpac: "DB",
			dataValue: "大阪",
			dataSzm: "OSA",
			dataTags: "DABAN",
			dataType: 1
		}, {
			dataSpac: "DLD",
			dataValue: "多伦多",
			dataSzm: "YTO",
			dataTags: "DUOLUNDUO",
			dataType: 1
		}, {
			dataSpac: "DB",
			dataValue: "迪拜",
			dataSzm: "DXB",
			dataTags: "DIBAI",
			dataType: 1
		}, {
			dataSpac: "DTL",
			dataValue: "底特律",
			dataSzm: "DTT",
			dataTags: "DITELV",
			dataType: 1
		}, {
			dataSpac: "DLS",
			dataValue: "达拉斯",
			dataSzm: "DFW",
			dataTags: "DALASI",
			dataType: 1
		}, {
			dataSpac: "DF",
			dataValue: "丹佛",
			dataSzm: "DEN",
			dataTags: "DANFO",
			dataType: 1
		}, {
			dataSpac: "DBL",
			dataValue: "都柏林",
			dataSzm: "DUB",
			dataTags: "DUBOLIN",
			dataType: 1
		}, {
			dataSpac: "DSEDF",
			dataValue: "杜塞尔多夫",
			dataSzm: "DUS",
			dataTags: "DUSAIERDUOFU",
			dataType: 1
		}, {
			dataSpac: "DLSSLM",
			dataValue: "达累斯萨拉姆",
			dataSzm: "DAR",
			dataTags: "DALEISISALAMU",
			dataType: 1
		}, {
			dataSpac: "DLBL",
			dataValue: "的黎波里",
			dataSzm: "TIP",
			dataTags: "DELIBOLI",
			dataType: 1
		}, {
			dataSpac: "DHL",
			dataValue: "德黑兰",
			dataSzm: "THR",
			dataTags: "DEHEILAN",
			dataType: 1
		}]
	}, {
		groupname: "F",
		citylist: [{
			dataSpac: "FZ",
			dataValue: "福州",
			dataSzm: "FOC",
			dataTags: "FUZHOU",
			dataType: 1
		}, {
			dataSpac: "FS",
			dataValue: "釜山",
			dataSzm: "PUS",
			dataTags: "FUSHAN",
			dataType: 1
		}, {
			dataSpac: "FG",
			dataValue: "福冈",
			dataSzm: "FUK",
			dataTags: "FUGANG",
			dataType: 1
		}, {
			dataSpac: "FLKF",
			dataValue: "法兰克福",
			dataSzm: "FRA",
			dataTags: "FALANKEFU",
			dataType: 1
		}, {
			dataSpac: "FC",
			dataValue: "费城",
			dataSzm: "PHI",
			dataTags: "FEICHENG",
			dataType: 1
		}, {
			dataSpac: "FHC",
			dataValue: "凤凰城",
			dataSzm: "PHX",
			dataTags: "FENGHUANGCHENG",
			dataType: 1
		}]
	}, {
		groupname: "G",
		citylist: [{
			dataSpac: "GZ",
			dataValue: "广州",
			dataSzm: "CAN",
			dataTags: "GUANGZHOU",
			dataType: 1
		}, {
			dataSpac: "GY",
			dataValue: "贵阳",
			dataSzm: "KWE",
			dataTags: "GUIYANG",
			dataType: 1
		}, {
			dataSpac: "GX",
			dataValue: "高雄",
			dataSzm: "KHH",
			dataTags: "GAOXIONG",
			dataType: 1
		}, {
			dataSpac: "GBHG",
			dataValue: "哥本哈根",
			dataSzm: "CPH",
			dataTags: "GEBENHAGEN",
			dataType: 1
		}, {
			dataSpac: "GLSG",
			dataValue: "格拉斯哥",
			dataSzm: "GLA",
			dataTags: "GELASIGE",
			dataType: 1
		}, {
			dataSpac: "GLC",
			dataValue: "格拉茨",
			dataSzm: "GRZ",
			dataTags: "GELACI",
			dataType: 1
		}]
	}, {
		groupname: "H",
		citylist: [{
			dataSpac: "HZ",
			dataValue: "杭州",
			dataSzm: "HGH",
			dataTags: "HANGZHOU",
			dataType: 1
		}, {
			dataSpac: "HK",
			dataValue: "海口",
			dataSzm: "HAK",
			dataTags: "HAIKOU",
			dataType: 1
		}, {
			dataSpac: "HEB",
			dataValue: "哈尔滨",
			dataSzm: "HRB",
			dataTags: "HAERBIN",
			dataType: 1
		}, {
			dataSpac: "HZMS",
			dataValue: "胡志明市",
			dataSzm: "SGN",
			dataTags: "HUZHIMINGSHI",
			dataType: 1
		}, {
			dataSpac: "HN",
			dataValue: "河内",
			dataSzm: "HAN",
			dataTags: "HENEI",
			dataType: 1
		}, {
			dataSpac: "HSD",
			dataValue: "华盛顿",
			dataSzm: "WAS",
			dataTags: "HUASHENGDUN",
			dataType: 1
		}, {
			dataSpac: "HNLL",
			dataValue: "火奴鲁鲁",
			dataSzm: "HNL",
			dataTags: "HUONULULU",
			dataType: 1
		}, {
			dataSpac: "HEXJ",
			dataValue: "赫尔辛基",
			dataSzm: "HEL",
			dataTags: "HEERXINJI",
			dataType: 1
		}, {
			dataSpac: "HB",
			dataValue: "汉堡",
			dataSzm: "HAM",
			dataTags: "HANBAO",
			dataType: 1
		}]
	}, {
		groupname: "J",
		citylist: [{
			dataSpac: "JN",
			dataValue: "济南",
			dataSzm: "TNA",
			dataTags: "JINAN",
			dataType: 1
		}, {
			dataSpac: "JLP",
			dataValue: "吉隆坡",
			dataSzm: "KUL",
			dataTags: "JILONGPO",
			dataType: 1
		}, {
			dataSpac: "JZD",
			dataValue: "济州岛",
			dataSzm: "CJU",
			dataTags: "JIZHOUDAO",
			dataType: 1
		}, {
			dataSpac: "JJS",
			dataValue: "旧金山",
			dataSzm: "SFO",
			dataTags: "JIUJINSHAN",
			dataType: 1
		}, {
			dataSpac: "JDMD",
			dataValue: "加德满都",
			dataSzm: "KTM",
			dataTags: "JIADEMANDU",
			dataType: 1
		}, {
			dataSpac: "JB",
			dataValue: "金边",
			dataSzm: "PNH",
			dataTags: "JINBIAN",
			dataType: 1
		}, {
			dataSpac: "JF",
			dataValue: "基辅",
			dataSzm: "IEV",
			dataTags: "JIFU",
			dataType: 1
		}, {
			dataSpac: "JSS",
			dataValue: "金沙萨",
			dataSzm: "FIH",
			dataTags: "JINSHASHA",
			dataType: 1
		}]
	}, {
		groupname: "K",
		citylist: [{
			dataSpac: "KM",
			dataValue: "昆明",
			dataSzm: "KMG",
			dataTags: "KUNMING",
			dataType: 1
		}, {
			dataSpac: "KEJL",
			dataValue: "卡尔加里",
			dataSzm: "YYC",
			dataTags: "KAERJIALI",
			dataType: 1
		}, {
			dataSpac: "KL",
			dataValue: "开罗",
			dataSzm: "CAI",
			dataTags: "KAILUO",
			dataType: 1
		}, {
			dataSpac: "KPD",
			dataValue: "开普敦",
			dataSzm: "CPT",
			dataTags: "KAIPUDUN",
			dataType: 1
		}, {
			dataSpac: "KTM",
			dataValue: "喀土穆",
			dataSzm: "KRT",
			dataTags: "KATUMU",
			dataType: 1
		}, {
			dataSpac: "KSBLK",
			dataValue: "卡萨布兰卡",
			dataSzm: "CAS",
			dataTags: "KASABULANKA",
			dataType: 1
		}]
	}, {
		groupname: "L",
		citylist: [{
			dataSpac: "LJ",
			dataValue: "丽江",
			dataSzm: "LJG",
			dataTags: "LIJIANG",
			dataType: 1
		}, {
			dataSpac: "LSJ",
			dataValue: "洛杉矶",
			dataSzm: "LAX",
			dataTags: "LUOSHANJI",
			dataType: 1
		}, {
			dataSpac: "LD",
			dataValue: "伦敦",
			dataSzm: "LON",
			dataTags: "LUNDUN",
			dataType: 1
		}, {
			dataSpac: "LSWJS",
			dataValue: "拉斯维加斯",
			dataSzm: "LAS",
			dataTags: "LASIWEIJIASI",
			dataType: 1
		}, {
			dataSpac: "LYRNL",
			dataValue: "里约热内卢",
			dataSzm: "RIO",
			dataTags: "LIYUERENEILU",
			dataType: 1
		}, {
			dataSpac: "LM",
			dataValue: "罗马",
			dataSzm: "ROM",
			dataTags: "LUOMA",
			dataType: 1
		}, {
			dataSpac: "LGS",
			dataValue: "拉各斯",
			dataSzm: "LOS",
			dataTags: "LAGESI",
			dataType: 1
		}, {
			dataSpac: "LM",
			dataValue: "利马",
			dataSzm: "LIM",
			dataTags: "LIMA",
			dataType: 1
		}]
	}, {
		groupname: "M",
		citylist: [{
			dataSpac: "MGW",
			dataValue: "名古屋",
			dataSzm: "NGO",
			dataTags: "MINGGUWU",
			dataType: 1
		}, {
			dataSpac: "MG",
			dataValue: "曼谷",
			dataSzm: "BKK",
			dataTags: "MANGU",
			dataType: 1
		}, {
			dataSpac: "MEB",
			dataValue: "墨尔本",
			dataSzm: "MEL",
			dataTags: "MOERBEN",
			dataType: 1
		}, {
			dataSpac: "MNL",
			dataValue: "马尼拉",
			dataSzm: "MNL",
			dataTags: "MANILA",
			dataType: 1
		}, {
			dataSpac: "ML",
			dataValue: "马累",
			dataSzm: "MLE",
			dataTags: "MALEI",
			dataType: 1
		}, {
			dataSpac: "MTLE",
			dataValue: "蒙特利尔",
			dataSzm: "YMQ",
			dataTags: "MENGTELIER",
			dataType: 1
		}, {
			dataSpac: "MNABLS",
			dataValue: "明尼阿波利斯",
			dataSzm: "MSP",
			dataTags: "MINGNIABOLISI",
			dataType: 1
		}, {
			dataSpac: "MXGC",
			dataValue: "墨西哥城",
			dataSzm: "MEX",
			dataTags: "MOXIGECHENG",
			dataType: 1
		}, {
			dataSpac: "MAM",
			dataValue: "迈阿密",
			dataSzm: "MIA",
			dataTags: "MAIAMI",
			dataType: 1
		}, {
			dataSpac: "MSK",
			dataValue: "莫斯科",
			dataSzm: "MOS",
			dataTags: "MOSIKE",
			dataType: 1
		}, {
			dataSpac: "ML",
			dataValue: "米兰",
			dataSzm: "MIL",
			dataTags: "MILAN",
			dataType: 1
		}, {
			dataSpac: "MDL",
			dataValue: "马德里",
			dataSzm: "MAD",
			dataTags: "MADELI",
			dataType: 1
		}, {
			dataSpac: "MNH",
			dataValue: "慕尼黑",
			dataSzm: "MUC",
			dataTags: "MUNIHEI",
			dataType: 1
		}, {
			dataSpac: "MLQS",
			dataValue: "毛里求斯",
			dataSzm: "MRU",
			dataTags: "MAOLIQIUSI",
			dataType: 1
		}]
	}, {
		groupname: "N",
		citylist: [{
			dataSpac: "NJ",
			dataValue: "南京",
			dataSzm: "NKG",
			dataTags: "NANJING",
			dataType: 1
		}, {
			dataSpac: "NN",
			dataValue: "南宁",
			dataSzm: "NNG",
			dataTags: "NANNING",
			dataType: 1
		}, {
			dataSpac: "NC",
			dataValue: "南昌",
			dataSzm: "KHN",
			dataTags: "NANCHANG",
			dataType: 1
		}, {
			dataSpac: "NY",
			dataValue: "纽约",
			dataSzm: "NYC",
			dataTags: "NIUYUE",
			dataType: 1
		}, {
			dataSpac: "NLB",
			dataValue: "内罗毕",
			dataSzm: "NBO",
			dataTags: "NEILUOBI",
			dataType: 1
		}]
	}, {
		groupname: "P",
		citylist: [{
			dataSpac: "PJ",
			dataValue: "普吉",
			dataSzm: "HKT",
			dataTags: "PUJI",
			dataType: 1
		}, {
			dataSpac: "PZB",
			dataValue: "匹兹堡",
			dataSzm: "PIT",
			dataTags: "PIZIBAO",
			dataType: 1
		}]
	}, {
		groupname: "Q",
		citylist: [{
			dataSpac: "QD",
			dataValue: "青岛",
			dataSzm: "TAO",
			dataTags: "QINGDAO",
			dataType: 1
		}, {
			dataSpac: "QH",
			dataValue: "清化",
			dataSzm: "THD",
			dataTags: "QINGHUA",
			dataType: 1
		}]
	}, {
		groupname: "R",
		citylist: [{
			dataSpac: "RNW",
			dataValue: "日内瓦",
			dataSzm: "GVA",
			dataTags: "RINEIWA",
			dataType: 1
		}]
	}, {
		groupname: "S",
		citylist: [{
			dataSpac: "SH",
			dataValue: "上海",
			dataSzm: "SHA",
			dataTags: "SHANGHAI",
			dataType: 1
		}, {
			dataSpac: "SZ",
			dataValue: "深圳",
			dataSzm: "SZX",
			dataTags: "SHENZHEN",
			dataType: 1
		}, {
			dataSpac: "SY",
			dataValue: "沈阳",
			dataSzm: "SHE",
			dataTags: "SHENYANG",
			dataType: 1
		}, {
			dataSpac: "SY",
			dataValue: "三亚",
			dataSzm: "SYX",
			dataTags: "SANYA",
			dataType: 1
		}, {
			dataSpac: "SE",
			dataValue: "首尔",
			dataSzm: "SEL",
			dataTags: "SHOUER",
			dataType: 1
		}, {
			dataSpac: "SBL",
			dataValue: "圣保罗",
			dataSzm: "SAO",
			dataTags: "SHENGBAOLUO",
			dataType: 1
		}, {
			dataSpac: "SDGEM",
			dataValue: "斯德哥尔摩",
			dataSzm: "STO",
			dataTags: "SIDEGEERMO",
			dataType: 1
		}, {
			dataSpac: "SLS",
			dataValue: "苏黎世",
			dataSzm: "ZRH",
			dataTags: "SULISHI",
			dataType: 1
		}, {
			dataSpac: "SBDB",
			dataValue: "圣彼得堡",
			dataSzm: "LED",
			dataTags: "SHENGBIDEBAO",
			dataType: 1
		}, {
			dataSpac: "SSE",
			dataValue: "塞舌尔",
			dataSzm: "SEZ",
			dataTags: "SAISHEER",
			dataType: 1
		}]
	}, {
		groupname: "T",
		citylist: [{
			dataSpac: "TJ",
			dataValue: "天津",
			dataSzm: "TSN",
			dataTags: "TIANJIN",
			dataType: 1
		}, {
			dataSpac: "TY",
			dataValue: "太原",
			dataSzm: "TYN",
			dataTags: "TAIYUAN",
			dataType: 1
		}, {
			dataSpac: "TB",
			dataValue: "台北",
			dataSzm: "TPE",
			dataTags: "TAIBEI",
			dataType: 1
		}, {
			dataSpac: "TNS",
			dataValue: "突尼斯",
			dataSzm: "TUN",
			dataTags: "TUNISI",
			dataType: 1
		}]
	}, {
		groupname: "W",
		citylist: [{
			dataSpac: "WLMQ",
			dataValue: "乌鲁木齐",
			dataSzm: "URC",
			dataTags: "WULUMUQI",
			dataType: 1
		}, {
			dataSpac: "WH",
			dataValue: "武汉",
			dataSzm: "WUH",
			dataTags: "WUHAN",
			dataType: 1
		}, {
			dataSpac: "WGH",
			dataValue: "温哥华",
			dataSzm: "YVR",
			dataTags: "WENGEHUA",
			dataType: 1
		}, {
			dataSpac: "WTH",
			dataValue: "渥太华",
			dataSzm: "YOW",
			dataTags: "WOTAIHUA",
			dataType: 1
		}, {
			dataSpac: "WYN",
			dataValue: "维也纳",
			dataSzm: "VIE",
			dataTags: "WEIYENA",
			dataType: 1
		}]
	}, {
		groupname: "X",
		citylist: [{
			dataSpac: "XA",
			dataValue: "西安",
			dataSzm: "SIA",
			dataTags: "XIAN",
			dataType: 1
		}, {
			dataSpac: "XM",
			dataValue: "厦门",
			dataSzm: "XMN",
			dataTags: "XIAMEN",
			dataType: 1
		}, {
			dataSpac: "XG",
			dataValue: "香港",
			dataSzm: "HKG",
			dataTags: "XIANGGANG",
			dataType: 1
		}, {
			dataSpac: "XJP",
			dataValue: "新加坡",
			dataSzm: "SIN",
			dataTags: "XINJIAPO",
			dataType: 1
		}, {
			dataSpac: "XN",
			dataValue: "悉尼",
			dataSzm: "SYD",
			dataTags: "XINI",
			dataType: 1
		}, {
			dataSpac: "XWY",
			dataValue: "夏威夷",
			dataSzm: "FUK",
			dataTags: "XIAWEIYI",
			dataType: 1
		}, {
			dataSpac: "XL",
			dataValue: "暹粒",
			dataSzm: "REP",
			dataTags: "XIANLI",
			dataType: 1
		}, {
			dataSpac: "XDL",
			dataValue: "新德里",
			dataSzm: "DEL",
			dataTags: "XINDELI",
			dataType: 1
		}, {
			dataSpac: "XYT",
			dataValue: "西雅图",
			dataSzm: "SEA",
			dataTags: "XIYATU",
			dataType: 1
		}, {
			dataSpac: "XSD",
			dataValue: "休斯敦",
			dataSzm: "HOU",
			dataTags: "XIUSIDUN",
			dataType: 1
		}]
	}, {
		groupname: "Y",
		citylist: [{
			dataSpac: "YJD",
			dataValue: "雅加达",
			dataSzm: "JKT",
			dataTags: "YAJIADA",
			dataType: 1
		}, {
			dataSpac: "YTLD",
			dataValue: "亚特兰大",
			dataSzm: "ATL",
			dataTags: "YATELANDA",
			dataType: 1
		}, {
			dataSpac: "YSTBE",
			dataValue: "伊斯坦布尔",
			dataSzm: "IST",
			dataTags: "YISITANBUER",
			dataType: 1
		}, {
			dataSpac: "YD",
			dataValue: "雅典",
			dataSzm: "ATH",
			dataTags: "YADIAN",
			dataType: 1
		}, {
			dataSpac: "YHNSB",
			dataValue: "约翰内斯堡",
			dataSzm: "JNB",
			dataTags: "YUEHANNEISIBAO",
			dataType: 1
		}, {
			dataSpac: "YDSYBB",
			dataValue: "亚的斯亚贝巴",
			dataSzm: "ADD",
			dataTags: "YADESIYABEIBA",
			dataType: 1
		}]
	}, {
		groupname: "Z",
		citylist: [{
			dataSpac: "ZZ",
			dataValue: "郑州",
			dataSzm: "CGO",
			dataTags: "ZHENGZHOU",
			dataType: 1
		}, {
			dataSpac: "ZJG",
			dataValue: "芝加哥",
			dataSzm: "CHI",
			dataTags: "ZHIJIAGE",
			dataType: 1
		}]
	}],
	hotList: [{
		dataValue: "北京",
		dataSpac: "BJ",
		dataSzm: "BJS",
		dataTags: "BEIJING"
	}, {
		dataValue: "长春",
		dataSpac: "CC",
		dataSzm: "CGQ",
		dataTags: "CHANGCHUN"
	}, {
		dataValue: "上海",
		dataSpac: "SH",
		dataSzm: "SHA",
		dataTags: "SHANGHAI"
	}, {
		dataValue: "法兰克福",
		dataSpac: "FLKF",
		dataSzm: "FRA",
		dataTags: "FALANKEFU"
	}, {
		dataValue: "广州",
		dataSpac: "GZ",
		dataSzm: "CAN",
		dataTags: "GUANGZHOU"
	}, {
		dataValue: "香港",
		dataSpac: "XG",
		dataSzm: "HKG",
		dataTags: "XIANGGANG"
	}, {
		dataValue: "迪拜",
		dataSpac: "DB",
		dataSzm: "DXB",
		dataTags: "DIBAI"
	}, {
		dataValue: "名古屋",
		dataSpac: "MGW",
		dataSzm: "NGO",
		dataTags: "MINGGUWU"
	}, {
		dataValue: "曼谷",
		dataSpac: "MG",
		dataSzm: "BKK",
		dataTags: "MANGU"
	}, {
		dataValue: "莫斯科",
		dataSpac: "MSK",
		dataSzm: "MOS",
		dataTags: "MOSIKE"
	}, {
		dataValue: "慕尼黑",
		dataSpac: "MNH",
		dataSzm: "MUC",
		dataTags: "MUNIHEI"
	}, {
		dataValue: "巴黎",
		dataSpac: "BL",
		dataSzm: "PAR",
		dataTags: "BALI"
	}, {
		dataValue: "东京",
		dataSpac: "DJ",
		dataSzm: "TYO",
		dataTags: "DONGJING"
	}, {
		dataValue: "台北",
		dataSpac: "TB",
		dataSzm: "TPE",
		dataTags: "TAIBEI"
	}, {
		dataValue: "新加坡",
		dataSpac: "XJP",
		dataSzm: "SIN",
		dataTags: "XINJIAPO"
	}, {
		dataValue: "伊斯坦布尔",
		dataSpac: "YSTBE",
		dataSzm: "IST",
		dataTags: "YISITANBUER"
	}, {
		dataValue: "阿姆斯特丹",
		dataSpac: "AMSTD",
		dataSzm: "AMS",
		dataTags: "AMUSITEDAN"
	}, {
		dataValue: "吉隆坡",
		dataSpac: "JLP",
		dataSzm: "KUL",
		dataTags: "JILONGPO"
	}, {
		dataValue: "德黑兰",
		dataSpac: "DHL",
		dataSzm: "THR",
		dataTags: "DEHEILAN"
	}, {
		dataValue: "旧金山",
		dataSpac: "JJS",
		dataSzm: "SFO",
		dataTags: "JIUJINSHAN"
	}, {
		dataValue: "洛杉矶",
		dataSpac: "LSJ",
		dataSzm: "LAX",
		dataTags: "LUOSHANJI"
	}]
}