domesticDataCityJson = {
	list: [{
		groupname: "A",
		citylist: [{
			dataSpac: "AESS",
			dataValue: "阿尔山",
			dataSzm: "YIE",
			dataTags: "AERSHANSHI",
			dataType: 0
		}, {
			dataSpac: "ALSZQ",
			dataValue: "阿拉善左旗",
			dataSzm: "AXF",
			dataTags: "ALASHANZUOQI",
			dataType: 0
		}, {
			dataSpac: "ALSYQ",
			dataValue: "阿拉善右旗",
			dataSzm: "RHT",
			dataTags: "ALASHANYOUQI",
			dataType: 0
		}, {
			dataSpac: "AS",
			dataValue: "鞍山",
			dataSzm: "IOB",
			dataTags: "AN SHA",
			dataType: 0
		}, {
			dataSpac: "AQ",
			dataValue: "安庆",
			dataSzm: "AQG",
			dataTags: "ANQING",
			dataType: 0
		}, {
			dataSpac: "AY",
			dataValue: "安阳",
			dataSzm: "AYG",
			dataTags: "ANYANG",
			dataType: 0
		}, {
			dataSpac: "AS",
			dataValue: "安顺",
			dataSzm: "AVA",
			dataTags: "ANSHU",
			dataType: 0
		}, {
			dataSpac: "ALDQ",
			dataValue: "阿里",
			dataSzm: "NGQ",
			dataTags: "ALIDIQU",
			dataType: 0
		}, {
			dataSpac: "AK",
			dataValue: "安康",
			dataSzm: "AKA",
			dataTags: "ANKANG",
			dataType: 0
		}, {
			dataSpac: "AKS",
			dataValue: "阿克苏",
			dataSzm: "AKU",
			dataTags: "AKESU",
			dataType: 0
		}, {
			dataSpac: "ALT",
			dataValue: "阿勒泰",
			dataSzm: "AAT",
			dataTags: "ALETAI",
			dataType: 0
		}, {
			dataSpac: "AM",
			dataValue: "澳门",
			dataSzm: "MFM",
			dataTags: "AOMEN",
			dataType: 0
		}]
	}, {
		groupname: "B",
		citylist: [{
			dataSpac: "BJ",
			dataValue: "北京",
			dataSzm: "BJS",
			dataTags: "BEIJING",
			dataType: 0
		}, {
			dataSpac: "BT",
			dataValue: "包头",
			dataSzm: "BAV",
			dataTags: "BAOTOU",
			dataType: 0
		}, {
			dataSpac: "BYNES",
			dataValue: "巴彦淖尔",
			dataSzm: "RLK",
			dataTags: "BAYANNAOERSHI",
			dataType: 0
		}, {
			dataSpac: "BS",
			dataValue: "白山",
			dataSzm: "NBS",
			dataTags: "BAISHA",
			dataType: 0
		}, {
			dataSpac: "BH",
			dataValue: "北海",
			dataSzm: "BHY",
			dataTags: "BEIHAI",
			dataType: 0
		}, {
			dataSpac: "BSS",
			dataValue: "百色",
			dataSzm: "AEB",
			dataTags: "BAISESHI",
			dataType: 0
		}, {
			dataSpac: "BJS",
			dataValue: "毕节",
			dataSzm: "BFJ",
			dataTags: "BIJIESHI",
			dataType: 0
		}, {
			dataSpac: "BS",
			dataValue: "保山",
			dataSzm: "BSD",
			dataTags: "BAOSHA",
			dataType: 0
		}, {
			dataSpac: "BLS",
			dataValue: "博乐",
			dataSzm: "BPL",
			dataTags: "BOLESHI",
			dataType: 0
		}, {
			dataSpac: "BEJX",
			dataValue: "布尔津",
			dataSzm: "KJI",
			dataTags: "BUERJINXIAN",
			dataType: 0
		}, {
			dataSpac: "BB",
			dataValue: "蚌埠",
			dataSzm: "BFU",
			dataTags: "BENGBU",
			dataType: 0
		}, {
			dataSpac: "BC",
			dataValue: "白城",
			dataSzm: "SSSSSS",
			dataTags: "BAICHENG",
			dataType: 0
		}]
	}, {
		groupname: "C",
		citylist: [{
			dataSpac: "CZ",
			dataValue: "长治",
			dataSzm: "CIH",
			dataTags: "CHANG ZHI",
			dataType: 0
		}, {
			dataSpac: "CF",
			dataValue: "赤峰",
			dataSzm: "CIF",
			dataTags: "CHIFENG",
			dataType: 0
		}, {
			dataSpac: "CH",
			dataValue: "长海",
			dataSzm: "CNI",
			dataTags: "CHANGHAI",
			dataType: 0
		}, {
			dataSpac: "CY",
			dataValue: "朝阳",
			dataSzm: "CHG",
			dataTags: "CHAO YANG",
			dataType: 0
		}, {
			dataSpac: "CC",
			dataValue: "长春",
			dataSzm: "CGQ",
			dataTags: "CHANGCHUN",
			dataType: 0
		}, {
			dataSpac: "CZ",
			dataValue: "常州",
			dataSzm: "CZX",
			dataTags: "CHANGZHOU",
			dataType: 0
		}, {
			dataSpac: "CZS",
			dataValue: "池州",
			dataSzm: "JUH",
			dataTags: "CHIZHOUSHI",
			dataType: 0
		}, {
			dataSpac: "CS",
			dataValue: "长沙",
			dataSzm: "CSX",
			dataTags: "CHANGSHA",
			dataType: 0
		}, {
			dataSpac: "CD",
			dataValue: "常德",
			dataSzm: "CGD",
			dataTags: "CHANGDE",
			dataType: 0
		}, {
			dataSpac: "CQ",
			dataValue: "重庆",
			dataSzm: "CKG",
			dataTags: "CHONGQING",
			dataType: 0
		}, {
			dataSpac: "CD",
			dataValue: "成都",
			dataSzm: "CTU",
			dataTags: "CHENGDU",
			dataType: 0
		}, {
			dataSpac: "CDX",
			dataValue: "昌都",
			dataSzm: "BPX",
			dataTags: "CHANGDUXIAN",
			dataType: 0
		}]
	}, {
		groupname: "D",
		citylist: [{
			dataSpac: "DT",
			dataValue: "大同",
			dataSzm: "DAT",
			dataTags: "DATONG",
			dataType: 0
		}, {
			dataSpac: "DL",
			dataValue: "大连",
			dataSzm: "DLC",
			dataTags: "DA LIAN",
			dataType: 0
		}, {
			dataSpac: "DD",
			dataValue: "丹东",
			dataSzm: "DDG",
			dataTags: "DAN DONG",
			dataType: 0
		}, {
			dataSpac: "DQS",
			dataValue: "大庆",
			dataSzm: "DQA",
			dataTags: "DAQINGSHI",
			dataType: 0
		}, {
			dataSpac: "DXALDQ",
			dataValue: "大兴安岭",
			dataSzm: "JGD",
			dataTags: "DAXINGANLINGDIQU",
			dataType: 0
		}, {
			dataSpac: "DY",
			dataValue: "东营",
			dataSzm: "DOY",
			dataTags: "DONGYING",
			dataType: 0
		}, {
			dataSpac: "DZ",
			dataValue: "达州",
			dataSzm: "DAX",
			dataTags: "DAZHOU",
			dataType: 0
		}, {
			dataSpac: "DCX",
			dataValue: "稻城",
			dataSzm: "DCY",
			dataTags: "DAOCHENGXIAN",
			dataType: 0
		}, {
			dataSpac: "DL",
			dataValue: "大理",
			dataSzm: "DLU",
			dataTags: "DALI",
			dataType: 0
		}, {
			dataSpac: "DH",
			dataValue: "德宏芒市",
			dataSzm: "LUM",
			dataTags: "DEHONG",
			dataType: 0
		}, {
			dataSpac: "DQ",
			dataValue: "迪庆",
			dataSzm: "DIG",
			dataTags: "DIQING",
			dataType: 0
		}, {
			dataSpac: "DH",
			dataValue: "敦煌",
			dataSzm: "DNH",
			dataTags: "DUNHUANG",
			dataType: 0
		}, {
			dataSpac: "DZ",
			dataValue: "定州",
			dataSzm: "CCA",
			dataTags: "DINGZHOU",
			dataType: 0
		}]
	}, {
		groupname: "E",
		citylist: [{
			dataSpac: "EEDSS",
			dataValue: "鄂尔多斯",
			dataSzm: "DSN",
			dataTags: "EERDUOSISHI",
			dataType: 0
		}, {
			dataSpac: "ELHTS",
			dataValue: "二连浩特",
			dataSzm: "ERL",
			dataTags: "ERLIANHAOTESHI",
			dataType: 0
		}, {
			dataSpac: "EJNQ",
			dataValue: "额济纳旗",
			dataSzm: "EJN",
			dataTags: "EJINAQI",
			dataType: 0
		}, {
			dataSpac: "ES",
			dataValue: "恩施",
			dataSzm: "ENH",
			dataTags: "ENSHI",
			dataType: 0
		}]
	}, {
		groupname: "F",
		citylist: [{
			dataSpac: "FY",
			dataValue: "阜阳",
			dataSzm: "FUG",
			dataTags: "FUYANG",
			dataType: 0
		}, {
			dataSpac: "FZ",
			dataValue: "福州",
			dataSzm: "FOC",
			dataTags: "FUZHOU",
			dataType: 0
		}, {
			dataSpac: "FS",
			dataValue: "佛山",
			dataSzm: "FUO",
			dataTags: "FOSHA",
			dataType: 0
		}, {
			dataSpac: "FY",
			dataValue: "富蕴",
			dataSzm: "FYN",
			dataTags: "FUYU",
			dataType: 0
		}, {
			dataSpac: "FT",
			dataValue: "福田",
			dataSzm: "FTT",
			dataTags: "FUTIAN",
			dataType: 0
		}]
	}, {
		groupname: "G",
		citylist: [{
			dataSpac: "GZ",
			dataValue: "赣州",
			dataSzm: "KOW",
			dataTags: "GANZHOU",
			dataType: 0
		}, {
			dataSpac: "GZ",
			dataValue: "广州",
			dataSzm: "CAN",
			dataTags: "GUANGZHOU",
			dataType: 0
		}, {
			dataSpac: "GL",
			dataValue: "桂林",
			dataSzm: "KWL",
			dataTags: "GUILI",
			dataType: 0
		}, {
			dataSpac: "GH",
			dataValue: "广汉",
			dataSzm: "GHN",
			dataTags: "GUANGHA",
			dataType: 0
		}, {
			dataSpac: "GY",
			dataValue: "广元",
			dataSzm: "GYS",
			dataTags: "GUANGYUA",
			dataType: 0
		}, {
			dataSpac: "GY",
			dataValue: "贵阳",
			dataSzm: "KWE",
			dataTags: "GUIYANG",
			dataType: 0
		}, {
			dataSpac: "GEM",
			dataValue: "格尔木",
			dataSzm: "COQ",
			dataTags: "GEERMU",
			dataType: 0
		}, {
			dataSpac: "GYS",
			dataValue: "固原",
			dataSzm: "GYU",
			dataTags: "GUYUANSHI",
			dataType: 0
		}, {
			dataSpac: "GX",
			dataValue: "高雄",
			dataSzm: "KHH",
			dataTags: "GAOXIONG",
			dataType: 0
		}, {
			dataSpac: "GN",
			dataValue: "甘南",
			dataSzm: "GXH",
			dataTags: "GANNAN",
			dataType: 0
		}, {
			dataSpac: "GZL",
			dataValue: "公主岭",
			dataSzm: "SSSSSS",
			dataTags: "GONGZHULING",
			dataType: 0
		}]
	}, {
		groupname: "H",
		citylist: [{
			dataSpac: "HDS",
			dataValue: "邯郸",
			dataSzm: "HDG",
			dataTags: "HANDANSHI",
			dataType: 0
		}, {
			dataSpac: "HHHT",
			dataValue: "呼和浩特",
			dataSzm: "HET",
			dataTags: "HUHEHAOTE",
			dataType: 0
		}, {
			dataSpac: "HLE",
			dataValue: "呼伦贝尔",
			dataSzm: "HLD",
			dataTags: "HAILAER",
			dataType: 0
		}, {
			dataSpac: "HRB",
			dataValue: "哈尔滨",
			dataSzm: "HRB",
			dataTags: "HAERBI",
			dataType: 0
		}, {
			dataSpac: "HH",
			dataValue: "黑河",
			dataSzm: "HEK",
			dataTags: "HEIHE",
			dataType: 0
		}, {
			dataSpac: "HAS",
			dataValue: "淮安",
			dataSzm: "HIA",
			dataTags: "HUAIANSHI",
			dataType: 0
		}, {
			dataSpac: "HZ",
			dataValue: "杭州",
			dataSzm: "HGH",
			dataTags: "HANGZHOU",
			dataType: 0
		}, {
			dataSpac: "HF",
			dataValue: "合肥",
			dataSzm: "HFE",
			dataTags: "HEFEI",
			dataType: 0
		}, {
			dataSpac: "HS",
			dataValue: "黄山",
			dataSzm: "TXN",
			dataTags: "HUANGSHA",
			dataType: 0
		}, {
			dataSpac: "HY",
			dataValue: "衡阳",
			dataSzm: "HNY",
			dataTags: "HENGYANG",
			dataType: 0
		}, {
			dataSpac: "HH",
			dataValue: "怀化",
			dataSzm: "HJJ",
			dataTags: "HUAIHUA",
			dataType: 0
		}, {
			dataSpac: "HZ",
			dataValue: "惠州",
			dataSzm: "HUZ",
			dataTags: "HUIZHOU",
			dataType: 0
		}, {
			dataSpac: "HK",
			dataValue: "海口",
			dataSzm: "HAK",
			dataTags: "HAIKOU",
			dataType: 0
		}, {
			dataSpac: "HZ",
			dataValue: "汉中",
			dataSzm: "HZG",
			dataTags: "HANZHONG",
			dataType: 0
		}, {
			dataSpac: "HM",
			dataValue: "哈密",
			dataSzm: "HMT",
			dataTags: "HAMI",
			dataType: 0
		}, {
			dataSpac: "HT",
			dataValue: "和田",
			dataSzm: "HTN",
			dataTags: "HETIA",
			dataType: 0
		}, {
			dataSpac: "HL",
			dataValue: "花莲",
			dataSzm: "HUN",
			dataTags: "HUALIAN",
			dataType: 0
		}]
	}, {
		groupname: "J",
		citylist: [{
			dataSpac: "JZ",
			dataValue: "锦州",
			dataSzm: "JNZ",
			dataTags: "JIN ZHOU",
			dataType: 0
		}, {
			dataSpac: "JXS",
			dataValue: "鸡西",
			dataSzm: "JXA",
			dataTags: "JIXISHI",
			dataType: 0
		}, {
			dataSpac: "JMS",
			dataValue: "佳木斯",
			dataSzm: "JMU",
			dataTags: "JIAMUSI",
			dataType: 0
		}, {
			dataSpac: "JJ",
			dataValue: "晋江",
			dataSzm: "JJN",
			dataTags: "JINJIANG",
			dataType: 0
		}, {
			dataSpac: "JDZ",
			dataValue: "景德镇",
			dataSzm: "JDZ",
			dataTags: "JINGDEZHE",
			dataType: 0
		}, {
			dataSpac: "JJ",
			dataValue: "九江",
			dataSzm: "JIU",
			dataTags: "JIUJIANG",
			dataType: 0
		}, {
			dataSpac: "JGS",
			dataValue: "井冈山",
			dataSzm: "JGS",
			dataTags: "JINGGANGSHA",
			dataType: 0
		}, {
			dataSpac: "J",
			dataValue: "济南",
			dataSzm: "TNA",
			dataTags: "JINA",
			dataType: 0
		}, {
			dataSpac: "J",
			dataValue: "济宁",
			dataSzm: "JNG",
			dataTags: "JINING",
			dataType: 0
		}, {
			dataSpac: "JZ",
			dataValue: "荆州",
			dataSzm: "SHS",
			dataTags: "JINGZHOU",
			dataType: 0
		}, {
			dataSpac: "JYS",
			dataValue: "揭阳",
			dataSzm: "SWA",
			dataTags: "JIEYANGSHI",
			dataType: 0
		}, {
			dataSpac: "JZG",
			dataValue: "九寨沟",
			dataSzm: "JZH",
			dataTags: "JIUZHAIU",
			dataType: 0
		}, {
			dataSpac: "JH",
			dataValue: "景洪",
			dataSzm: "JHG",
			dataTags: "JINGHONG",
			dataType: 0
		}, {
			dataSpac: "JYG",
			dataValue: "嘉峪关",
			dataSzm: "JGN",
			dataTags: "JIAYUGUA",
			dataType: 0
		}, {
			dataSpac: "JCS",
			dataValue: "金昌",
			dataSzm: "JIC",
			dataTags: "JINCHANGSHI",
			dataType: 0
		}, {
			dataSpac: "JY",
			dataValue: "嘉义",
			dataSzm: "CYI",
			dataTags: "JIAYI",
			dataType: 0
		}, {
			dataSpac: "JM",
			dataValue: "金门",
			dataSzm: "KNH",
			dataTags: "JINMEN",
			dataType: 0
		}, {
			dataSpac: "JQ",
			dataValue: "酒泉",
			dataSzm: "CHW",
			dataTags: "JIUQUAN",
			dataType: 0
		}, {
			dataSpac: "JL",
			dataValue: "吉林",
			dataSzm: "JIL",
			dataTags: "JILIN",
			dataType: 0
		}, {
			dataSpac: "JA",
			dataValue: "吉安",
			dataSzm: "KNC",
			dataTags: "JIAN",
			dataType: 0
		}, {
			dataSpac: "JT",
			dataValue: "九台",
			dataSzm: "ssssss",
			dataTags: "JIUTAI",
			dataType: 0
		}, {
			dataSpac: "JZ",
			dataValue: "焦作",
			dataSzm: "sssss",
			dataTags: "JIAOZUO",
			dataType: 0
		}]
	}, {
		groupname: "K",
		citylist: [{
			dataSpac: "KDX",
			dataValue: "康定",
			dataSzm: "KGT",
			dataTags: "KANGDINGXIAN",
			dataType: 0
		}, {
			dataSpac: "KLS",
			dataValue: "凯里",
			dataSzm: "KJH",
			dataTags: "KAILISHI",
			dataType: 0
		}, {
			dataSpac: "KM",
			dataValue: "昆明",
			dataSzm: "KMG",
			dataTags: "KUNMING",
			dataType: 0
		}, {
			dataSpac: "KLMY",
			dataValue: "克拉玛依",
			dataSzm: "KRY",
			dataTags: "KELAMAYI",
			dataType: 0
		}, {
			dataSpac: "KEL",
			dataValue: "库尔勒",
			dataSzm: "KRL",
			dataTags: "KUERLE",
			dataType: 0
		}, {
			dataSpac: "KC",
			dataValue: "库车",
			dataSzm: "KCA",
			dataTags: "KUCHE",
			dataType: 0
		}, {
			dataSpac: "KS",
			dataValue: "喀什",
			dataSzm: "KHG",
			dataTags: "KESHI",
			dataType: 0
		}]
	}, {
		groupname: "L",
		citylist: [{
			dataSpac: "LLS",
			dataValue: "吕梁",
			dataSzm: "LLV",
			dataTags: "LVLIANGSHI",
			dataType: 0
		}, {
			dataSpac: "LXX",
			dataValue: "林西",
			dataSzm: "UYN",
			dataTags: "LINXIXIAN",
			dataType: 0
		}, {
			dataSpac: "LYG",
			dataValue: "连云港",
			dataSzm: "LYG",
			dataTags: "LIANYUNGANG",
			dataType: 0
		}, {
			dataSpac: "LYS",
			dataValue: "龙岩",
			dataSzm: "LCX",
			dataTags: "LONGYANSHI",
			dataType: 0
		}, {
			dataSpac: "LY",
			dataValue: "临沂",
			dataSzm: "LYI",
			dataTags: "LINYI",
			dataType: 0
		}, {
			dataSpac: "LY",
			dataValue: "洛阳",
			dataSzm: "LYA",
			dataTags: "LUOYANG",
			dataType: 0
		}, {
			dataSpac: "LHKS",
			dataValue: "老河口",
			dataSzm: "LHK",
			dataTags: "LAOHEKOUSHI",
			dataType: 0
		}, {
			dataSpac: "LZ",
			dataValue: "柳州",
			dataSzm: "LZH",
			dataTags: "LIUZHOU",
			dataType: 0
		}, {
			dataSpac: "LPX",
			dataValue: "梁平",
			dataSzm: "LIA",
			dataTags: "LIANGPINGXIAN",
			dataType: 0
		}, {
			dataSpac: "LZ",
			dataValue: "泸州",
			dataSzm: "LZO",
			dataTags: "LUZHOU",
			dataType: 0
		}, {
			dataSpac: "LP",
			dataValue: "黎平",
			dataSzm: "HZH",
			dataTags: "LIPING",
			dataType: 0
		}, {
			dataSpac: "LBX",
			dataValue: "荔波",
			dataSzm: "LLB",
			dataTags: "LIBOXIAN",
			dataType: 0
		}, {
			dataSpac: "LJ",
			dataValue: "丽江",
			dataSzm: "LJG",
			dataTags: "LIJIANG",
			dataType: 0
		}, {
			dataSpac: "LC",
			dataValue: "临沧",
			dataSzm: "LNJ",
			dataTags: "LINCANG",
			dataType: 0
		}, {
			dataSpac: "LS",
			dataValue: "拉萨",
			dataSzm: "LXA",
			dataTags: "LASA",
			dataType: 0
		}, {
			dataSpac: "LZX",
			dataValue: "林芝",
			dataSzm: "MZY",
			dataTags: "LINZHIXIAN",
			dataType: 0
		}, {
			dataSpac: "LZ",
			dataValue: "兰州",
			dataSzm: "LHW",
			dataTags: "LANZHOU",
			dataType: 0
		}, {
			dataSpac: "LPS",
			dataValue: "六盘水",
			dataSzm: "LPF",
			dataTags: "LIUPANSHUI",
			dataType: 0
		}, {
			dataSpac: "LY",
			dataValue: "辽源",
			dataSzm: "SSSSSSS",
			dataTags: "LIAOYUAN",
			dataType: 0
		}]
	}, {
		groupname: "M",
		citylist: [{
			dataSpac: "MZLS",
			dataValue: "满洲里",
			dataSzm: "NZH",
			dataTags: "MANZHOULISHI",
			dataType: 0
		}, {
			dataSpac: "MDJ",
			dataValue: "牡丹江",
			dataSzm: "MDG",
			dataTags: "MUDANJIANG",
			dataType: 0
		}, {
			dataSpac: "MHX",
			dataValue: "漠河",
			dataSzm: "OHE",
			dataTags: "MOHEXIAN",
			dataType: 0
		}, {
			dataSpac: "MZ",
			dataValue: "梅州",
			dataSzm: "MEI",
			dataTags: "MEIZHOU",
			dataType: 0
		}, {
			dataSpac: "MY",
			dataValue: "绵阳",
			dataSzm: "MIG",
			dataTags: "MIANYANG",
			dataType: 0
		}]
	}, {
		groupname: "N",
		citylist: [{
			dataSpac: "NJ",
			dataValue: "南京",
			dataSzm: "NKG",
			dataTags: "NANJING",
			dataType: 0
		}, {
			dataSpac: "NT",
			dataValue: "南通",
			dataSzm: "NTG",
			dataTags: "NANTONG",
			dataType: 0
		}, {
			dataSpac: "NB",
			dataValue: "宁波",
			dataSzm: "NGB",
			dataTags: "NINGBO",
			dataType: 0
		}, {
			dataSpac: "NC",
			dataValue: "南昌",
			dataSzm: "KHN",
			dataTags: "NANCHANG",
			dataType: 0
		}, {
			dataSpac: "NY",
			dataValue: "南阳",
			dataSzm: "NNY",
			dataTags: "NANYANG",
			dataType: 0
		}, {
			dataSpac: "N",
			dataValue: "南宁",
			dataSzm: "NNG",
			dataTags: "NANNING",
			dataType: 0
		}, {
			dataSpac: "NC",
			dataValue: "南充",
			dataSzm: "NAO",
			dataTags: "NANCHONG",
			dataType: 0
		}, {
			dataSpac: "NJ",
			dataValue: "嫩江",
			dataSzm: "NNN",
			dataTags: "NENGJIANG",
			dataType: 0
		}, {
			dataSpac: "NA",
			dataValue: "农安",
			dataSzm: "SSSSSSS",
			dataTags: "NONGAN",
			dataType: 0
		}]
	}, {
		groupname: "P",
		citylist: [{
			dataSpac: "PZH",
			dataValue: "攀枝花",
			dataSzm: "PZI",
			dataTags: "PANZHIHUA",
			dataType: 0
		}, {
			dataSpac: "PE",
			dataValue: "普洱",
			dataSzm: "SYM",
			dataTags: "PUER",
			dataType: 0
		}, {
			dataSpac: "PH",
			dataValue: "澎湖",
			dataSzm: "MZG",
			dataTags: "PENGHU",
			dataType: 0
		}]
	}, {
		groupname: "Q",
		citylist: [{
			dataSpac: "QHD",
			dataValue: "秦皇岛",
			dataSzm: "SHF",
			dataTags: "QINHUANGDAO",
			dataType: 0
		}, {
			dataSpac: "QQHE",
			dataValue: "齐齐哈尔",
			dataSzm: "NDG",
			dataTags: "QIQIHAER",
			dataType: 0
		}, {
			dataSpac: "QZ",
			dataValue: "衢州",
			dataSzm: "JUZ",
			dataTags: "QUZHOU",
			dataType: 0
		}, {
			dataSpac: "QD",
			dataValue: "青岛",
			dataSzm: "TAO",
			dataTags: "QINGDAO",
			dataType: 0
		}, {
			dataSpac: "QJS",
			dataValue: "黔江市",
			dataSzm: "JIQ",
			dataTags: "QIANJIANGSHI",
			dataType: 0
		}, {
			dataSpac: "QY",
			dataValue: "庆阳",
			dataSzm: "IQN",
			dataTags: "QINGYANG",
			dataType: 0
		}, {
			dataSpac: "QM",
			dataValue: "且末",
			dataSzm: "IQM",
			dataTags: "QIEMO",
			dataType: 0
		}]
	}, {
		groupname: "R",
		citylist: [{
			dataSpac: "RKZS",
			dataValue: "日喀则",
			dataSzm: "RKZ",
			dataTags: "RIKAZESHI",
			dataType: 0
		}]
	}, {
		groupname: "S",
		citylist: [{
			dataSpac: "SJZ",
			dataValue: "石家庄",
			dataSzm: "SJW",
			dataTags: "SHIJIAZHUANG",
			dataType: 0
		}, {
			dataSpac: "SY",
			dataValue: "沈阳",
			dataSzm: "SHE",
			dataTags: "SHEN YANG",
			dataType: 0
		}, {
			dataSpac: "SH",
			dataValue: "上海",
			dataSzm: "SHA",
			dataTags: "SHANGHAI",
			dataType: 0
		}, {
			dataSpac: "SZ",
			dataValue: "深圳",
			dataSzm: "SZX",
			dataTags: "SHENZHE",
			dataType: 0
		}, {
			dataSpac: "SY",
			dataValue: "三亚",
			dataSzm: "SYX",
			dataTags: "SANYA",
			dataType: 0
		}, {
			dataSpac: "SY",
			dataValue: "十堰",
			dataSzm: "WDS",
			dataTags: "SHIYAN",
			dataType: 0
		}, {
			dataSpac: "SG",
			dataValue: "韶关",
			dataSzm: "HSC",
			dataTags: "SHAOGUAN",
			dataType: 0
		}, {
			dataSpac: "SH",
			dataValue: "沙市",
			dataSzm: "SHS",
			dataTags: "SHASHI",
			dataType: 0
		}, {
			dataSpac: "SZ",
			dataValue: "苏州",
			dataSzm: "SZV",
			dataTags: "SHUZHOU",
			dataType: 0
		}, {
			dataSpac: "SP",
			dataValue: "四平",
			dataSzm: "SSSSS",
			dataTags: "SIPING",
			dataType: 0
		}, {
			dataSpac: "SY",
			dataValue: "松原",
			dataSzm: "SSSSSS",
			dataTags: "SONGYUANG",
			dataType: 0
		}]
	}, {
		groupname: "T",
		citylist: [{
			dataSpac: "TJ",
			dataValue: "天津",
			dataSzm: "TSN",
			dataTags: "TIANJI",
			dataType: 0
		}, {
			dataSpac: "TSS",
			dataValue: "唐山",
			dataSzm: "TVS",
			dataTags: "TANGSHANSHI",
			dataType: 0
		}, {
			dataSpac: "TY",
			dataValue: "太原",
			dataSzm: "TYN",
			dataTags: "TAIYUA",
			dataType: 0
		}, {
			dataSpac: "TL",
			dataValue: "通辽",
			dataSzm: "TGO",
			dataTags: "TONGLIAO",
			dataType: 0
		}, {
			dataSpac: "TZ",
			dataValue: "台州",
			dataSzm: "HYN",
			dataTags: "TAIZHOU",
			dataType: 0
		}, {
			dataSpac: "TR",
			dataValue: "铜仁",
			dataSzm: "TEN",
			dataTags: "TONGREN",
			dataType: 0
		}, {
			dataSpac: "TCX",
			dataValue: "腾冲",
			dataSzm: "TCZ",
			dataTags: "TENGCHONGXIAN",
			dataType: 0
		}, {
			dataSpac: "TSS",
			dataValue: "天水",
			dataSzm: "THQ",
			dataTags: "TIANSHUISHI",
			dataType: 0
		}, {
			dataSpac: "TLFS",
			dataValue: "吐鲁番",
			dataSzm: "TLQ",
			dataTags: "TULUFANSHI",
			dataType: 0
		}, {
			dataSpac: "TC",
			dataValue: "塔城",
			dataSzm: "TCG",
			dataTags: "TACHENG",
			dataType: 0
		}, {
			dataSpac: "TB",
			dataValue: "台北",
			dataSzm: "TPE",
			dataTags: "TAIBEI",
			dataType: 0
		}, {
			dataSpac: "TZ",
			dataValue: "台中",
			dataSzm: "RMQ",
			dataTags: "TAIZHONG",
			dataType: 0
		}, {
			dataSpac: "TD",
			dataValue: "台东",
			dataSzm: "TTT",
			dataTags: "TAIDONG",
			dataType: 0
		}, {
			dataSpac: "TH",
			dataValue: "通化",
			dataSzm: "ssss",
			dataTags: "TONGHUA",
			dataType: 0
		}]
	}, {
		groupname: "W",
		citylist: [{
			dataSpac: "WH",
			dataValue: "乌海",
			dataSzm: "WUA",
			dataTags: "WUHAI",
			dataType: 0
		}, {
			dataSpac: "WLHT",
			dataValue: "乌兰浩特",
			dataSzm: "HLH",
			dataTags: "WULANHAOTE",
			dataType: 0
		}, {
			dataSpac: "WX",
			dataValue: "无锡",
			dataSzm: "WUX",
			dataTags: "WUXI",
			dataType: 0
		}, {
			dataSpac: "WZ",
			dataValue: "温州",
			dataSzm: "WNZ",
			dataTags: "WENZHOU",
			dataType: 0
		}, {
			dataSpac: "WYS",
			dataValue: "武夷山",
			dataSzm: "WUS",
			dataTags: "WUYISHA",
			dataType: 0
		}, {
			dataSpac: "WF",
			dataValue: "潍坊",
			dataSzm: "WEF",
			dataTags: "WEIFANG",
			dataType: 0
		}, {
			dataSpac: "WH",
			dataValue: "威海",
			dataSzm: "WEH",
			dataTags: "WEIHAI",
			dataType: 0
		}, {
			dataSpac: "WH",
			dataValue: "武汉",
			dataSzm: "WUH",
			dataTags: "WUHA",
			dataType: 0
		}, {
			dataSpac: "WZ",
			dataValue: "梧州",
			dataSzm: "WUZ",
			dataTags: "WUZHOU",
			dataType: 0
		}, {
			dataSpac: "WZS",
			dataValue: "万州市",
			dataSzm: "WXN",
			dataTags: "WANZHOUSHI",
			dataType: 0
		}, {
			dataSpac: "WSS",
			dataValue: "文山",
			dataSzm: "WSS",
			dataTags: "WENSHANSHI",
			dataType: 0
		}, {
			dataSpac: "WLMQ",
			dataValue: "乌鲁木齐",
			dataSzm: "URC",
			dataTags: "WULUMUQI",
			dataType: 0
		}, {
			dataSpac: "WLCB",
			dataValue: "乌兰察布",
			dataSzm: "UCB",
			dataTags: "WULANCHABU",
			dataType: 0
		}]
	}, {
		groupname: "X",
		citylist: [{
			dataSpac: "XLHT",
			dataValue: "锡林浩特",
			dataSzm: "XIL",
			dataTags: "XINLINHAOTE",
			dataType: 0
		}, {
			dataSpac: "XC",
			dataValue: "兴城",
			dataSzm: "XEN",
			dataTags: "XING CHENG",
			dataType: 0
		}, {
			dataSpac: "XZ",
			dataValue: "徐州",
			dataSzm: "XUZ",
			dataTags: "XUZHOU",
			dataType: 0
		}, {
			dataSpac: "XM",
			dataValue: "厦门",
			dataSzm: "XMN",
			dataTags: "XIAME",
			dataType: 0
		}, {
			dataSpac: "XY",
			dataValue: "襄阳",
			dataSzm: "XFN",
			dataTags: "XIANGYANG",
			dataType: 0
		}, {
			dataSpac: "XC",
			dataValue: "西昌",
			dataSzm: "XIC",
			dataTags: "XICHANG",
			dataType: 0
		}, {
			dataSpac: "XY",
			dataValue: "兴义",
			dataSzm: "ACX",
			dataTags: "XINGYI",
			dataType: 0
		}, {
			dataSpac: "XA",
			dataValue: "西安",
			dataSzm: "XIY",
			dataTags: "XIA",
			dataType: 0
		}, {
			dataSpac: "XHX",
			dataValue: "夏河",
			dataSzm: "GXH",
			dataTags: "XIAHEXIAN",
			dataType: 0
		}, {
			dataSpac: "X",
			dataValue: "西宁",
			dataSzm: "XNN",
			dataTags: "XINING",
			dataType: 0
		}, {
			dataSpac: "XYX",
			dataValue: "新源",
			dataSzm: "NLT",
			dataTags: "XINYUANXIAN",
			dataType: 0
		}, {
			dataSpac: "XG",
			dataValue: "香港",
			dataSzm: "HKG",
			dataTags: "XIANGGANG",
			dataType: 0
		}, {
			dataSpac: "XT",
			dataValue: "邢台",
			dataSzm: "XNT",
			dataTags: "XINGTAI",
			dataType: 0
		}]
	}, {
		groupname: "Y",
		citylist: [{
			dataSpac: "YC",
			dataValue: "运城",
			dataSzm: "YCU",
			dataTags: "YUNCHENG",
			dataType: 0
		}, {
			dataSpac: "YJ",
			dataValue: "延吉",
			dataSzm: "YNJ",
			dataTags: "YANJI",
			dataType: 0
		}, {
			dataSpac: "YCS",
			dataValue: "伊春",
			dataSzm: "LDS",
			dataTags: "YICHUNSHI",
			dataType: 0
		}, {
			dataSpac: "YC",
			dataValue: "盐城",
			dataSzm: "YNZ",
			dataTags: "YANCHENG",
			dataType: 0
		}, {
			dataSpac: "YZS",
			dataValue: "扬州",
			dataSzm: "YTY",
			dataTags: "YANGZHOUSHI",
			dataType: 0
		}, {
			dataSpac: "YW",
			dataValue: "义乌",
			dataSzm: "YIW",
			dataTags: "YIWU",
			dataType: 0
		}, {
			dataSpac: "YT",
			dataValue: "烟台",
			dataSzm: "YNT",
			dataTags: "YANTAI",
			dataType: 0
		}, {
			dataSpac: "YC",
			dataValue: "宜昌",
			dataSzm: "YIH",
			dataTags: "YICHANG",
			dataType: 0
		}, {
			dataSpac: "YZ",
			dataValue: "永州",
			dataSzm: "LLF",
			dataTags: "YONGZHOU",
			dataType: 0
		}, {
			dataSpac: "YB",
			dataValue: "宜宾",
			dataSzm: "YBP",
			dataTags: "YIBI",
			dataType: 0
		}, {
			dataSpac: "YA",
			dataValue: "延安",
			dataSzm: "ENY",
			dataTags: "YANA",
			dataType: 0
		}, {
			dataSpac: "YL",
			dataValue: "榆林",
			dataSzm: "UYN",
			dataTags: "YULI",
			dataType: 0
		}, {
			dataSpac: "YSS",
			dataValue: "玉树",
			dataSzm: "YUS",
			dataTags: "YUSHUSHI",
			dataType: 0
		}, {
			dataSpac: "YC",
			dataValue: "银川",
			dataSzm: "INC",
			dataTags: "YINCHUA",
			dataType: 0
		}, {
			dataSpac: "Y",
			dataValue: "伊宁",
			dataSzm: "YIN",
			dataTags: "YINING",
			dataType: 0
		}]
	}, {
		groupname: "Z",
		citylist: [{
			dataSpac: "ZJKS",
			dataValue: "张家口",
			dataSzm: "ZQZ",
			dataTags: "ZHANGJIAKOUSHI",
			dataType: 0
		}, {
			dataSpac: "ZS",
			dataValue: "舟山",
			dataSzm: "HSN",
			dataTags: "ZHOUSHA",
			dataType: 0
		}, {
			dataSpac: "ZZ",
			dataValue: "郑州",
			dataSzm: "CGO",
			dataTags: "ZHENGZHOU",
			dataType: 0
		}, {
			dataSpac: "ZJJ",
			dataValue: "张家界",
			dataSzm: "DYG",
			dataTags: "ZHANGJIAJIE",
			dataType: 0
		}, {
			dataSpac: "ZH",
			dataValue: "珠海",
			dataSzm: "ZUH",
			dataTags: "ZHUHAI",
			dataType: 0
		}, {
			dataSpac: "ZJS",
			dataValue: "湛江",
			dataSzm: "ZHA",
			dataTags: "ZHANJIANGSHI",
			dataType: 0
		}, {
			dataSpac: "ZY",
			dataValue: "遵义",
			dataSzm: "ZYI",
			dataTags: "ZUIYI",
			dataType: 0
		}, {
			dataSpac: "ZT",
			dataValue: "昭通",
			dataSzm: "ZAT",
			dataTags: "ZHAOTONG",
			dataType: 0
		}, {
			dataSpac: "ZYS",
			dataValue: "张掖",
			dataSzm: "YZY",
			dataTags: "ZHANGYESHI",
			dataType: 0
		}, {
			dataSpac: "ZWS",
			dataValue: "中卫",
			dataSzm: "ZHY",
			dataTags: "ZHONGWEISHI",
			dataType: 0
		}]
	}],
	hotList: [{
		dataSpac: "BJ",
		dataValue: "北京",
		dataSzm: "BJS",
		dataTags: "BEIJING",
		dataType: 0
	}, {
		dataSpac: "TJ",
		dataValue: "天津",
		dataSzm: "TSN",
		dataTags: "TIANJI",
		dataType: 0
	}, {
		dataSpac: "DL",
		dataValue: "大连",
		dataSzm: "DLC",
		dataTags: "DA LIAN",
		dataType: 0
	}, {
		dataSpac: "CC",
		dataValue: "长春",
		dataSzm: "CGQ",
		dataTags: "CHANGCHUN",
		dataType: 0
	}, {
		dataSpac: "SH",
		dataValue: "上海",
		dataSzm: "SHA",
		dataTags: "SHANGHAI",
		dataType: 0
	}, {
		dataSpac: "NJ",
		dataValue: "南京",
		dataSzm: "NKG",
		dataTags: "NANJING",
		dataType: 0
	}, {
		dataSpac: "HZ",
		dataValue: "杭州",
		dataSzm: "HGH",
		dataTags: "HANGZHOU",
		dataType: 0
	}, {
		dataSpac: "XM",
		dataValue: "厦门",
		dataSzm: "XMN",
		dataTags: "XIAME",
		dataType: 0
	}, {
		dataSpac: "J",
		dataValue: "济南",
		dataSzm: "TNA",
		dataTags: "JINA",
		dataType: 0
	}, {
		dataSpac: "QD",
		dataValue: "青岛",
		dataSzm: "TAO",
		dataTags: "QINGDAO",
		dataType: 0
	}, {
		dataSpac: "ZZ",
		dataValue: "郑州",
		dataSzm: "CGO",
		dataTags: "ZHENGZHOU",
		dataType: 0
	}, {
		dataSpac: "WH",
		dataValue: "武汉",
		dataSzm: "WUH",
		dataTags: "WUHA",
		dataType: 0
	}, {
		dataSpac: "CS",
		dataValue: "长沙",
		dataSzm: "CSX",
		dataTags: "CHANGSHA",
		dataType: 0
	}, {
		dataSpac: "GZ",
		dataValue: "广州",
		dataSzm: "CAN",
		dataTags: "GUANGZHOU",
		dataType: 0
	}, {
		dataSpac: "SZ",
		dataValue: "深圳",
		dataSzm: "SZX",
		dataTags: "SHENZHE",
		dataType: 0
	}, {
		dataSpac: "SY",
		dataValue: "三亚",
		dataSzm: "SYX",
		dataTags: "SANYA",
		dataType: 0
	}, {
		dataSpac: "CQ",
		dataValue: "重庆",
		dataSzm: "CKG",
		dataTags: "CHONGQING",
		dataType: 0
	}, {
		dataSpac: "CD",
		dataValue: "成都",
		dataSzm: "CTU",
		dataTags: "CHENGDU",
		dataType: 0
	}, {
		dataSpac: "KM",
		dataValue: "昆明",
		dataSzm: "KMG",
		dataTags: "KUNMING",
		dataType: 0
	}, {
		dataSpac: "XA",
		dataValue: "西安",
		dataSzm: "XIY",
		dataTags: "XIA",
		dataType: 0
	}]
}